api/includes/pages/class.proposal.php, client/js/modules/fault/views/add.js
Fix for problem with new fault reports: Doesn't show ongoing visits. (MXSW-482)
=> New fault: Show started visits, not just previous visits.

api/includes/class.page.php
Adding braces in these positions allows SynchWeb to work with PHP 7.
=> Make the pages class work with PHP 7

api/formulatrix/uploader/config.json.sample, api/formulatrix/uploader/formulatrix_uploader.py
This will allow logging to graylog, and also wraps some critical parts related to file access in try ... except so it doesn't fall over so easily. 
Also a bug fix on your line 220 - referencing the wrong variable (ty).
=> Logging and robustification

api/formulatrix/uploader/formulatrix_uploader.py
Lines 116 - 118: Changes to use new file non-year directory structure
Lines 134 - 136: Handle permission denied
Lines 301 - 308: Run as daemon (i.e. in background, so script can be started with 'python formulatrix_uploader.py'.
=> Run as daemon + use new non-year dir structure

api/formulatrix/uploader/config.json.sample, api/formulatrix/uploader/formulatrix_uploader.py
This is the problem we discussed, Stu, regarding sessions in the old directory structure that are still active
=> Check new AND old visit location for images

api/includes/pages/class.dc.php, client/js/modules/dc/controller.js, client/js/modules/dc/router.js, client/js/modules/dc/views/apstatusitem.js, client/js/modules/dc/views/apstatussummary.js, client/js/templates/dc/apstatussummary.html, client/js/templates/dc/dc.html, client/js/templates/dc/dclist.html
Up-to-date list of auto processing status flags and a new page with a table listing auto processing status flags for all data collections in a visit.
=> Auto processing flags and a summary table

api/formulatrix/uploader/config.json.sample, api/formulatrix/uploader/formulatrix_uploader.py
This new pull request apparently includes my previous pull request as well.
=> Enable 'port' as a config parameter

api/includes/pages/class.image.php, api/includes/pages/class.proposal.php, api/includes/pages/class.shipment.php, client/js/views/status.js
Merge fixes to status element on datacollections/activity stream page when showing webcams.
=> Merge staging changes for webcam fix

README.md
Also, it would be nice to make the same change to the website URL of the project on GitHub which I cannot do as a PR.
=> Use HTTPS URLs in README.md

api/formulatrix/uploader/formulatrix_uploader.py, api/includes/pages/class.shipment.php, api/includes/pages/class.status.php, client/js/modules/assign/controller.js, client/js/modules/fault/controller.js, client/js/modules/imaging/controller.js, client/js/modules/shipment/controller.js, client/js/modules/stats/controller.js
Couldnt looks really clumsy...
=> Countn't has ' in; viist

api/src/Page/Shipment.php
=> SCI-9049 remove redundant join

api/src/Database/Type/MySQL.php, api/src/Database/Type/Result53.php
Needed this back for working on the old dev
=> php5.3 compat

api/src/Database/Type/MySQL.php, api/src/Database/Type/Result53.php, api/src/Page/Sample.php
issue with cluster read / write synchronisation
=> vmxi-650 - subsample creation issue

client/webpack.config.js
add history api fallback to npm dev webserver
=> add history api fallback

api/src/Page/DC.php
correct dcid count, expand dc group when viewing processing job
=> sci-8153 processing job count updates

client/src/js/templates/types/gen/samples/sample.html
missing subsample holder breaks all none mx sample view pages
=> add subsamples to general sample type

api/scripts/cbf2jpg.sh, api/scripts/dls/environ.sh, api/scripts/dls/reprocess.sh, api/scripts/dls/submit.sh, api/scripts/mtz2map.sh
Also noted in comments which scripts are deprecated
=> Fixed ccp4 version for mtz2map script 

client/src/css/partials/_header.scss, client/src/index.php, client/src/js/config_sample.json, client/webpack.config.js
Allows some local customisation, changing site name, url, header image from config.json (and builds into webpack bundle)
Allow specifiying port and proxy location as --env on npm run server
(rebased off master)
=> Local customisation

api/src/Page.php, api/src/Page/Cell.php, api/src/Page/DC.php, api/src/Page/Download.php, api/src/Page/EM.php, api/src/Page/Exp.php, api/src/Page/Image.php, api/src/Page/PDF.php, api/src/Page/Process.php, api/src/Page/Proposal.php, api/src/Page/Stats.php, api/src/Page/Vstat.php, api/src/TemplateParser.php
rebase on master, resolve EM.php merge conflicts, add dc counts from dcg for visit list
=> mxsw-938 migrate dc.sessionid -> dcg.sessionid

api/src/Page/DC.php, client/src/js/templates/cell/item.html, client/src/js/templates/dc/dc.html, client/src/js/templates/dc/dc_strategy.html, client/src/js/templates/dc/grid.html, client/src/js/templates/dc/reprocess_dc.html, client/src/js/templates/mc/datacollection.html
Get rotationaxis name from the relevant column rather than hard coding it
=> Remove hardcoded omega axis

api/src/Page/Sample.php
=> php5.4 compatibility

api/src/Page/Sample.php, client/src/js/models/sample.js, client/src/js/modules/shipment/views/sampletable.js, client/src/js/templates/shipment/sampletable.html, client/src/js/templates/shipment/sampletablenew.html, client/src/js/templates/shipment/sampletablerow.html, client/src/js/templates/shipment/sampletablerowedit.html, client/src/js/templates/shipment/sampletablerownew.html, client/src/js/utils/validation.js
=> SCI-7989: sample user folder

api/src/Page/DC.php
need to groupby autoprocprogram as well as failed jobs have apss = NULL => single row
=> sci-9072 - missing failed jobs in autoproc list

README.md, api/config_sample.php, api/index.php, api/src/Page/Sample.php, client/src/css/partials/_form.scss, client/src/js/app.js, client/src/js/modules/samples/controller.js, client/src/js/modules/samples/views/proteinlist.js, client/src/js/modules/shipment/views/container.js, client/src/js/modules/shipment/views/containeradd.js, client/src/js/modules/shipment/views/sampletable.js, client/src/js/modules/shipment/views/singlesample.js, client/src/js/templates/samples/proteinlist.html
=> make valid_components server side

api/src/Database/Type/MySQL.php, api/src/Page/Shipment.php, client/src/js/modules/shipment/collections/dewarproposals.js, client/src/js/modules/shipment/controller.js, client/src/js/modules/shipment/models/dewarproposal.js, client/src/js/modules/shipment/models/dewarregistry.js, client/src/js/modules/shipment/router.js, client/src/js/modules/shipment/views/containerregistry.js, client/src/js/modules/shipment/views/dewarregistry.js, client/src/js/modules/shipment/views/regdewar.js, client/src/js/modules/types/mx/menu.js, client/src/js/templates/shipment/dewarregistry.html, client/src/js/templates/shipment/dewarregistryadd.html, client/src/js/templates/shipment/regdewar.html
=> I03-305: Allow registered dewars to belong to more than one proposal

client/src/js/modules/dc/views/dc.js, client/src/js/modules/dc/views/dcbase.js, client/src/js/modules/dc/views/edge.js, client/src/js/modules/dc/views/grid.js, client/src/js/modules/dc/views/mca.js, client/src/js/modules/types/em/dc/dc.js, client/src/js/modules/types/gen/dc/dc.js, client/src/js/modules/types/pow/dc/dc.js, client/src/js/modules/types/saxs/dc/dc.js, client/src/js/templates/dc/dc.html, client/src/js/templates/dc/dc_title.html, client/src/js/templates/dc/edge.html, client/src/js/templates/dc/grid.html, client/src/js/templates/dc/mca.html, client/src/js/templates/types/em/dc/dc.html, client/src/js/templates/types/gen/dc/dc.html, client/src/js/templates/types/pow/dc/dc.html, client/src/js/templates/types/saxs/dc/dc.html, client/src/js/templates/types/tomo/dc/dc.html, client/src/js/templates/types/xpdf/dc/dc.html
This has become a bit more involved than i expected. Trying to centralise a lot of duplicate dc code at the same time as allowing views to update themselves
=> sci-8602 centralise dc view code and allow update in place

client/src/js/templates/dc/dclist.html
and fix up the message wording a bit
=> When a visit is archived hide the autorefresh box

client/webpack.config.js
=> Remove assets as proxy target in webpack dev server

api/src/Page.php
Also added comments and minor refactoring
=> LDAP lookup should use uid for fedid not cn

client/src/js/modules/dc/views/summary.js
Be more informative about no successful aps
Fix infinite loading
Autoselect 0th ap if only one
=> Fix up ap summary page

.gitignore, api/src/Page/DC.php, client/src/js/templates/dc/dc_autoproc.html
This PR changes how refined x and y beam values are displayed by formatting only values that are numeric.
=> Fix: Change how beam values are displayed

api/src/Page/Download.php
and centralise mime / content type code (untested, cant get symfony::file installed on php 5.4!)
=> Apply mime types to dc attachments

.gitignore, client/package-lock.json, client/package.json, client/src/js/modules/calendar/views/calendar.js, client/src/js/modules/shipment/views/container.js, client/src/js/modules/shipment/views/dewarregistry.js, client/src/js/modules/stats/views/breakdown.js, client/src/js/modules/types/em/relion/views/relion.js, client/src/js/modules/types/em/scipion/views/scipion.js, client/webpack.config.js
This PR fixes the invalid parsing of ISO-8601 string without timezone
=> Fix: Add date-fns and date-fns-tz to solve issue of date parsing

api/src/Page/Proposal.php
rebase on master...
I think startdate / enddate are only used for visit management, but i need to check
related: https://github.com/DiamondLightSource/SynchWeb/pull/174
=> i04_1-618: make visit model valid and fix editing comments

client/src/js/modules/dc/controller.js, client/src/js/modules/dc/datacollections.js, client/src/js/templates/dc/dclist.html, client/src/js/templates/types/em/dc/dclist.html, client/src/js/templates/types/gen/dc/dclist.html, client/src/js/templates/types/xpdf/dc/dclist.html
also show visit and beamline for data collections list
=> sci-9453: add sub header for dcg and pj data collection views

api/src/Page/DC.php, api/src/Page/Image.php, api/src/TemplateParser.php
Need to check this is still performant as it does a few extra queries for the template parser
=> sci-9302: make image tests and serving consistent

api/assets/pdf/shipment_label.php, api/assets/pdf/styles.css, api/src/Page/PDF.php
This PR adds the containers barcode of a dewar to the shipping label
=> feat: add containers barcode to shipping label

.gitignore, api/src/Page/Shipment.php, client/src/js/modules/shipment/models/dewarhistory.js, client/src/js/modules/shipment/views/dispatch.js, client/src/js/templates/shipment/dispatch.html
[Synchweb: Only allow dispatch requests if dewar is in the dewar store [SCI-9933]](https://jira.diamond.ac.uk/browse/SCI-9933)
=> Fix: Add warning message to dewar dispatch page

.gitignore, api/src/Page/Shipment.php, client/src/js/modules/shipment/models/transfer.js, client/src/js/modules/shipment/views/dewars.js, client/src/js/modules/shipment/views/transfer.js, client/src/js/utils/kvcollection.js, client/src/js/utils/validation.js
[After a Visit Allow Users to Return a Dewar to the Scheduling Queue](https://jira.diamond.ac.uk/browse/I03-589)
=> Feature: Allow user to return dewar to scheduling queue

.gitignore, client/src/js/app/index.js, client/src/js/modules/dc/components/dc-wrapper.vue, client/src/js/modules/dc/views/gridplot.js, client/src/js/modules/imaging/views/imageviewer.js, client/src/js/templates/dc/gridplot.html
[Add "Hide Results" to drop-down menu showing grid scan results](https://jira.diamond.ac.uk/browse/MXSW-1176)
=> Feature: Add "None" type to grid scan dropdown

client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
This PR fixes the issue with scheduling the information for plates on synchweb.
[Scheduling Information For Plates Not Been Saved Via Synchweb](https://jira.diamond.ac.uk/browse/VMXI-890)
=> Fix: Scheduling Information For Plates Not Been Saved Via Synchweb

api/src/Page/Proposal.php, api/src/UAS.php
This PR adds the functionality of sending used time information to UAS when a session is closed
[Update delivered time for UDC sessions ](https://jira.diamond.ac.uk/browse/SCI-9816)
=> Feature: Add used time report when closing an auto-collected session

api/src/Page/Shipment.php, client/src/js/modules/shipment/views/dewars.js
This PR fixes the issue of fields on the dewar form refreshing and not persisting its inputted data
[SCI-28166](https://jira.diamond.ac.uk/browse/SCI-28166)
=> Fix: Change modelEvent for dewars view

client/src/js/modules/submission/views/conexs-submission.vue
I've added important references to main calculators, as well as made simpler request to MP API (tested on local podman run only, may still not work on production).
=> Pre release/2022 r3.2

api/src/Page/DC.php
This PR changes the number of decimal points value returned for the exposure time on the data collection page
[IO4-637](https://jira.diamond.ac.uk/browse/I04-637)
=> [IO4-637]Feature: make exposure time return values in 4 decimal places for data collection

client/src/js/app/components/pv-item.vue, client/src/js/modules/status/views/beamline-status-view.vue, client/src/js/views/pvs-stream.js
This PR fixes the issue with webcam images and machine messages not displaying on the beamline status page
[I03-760](https://jira.diamond.ac.uk/browse/I03-760)
=> [IO3-760]Fix: Add functionality to display webcam and machine message for beamline status page

api/src/Page/Shipment.php
This PR adds the ability to search for registered dewars by the proposal code or number
[Registered Dewars search doesn't search proposals](https://jira.diamond.ac.uk/browse/I03-686)
=> [I03-686]Feature: Add search by proposal functionality for registered dewars endpoint

api/src/Page/Sample.php, client/src/js/collections/subsamples.js, client/src/js/modules/imaging/views/imagehistory.js, client/src/js/modules/imaging/views/imageviewer.js, client/src/js/modules/imaging/views/queuecontainer.js, client/src/js/modules/shipment/views/containerplate.js
This PR adds auto generated subsamples points to the container view and container queue pages
[VMXI-862 Add Automatically Detected Crystal Points To SynchWeb Display](https://jira.diamond.ac.uk/browse/VMXI-862)
=> [VMXI-862]Feature: Add latest auto sub-sample points to container view and container queue pages

api/src/Page/Sample.php, api/src/Page/Shipment.php
remove source = 'manual' in where clause when queuing container
=> [LIMS-74]Fix: Auto Points Not Getting Queued For Container

client/src/js/app/mixins/vee-validate-custom-rules.js, client/src/js/modules/types/mx/samples/tabbed-columns-view.vue
[Screen & collect: Collect best of N accepts decimal places and it should not](https://jira.diamond.ac.uk/browse/LIMS-97)
=> [LIMS-97]Fix: Change validation logic for non_zero numeric values

client/src/js/modules/types/mx/samples/mx-puck-samples-table.vue, client/src/js/modules/types/mx/samples/sample-table-mixin.js, client/src/js/modules/types/mx/samples/sample-table-row.vue, client/src/js/modules/types/mx/samples/tabbed-columns-view.vue, client/src/js/modules/types/mx/shipment/views/container-mixin.js, client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
change how SCREENINGCOLLECTVALUE value is updated when adding samples
=> [LIMS-96]Fix: Make collect best value same for sample in group

api/src/Page/DC.php, client/src/js/templates/dc/dc_title.html
[Synchweb - List data collection groups by max(starttime) instead of min(starttime)](https://jira.diamond.ac.uk/browse/I03-372)
=> [I03-372]Fix: Display data collection group by max(starttime) instead of min(starttime)

client/src/js/app/store/store.js, client/src/js/modules/calendar/views/calendar-view.vue, client/src/js/modules/calendar/views/components/calendar-day-events.vue
This PR fixes the timezone issue with displaying database time value on synchweb calender ciew
[Synchweb: Wrong time zone in calendar view](https://jira.diamond.ac.uk/browse/I03-769)
=> [I03-769]Fix: Wrong time in calendar view

api/src/Authentication.php
[Deploy improved "DELETE FROM SW_onceToken ..." statement](https://jira.diamond.ac.uk/browse/SCI-10247)
=> [SCI-10247]Fix: Use calculated constant to delete expired one-time download tokens

api/src/Page/Sample.php, client/src/js/app.js, client/src/js/app/components/custom-dialog-box.vue, client/src/js/app/marionette-application.js, client/src/js/app/store/store.js, client/src/js/modules/types/mx/samples/move-sample-to-container.vue, client/src/js/modules/types/mx/samples/mx-puck-samples-table.vue, client/src/js/modules/types/mx/samples/sample-table-row.vue, client/src/js/modules/types/mx/shipment/views/container-mixin.js, client/src/js/modules/types/mx/shipment/views/mx-container-view.vue
[Ability to move samples from one container to another](https://jira.diamond.ac.uk/browse/I23-1110)
=> [I23-1110]Feature: Add ability to move samples from one container to another

api/src/Page/PDF.php
**JIRA ticket:** [LIMS-200](https://jira.diamond.ac.uk/projects/LIMS/issues/LIMS-200)
**Changes:**
- Trim trailing whitespace from laboratory address before adding it to the shipping label
- Change shipping label address line breaks from being appended to prepended to address lines
**To test:**
- Check that addresses on shipping labels are formatted correctly for addresses of all allowed lengths
=> [LIMS-200]Fix: Fix shipping label address

api/src/Page/Shipment.php, api/src/Shipment/Courier/DHL.php, client/src/js/modules/shipment/views/createawb.js
**JIRA ticket:** [LIMS-201](https://jira.diamond.ac.uk/browse/LIMS-201)
**Changes:**
- Populate Shipper->ShipperID  and Reference->ReferenceID elements of the shipment request with the proposal code
**To test:**
- Check that the proposal code appears on the DHL air waybill and invoices
=> [LIMS-201]Improvement: Populate invoice shippers reference

api/assets/emails/dewar-dispatch.html, api/assets/emails/html/dewar-dispatch.html, api/src/Page/PDF.php, api/src/Page/Shipment.php, client/src/js/modules/shipment/controller.js, client/src/js/modules/shipment/routes.js, client/src/js/modules/shipment/views/createawb.js, client/src/js/templates/shipment/createawb.html, client/src/js/templates/shipment/dispatch.html, client/src/js/templates/shipment/shipment.html, docs/index.html
**JIRA ticket:** [LIMS-243](https://jira.diamond.ac.uk/browse/LIMS-243)
**Changes:**
- Change every instance of 'airway bill' to 'air waybill'
**To test:**
- Check that the spelling is now correct
=> [LIMS-243]Improvement: Replace 'airway bill' with 'air waybill'

api/assets/emails/dewar-dispatch.html, api/assets/emails/html/dewar-dispatch.html, api/assets/pdf/shipment_label.php, api/src/Page/PDF.php, api/src/Page/Shipment.php, api/src/Shipment/Courier/DHL.php, client/src/js/models/shipment.js, client/src/js/modules/shipment/controller.js, client/src/js/modules/shipment/models/dispatch.js, client/src/js/modules/shipment/routes.js, client/src/js/modules/shipment/views/createawb.js, client/src/js/modules/shipment/views/dewars.js, client/src/js/modules/shipment/views/dispatch.js, client/src/js/modules/shipment/views/shipment.js, client/src/js/modules/shipment/views/shipmentadd.js, client/src/js/templates/contact/contactadd.html, client/src/js/templates/contact/contactview.html, client/src/js/templates/shipment/createawb.html, client/src/js/templates/shipment/dispatch.html, client/src/js/templates/shipment/shipment.html, client/src/js/templates/shipment/shipmentadd.html, client/src/js/templates/shipment/transfer.html, docs/index.html
Merge in 2022 Q4 chipping changes
=> 2022 Q4 shipping changes

client/src/js/modules/shipment/models/dispatch.js, client/src/js/modules/shipment/views/dispatch.js, client/src/js/templates/shipment/dispatch.html
JIRA ticket: [LIMS-256](https://jira.diamond.ac.uk/browse/LIMS-256)
Changes:
Allow for the facility courier terms to be accepted on the dewar dispatch page
Hide the courier details inputs when terms have been accepted
To test:
Check that dispatch can be requested using the facility courier once terms have been accepted
Check that dispatch can be requested using another account provided enough information is given
=> [LIMS-256]Feature: Add shipping terms to dispatch page

client/src/js/modules/shipment/views/containerplate.js
JIRA ticket: [LIMS-112](https://jira.diamond.ac.uk/browse/LIMS-112)
Changes:
Beforehand, screen components would not update when a new well is selected. This is fixed by this pull request, which restores the update functionality.
=> [LIMS-112] Fix: Fixes screen components on well update

api/src/Page/Shipment.php
JIRA ticket: [LIMS-324](https://jira.diamond.ac.uk/browse/LIMS-324)
Changes:
- Make `ENCLOSEDHARDDRIVE`, `ENCLOSEDTOOLS` ,  `DYNAMIC`, `LASTMINUTBEAMTIME`, `SCHEDULINGRESTRICTIONS`, `MICROFOCUSBEAM` optional parameters for shipment creation in back-end, giving them default values of null
To test:
- Check that shipments can be created with and without each of these parameters via direct POST requests to the API
=> [LIMS-324]Fix: Fix Icebear integration

client/src/js/views/log.js
Details in the ticket comments: https://jira.diamond.ac.uk/browse/LIMS-105
=> Set height and width of log view window to same as that that of iframe content

client/src/js/app/components/herotitle.vue, client/src/js/app/components/navbar.vue, client/src/js/app/store/modules/store.auth.js, client/src/js/app/views/login.vue, client/src/js/templates/calendar/current.html, client/src/js/templates/samples/proteinlist.html, client/src/js/templates/shipment/containerregistry.html
[#Update SynchWeb UI to accomodate running Selenium Test](https://jira.diamond.ac.uk/browse/LIMS-88)
=> [LIMS-88]Chore: Add custom attribute `data-testid` to html element to allow test pass

client/src/js/modules/visits/views/visit_list.vue
JIRA ticket: [LIMS-212](https://jira.diamond.ac.uk/browse/LIMS-212)
Changes:
Fix so that visit list clicks through to DC page and that patch request is fixed. 
Test:
Check ISPYB registers change to comments.
Check user journey is as aspected.
=> [LIMS-212] Fix: Add click through to DC page and fix patch request

client/src/js/modules/visits/views/visit_list.vue
JIRA ticket: [LIMS-212](https://jira.diamond.ac.uk/browse/LIMS-212)
Changes:
Fix so that visit list clicks through to DC page and that patch request is fixed. 
Test:
Check ISPYB registers change to comments.
Check user journey is as aspected.
=> [LIMS-212] Fix: Visit List clicks to DC page and patch request is fixed

client/src/js/models/sample.js
Ticket: [LIMS-442](https://jira.diamond.ac.uk/browse/LIMS-442)
Display when Screening Method = None on UDC page of container view eg https://ispyb.diamond.ac.uk/containers/cid/251099
=> LIMS-442: Display ScreeningMethod=None on container view

client/src/js/templates/dc/dc_autoproc.html
Reverts DiamondLightSource/SynchWeb#459
=> Revert "[LIMS-377] Patch: conditional logic changed for I/SigI == 2  "

api/src/Page/DC.php, client/src/js/views/filter.js
Ticket: [LIMS-84](https://jira.diamond.ac.uk/browse/LIMS-84)
Add a phasing filter next to the auto integrated filter at the top of the data collections page for a visit.
=> LIMS-84: Add phasing filter to top of data collections view

client/src/js/modules/shipment/views/containerplate.js
Ticket: [LIMS-151](https://jira.diamond.ac.uk/browse/LIMS-151)
* Set "crystal" (if exists) as the default for CHIMP scores on a plate, rather than the order they come from the db
=> LIMS-151: Change the sort order for CHIMP scores

api/composer.json
https://jira.diamond.ac.uk/browse/LIMS-426
Add php version so composer can be run in different version of php
=> Add php verion for build system

client/src/js/modules/shipment/views/dispatch.js
JIRA ticket: [LIMS-558](https://jira.diamond.ac.uk/browse/LIMS-558)
Changes:
- Populate the country dropdown on the Dewar dispatch page with the country from the selected lab conatct.
To test:
- Check that the country dropdown is set correctly for lab contacts with countries that aren't the United Kingdom.
=> [LIMS-558]Improvement: Set dispatch country as the lab contact country

api/src/Page/Shipment.php
Changes:
- fix if statement in `_dispatch_dewar` such that it's scope is now correct. Note that without this Dewars cannot be dispatched.
To test:
- Check that a Dewar dispatch request can now be successfully submitted.
=> Fix scope from mis-merge

client/src/js/modules/visits/views/visit_list.vue
JIRA Ticket: [[LIMS-514](https://jira.diamond.ac.uk/browse/LIMS-514)]
Changes: Added condition where if the proposal is industry then the message for archival suggests deletion of data rather than archival of data. 
To test:
Check user journey is as expected.
=> [LIMS-514] Fix: Change archive message on visit page

client/src/js/modules/visits/views/visit_list.vue
merged into wrong branch: https://github.com/DiamondLightSource/SynchWeb/pull/503
=> Fix/lims 514/change archive message visit page

api/src/Page/Exp.php
Merge bug fix into pre-release branch
=> Bad merge left and else rows in (#530)

api/assets/pdf/visit_report.php
Ticket: [LIMS-640](https://jira.diamond.ac.uk/browse/LIMS-640)
* Visit reports dont work under PHP7 strict error reporting
* FULLNAME is not a field in the database, replace with TITLE GIVENNAME FAMILYNAME
=> LIMS-640: Fix visit report PDF

api/src/Page/Shipment.php
https://jira.diamond.ac.uk/browse/LIMS-730
=> Bug/lims 730/dewar overview for users without all dewar permissions

client/src/js/models/sample.js, client/src/js/modules/types/mx/samples/tabbed-columns-view.vue
Merged after release candidate made but needed
=> Prerelease

api/src/Controllers/UserController.php, api/src/Model/Services/UserData.php, api/tests/Controllers/UserControllerTest.php, api/tests/Model/Services/UserDataSingleInvocationTest.php, client/src/js/modules/shipment/views/container.js, client/src/js/modules/shipment/views/containeradd.js, client/src/js/modules/shipment/views/containerplate.js, client/src/js/modules/types/mx/shipment/views/container-mixin.js
pid is not used anymore other than for determining access control if it is provided in users/ endpoint. Follow up ticket is https://jira.diamond.ac.uk/browse/LIMS-742
=> Replace or statment with and statement for pid

api/src/Page/Contact.php, client/src/js/modules/contact/views/addcontact.js, client/src/js/modules/shipment/views/migrate.js
Ticket: [LIMS-611](https://jira.diamond.ac.uk/browse/LIMS-611)
* Check whether card name already exists for current (add) or destination (migrate) proposal
* Give suitable error message from backend if so
* Display error message in popup
=> LIMS-611: Improve error message on lab contact add or migrate

api/src/Page/Processing.php
**Jira ticket**
[Group downstream processing results by autoProcProgramId](https://jira.diamond.ac.uk/browse/SCI-10151)
=> [LIMS-118]Improvement: group downstream processing results using autoProcProgramId

client/src/js/app/store/modules/store.auth.js
Ticket: [LIMS-795](https://jira.diamond.ac.uk/browse/LIMS-795)
- `getUser` request is not made immediately after getting OIDC token
=> LIMS-795: Fix proposal view on first OIDC login

client/src/js/app/components/base-input-select.vue, client/src/js/app/components/base-input-text.vue, client/src/js/app/components/combo-box.vue, client/src/js/modules/shipment/views/shipment.js, client/src/js/modules/shipment/views/shipments.js, client/src/js/modules/types/mx/samples/sample-table-row.vue, client/src/js/modules/types/mx/samples/tabbed-columns-view.vue, client/src/js/modules/types/mx/shipment/views/mx-container-add.vue, client/src/js/templates/samples/sample.html, client/src/js/templates/shipment/shipmentadd.html, client/src/js/views/filter.js
Ticket: [LIMS-653](https://jira.diamond.ac.uk/browse/LIMS-653)
For use with https://github.com/DiamondLightSource/SynchWeb-Selenium/pull/10
=> LIMS-653: Add data-testid's to improve Selenium use

client/src/js/modules/admin/views/proposalview.js, client/src/js/modules/proposal/routes.js
Ticket: [LIMS-735](https://jira.diamond.ac.uk/browse/LIMS-735)
- Remove unused declarations that mention empty model files
- Remove said empty model files
=> LIMS-735: Remove empty files from SynchWeb

client/package-lock.json, client/package.json
Update underscore so it works on node 18
=> update underscore so it will work on node18

client/package-lock.json, client/package.json
SynchWeb failed when filtering to Screening data sets on teh data collections page
=> Revert to satble version

client/src/css/partials/_content.scss, client/src/css/partials/_imaging.scss, client/src/js/modules/imaging/views/screencompadmin.js
Ticket: [LIMS-155](https://jira.diamond.ac.uk/browse/LIMS-155)
- Plates have a standard 12x8 layout, use CSS to maintain that
- Use A1-H12 names rather than 1-96 as that is what is printed on the plates
=> LIMS-155: Show plate as 12x8

api/composer.json, api/config_sample.php, api/src/Page.php, api/src/Page/Vstat.php
Ticket: [LIMS-779](https://jira.diamond.ac.uk/browse/LIMS-779)
* Move archiver URL to config
* Update URL parameter format
* Update function dealing with returned values
* Cope if visit ended with no beam
=> LIMS-779: Move archive url to config

api/src/Page/DC.php, client/src/js/modules/dc/datacollections.js, client/src/js/modules/dc/dclist.js, client/src/js/modules/types/xpdf/dc/datacollections.js, client/src/js/templates/dc/dc.html, client/src/js/templates/types/xpdf/dc/dclist.html
Ticket: [LIMS-774](https://jira.diamond.ac.uk/browse/LIMS-774)
=> LIMS-774 - Display single crystal vs multi crystal data in appropriate templates

api/config_sample.php, api/index.php, api/src/Authentication/AuthenticationTypeFactory.php, api/src/Authentication/Type/Combined.php, api/src/Authentication/Type/OIDC.php, client/src/js/app/components/header.vue, client/src/js/app/store/modules/store.auth.js, client/src/js/app/store/store.js, client/src/js/app/views/logout.vue
https://jira.diamond.ac.uk/browse/LIMS-856
requires https://github.com/DiamondLightSource/SynchWeb/pull/607
=> Fix/lims 856/provide api login

api/config_sample.php, api/index.php, api/src/Authentication/Type/OIDC.php, client/src/js/app/components/header.vue, client/src/js/app/store/modules/store.auth.js, client/src/js/app/store/store.js, client/src/js/app/views/logout.vue
Ticket: [LIMS-844](https://jira.diamond.ac.uk/browse/LIMS-844)
- Fixes bug caused by services that use CAS (as in CAS, the protocol)
- Allows multiple authentication mechanisms to coexist side by side in the codebase
- Sends client details through Authorization header in OIDC token endpoint.
=> LIMS-844: SSO-specific URL

api/src/Authentication/Type/OIDC.php
https://jira.diamond.ac.uk/browse/LIMS-876
=> Fix/lims 876/check unset variables

api/src/Page/Sample.php, client/src/js/models/sample.js, client/src/js/modules/samples/views/view.js, client/src/js/templates/samples/sample.html
Ticket: [LIMS-285](https://jira.diamond.ac.uk/browse/LIMS-285)
- Add fields on generic sample page to show size/shape/colour
- Make them editable
- Use mm as units for consistency with xpdf
=> LIMS-285: Make sample dimensions, color and shape visible and editable

api/src/Page/Shipment.php
JIRA ticket: [LIMS-932](https://jira.diamond.ac.uk/browse/lims-932)
Changes:
- Include `proposal` in shipping service requests when creating a shipment
To test:
- Check that shipping service requests continue to work as expected
=> LIMS-932: Send proposal when creating shipments in shipping service

.github/pull_request_template.md
**JIRA ticket**: [LIMS-940](https://jira.diamond.ac.uk/browse/lims-940)
**Description**:
Adds a basic template for pull requests
**Changes**:
- Add PR template
**To test**:
- N/A
=> LIMS-940: Add PR template

client/src/js/modules/imaging/views/queuecontainer.js, client/src/js/templates/imaging/queuecontainer.html
Ticket: [LIMS-222](https://jira.diamond.ac.uk/browse/LIMS-222)
- Add "Apply to All" button next to "Apply to Selected" button for presets
- Link to onPresetAll function, which is the same as onPreset but for all samples
Testing instructions:
- Go to a container that is a plate, eg /containers/cid/263100
- Click 'Prepare For Data Collection'
- Add some samples to the queue
- Select a preset and click 'Add to All'
=> LIMS-222: Apply experimental parameters to all samples

api/src/Database/Type/MySQL.php, api/src/Page/DC.php, client/src/js/modules/dc/views/grid.js, client/src/js/modules/dc/views/gridplot.js, client/src/js/templates/dc/grid.html
Ticket: [LIMS-395](https://jira.diamond.ac.uk/browse/LIMS-395)
- Display a warning if xray centring status:
- Successful but no result (ie no diffraction) (eg /dc/visit/cm33866-3/dcg/9683460)
- Pending (eg /dc/visit/cm33866-3/dcg/9716937 on dev db at time of writing)
- Failed (eg /dc/visit/cm33866-3/dcg/9716325 on dev db at time of writing)
=> LIMS-395: Display warning if no spots or incomplete PIA

client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
Ticket: [LIMS-862](https://jira.diamond.ac.uk/browse/LIMS-862)
* After creating a container, clear the registered container field ready for next container
* If previous container was queued for UDC, assume next one will be, and set default values for centring method, experiment kind and screening method
=> LIMS-862: Reset registered container after creating container

api/index.php, api/src/Options.php
Ticket: [LIMS-743](https://jira.diamond.ac.uk/browse/LIMS-743)
* Get message of the day from the AdminVar table, if the key "motd" is set
* Fall back to value from config file if "motd" is not set
=> LIMS-743: Get MOTD from database

client/src/js/templates/shipment/containerplateimage.html
**JIRA ticket**: [LIMS-95](https://jira.diamond.ac.uk/browse/LIMS-95)
**Summary**:
Tidy the labels for the radio box that was added in https://github.com/DiamondLightSource/SynchWeb/pull/621
**Changes**:
- Change style of label, change text to 'Display'
**To test**:
- Cosmetic changes only
=> LIMS-95: Change label to match others

api/config_sample.php, api/index.php, api/src/Authentication/Type/OIDC.php, api/src/Options.php, api/src/Page.php, api/src/Page/Contact.php, api/src/Page/Shipment.php, api/src/Shipment/ShippingService.php, client/src/js/modules/fault/routes.js, client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue
**Summary**:
**Changes**:
**To test**:
=> Pre release/2023 r4.3

api/src/Authentication/Type/OIDC.php, api/src/Page/Download.php, api/src/Page/Processing.php
**JIRA ticket**: none
**Summary**:
Make prerelease pass Psalm in build
**Changes**:
- Move globals in OIDC and use lazy loaf pattern for config
- Remove static ref in Download
- Conform to o php7 in processing
**To test**:
- Log in 
- Download something from data collection (archive)
- View something from a data collection
- Look at an image in downstream processing
=> On Build: Satisfy Psalm Config

api/src/Authentication/Type/OIDC.php, api/src/Page/Download.php, api/src/Page/Processing.php
* Move globals in OIDC and tidy, remove static ref in Download, conform to php7 in processing
* implement strpos properly
---------
**Summary**:
**Changes**:
**To test**:
=> On Build: Satisfy Psalm Config (#689)

api/src/Database/Type/MySQL.php, api/src/Page/Sample.php, api/src/Page/Shipment.php, client/src/js/app/layouts/main.vue, client/src/js/app/layouts/maintenance.vue, client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue
**Summary**:
**Changes**:
**To test**:
=> Merge 2024-R1.1 into master

api/src/Page/DC.php
Looks good to me
**Summary**:
**Changes**:
**To test**:
=> Fix slow data collection queries (#726)

api/assets/emails/html/dewar-transfer.html, api/assets/emails/html/storage-rack.html, api/docs/dist/spec.json, client/src/js/modules/dc/views/gridplot.js, client/src/js/modules/imaging/views/queuecontainer.js, client/src/js/templates/imaging/queuecontainer.html, client/src/js/templates/shipment/transfer.html, client/src/js/templates/types/sm/dc/dc.html
**Summary**:
**Changes**:
**To test**:
=> Pre-release/2024-R1.3

api/src/Page/Download.php, api/src/Page/Sample.php, client/src/js/modules/shipment/models/dispatch.js, client/src/js/modules/types/mx/shipment/views/mx-container-add.vue, client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue, client/src/js/utils/validation.js
**Summary**:
**Changes**:
**To test**:
=> Pre release/2024 r2.2

api/src/Page/Download.php, api/src/Page/Sample.php, client/src/js/modules/shipment/models/dispatch.js, client/src/js/modules/types/mx/shipment/views/mx-container-add.vue, client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue, client/src/js/utils/validation.js
* LIMS-1201: Amend name of XPDF capillary crystal to use user acronym (#738)
* LIMS-1256: Remove validation from Local Contact field (#756)
* LIMS-667: Make the Requested Imager a required field if a plate is being created (#733)
* LIMS-1261: Fix the grid scan heat maps on the VMXi container view (#744)
* LIMS-1289: Fix sample and pdb count on protens page (#753)
---------
**Summary**:
**Changes**:
**To test**:
=> Pre release/2024 r2.2 (#764)

client/src/js/app/store/modules/store.menus.js, client/src/js/modules/types/em/menu.js
**Summary**:
**Changes**:
**To test**:
=> Restore EM menu in dropdown (#766)

client/src/js/app/store/modules/store.menus.js, client/src/js/modules/types/em/menu.js
**Summary**:
Add 2.2a changes to 2.3
**Changes**:
**To test**:
=> Add 2.2a changes to 2.3

api/src/Page/Shipment.php
* LIMS-1353: Cannot book multiple dewars in one shipment
=> Merge 2024-R2.4.1 into master

api/src/Page/Sample.php, api/src/Page/Shipment.php, client/src/js/models/shipment.js, client/src/js/modules/shipment/views/shipment.js, client/src/js/modules/shipment/views/shipmentadd.js, client/src/js/modules/types/mx/shipment/views/container-mixin.js, client/src/js/modules/types/mx/shipment/views/mx-container-add.vue, client/src/js/modules/types/mx/shipment/views/mx-container-view.vue, client/src/js/templates/shipment/shipmentadd.html, client/src/js/utils/editable.js
**JIRA ticket**: [LIMS-1099](https://jira.diamond.ac.uk/browse/LIMS-1099)
**Summary**:
We should not allow red/yellow proteins into green shipments, nor allow containers with them to be queued for UDC.
**Changes**:
- Shipments must either be associated with a visit, or tick the UDC or Responsive box (to allow "-")
- If a shipment is created as Red or Yellow:
- hide the UDC and Responsive boxes, so a visit must be chosen
- hide the "Queue for UDC" button
- Only allow proteins in a suitable shipment, eg no red proteins in a green shipment
- Don't allow changing shipment safety level to lower than that of the proteins
- Don't allow changing shipment safety level to yellow/red if any of the containers are queued for UDC
**To test**:
- Go to a proposal with future visits eg cm37235
- Go to the …
=> LIMS-1099: Limit what can be done with red proteins

api/src/Page/Processing.php
**JIRA ticket**: [LIMS-139](https://jira.diamond.ac.uk/browse/LIMS-139)
**Summary**:
The origin of xia2 multiplex jobs are sometimes tricky to work out. As the sample_id or sample_group_id are stored in the ProcessingJobParameter table, we can display the sample or group that triggered each multiplex job.
**Changes**:
- Get the sample group name or sample name corresponding to the processing job parameter
- Append it to the multiplex job name
**To test**:
- Go to a data collection with multiplex jobs eg /dc/visit/nt24686-62/id/5302666
- Check that some of the multiplex jobs have the sample name or a sample group name in brackets after the pipeline name, as shown below
=> LIMS-139: link multiplex results to sample or sample group
