- api/includes/pages/class.download.php
Fixed duplicated .pdb file reference and included .log fine into archive for improved usability.
> Add missing .mtz and include .log file into mtz/pdb download archive

- client/js/models/scanmodel.js
Without the logical not, start:stop:step and array are either both required, or both can be empty. With the logical not, the correct behaviour is achieved: either start:stop:step or array are required.
> Add logical not in scan model validation

- api/config_sample.php
- api/includes/class.auth-ldap.php
Updates the api/includes/class.auth-ldap.php based on testing with openldap servers.
Main change is the ldap_bind call - concatenating the SynchWeb login value with the LDAP search string. 
Also updates api/config_sample.php with example values - showing the search syntax required.
> Fix for LDAP authentication

- api/includes/pages/class.dc.php
there are two spacegroup lines, but only one hand line. The hand line
follows a block that can fail and is therefore a better indicator of
success.
> Update fast_ep success criterion

- client/js/views/status.js
This changes the logic within the status element of the main data collections/activity stream.
It waits until the animation (slideToggle) is complete before making the test to see if the element is visible. This fixes the bug where the camera feeds would be open, even if the webcam view was collapsed.
> Fixed bug with camera feeds not stopping after widget closes

- api/includes/pages/class.proposal.php
If no Container.ownerId has been set, then we need to pick some other person to be the TEAM_LEADER for the Session to be created. This code modifies the SQL so that if no Container.ownerId exists, then we instead select the P.I. of the corresponding proposal. 
To help address internal Jira ticket I03-303.
> Make sure a TEAM_LEADER is being set for the session

- client/package.json
- client/webpack.config.js
Fixes inline date editing which does not work with npm version.
> Revert jquery-editable from npm to local vendor library

- api/src/Page/Download.php
This allows downloads of auto processing attachments < 512MB
> Disable output buffer for downloading attachments

- api/src/Authentication/Type/CAS.php
Explicitly set the cas certificate when making curl requests.
Should be more flexible for other sites using different CAS providers.
> Consistent use of cas certificate in curl requests

- client/src/js/modules/proposal/controller.js
The Proposals breadcrumb link is broken since it links to `/proposals` when it should be `/proposal` (singular).
> Fix Proposals breadcrumb: s/proposals/proposal/

- client/src/js/views/login.js
UNIX-like OSs allow a dash in the username, so allow a dash in the
username in the SynchWeb Login view.
> Allow dash in username

- .gitignore
- client/src/js/modules/stats/views/beamline.js
- client/src/js/templates/stats/beamline.html
This PR fixes the issue with `beamline runs stats` drop-down selector not being visible on mobile devices
> Fix: Run selector not displaying for mobile devices

- api/src/Page/DC.php
With https://github.com/DiamondLightSource/SynchWeb/pull/103 we removed hardcoded omega axis, however some beamlines are not actually populating rotationaxis so need to set a default
> return a default value if rotationaxis is not set

- client/src/js/modules/shipment/views/shipment.js
bltimestamp is the same for containers in the shipment, guess there is an update trigger @KarlLevik ? Sort by name on shipment page instead
> sci-9352: sort containers by name on shipment page

- api/src/Page/Vstat.php
- client/src/js/modules/blstats/collections/errorlog.js
- client/src/js/modules/stats/views/errorlog.js
- client/src/js/modules/types/gen/stats/views/visit.js
- client/src/js/templates/types/gen/stats/visit.html
This adds a list of datacollection errors and the last line of the associate log to the visit stats view for none mx proposals
> Add datacollection error log stats

- api/src/Page/DC.php
To be coordinated with database (which has already been updated, but dont know if column has been populated)
This allows multiple grid scans to exist in a group => xray centring for example
I think this should suffice:
```
UPDATE GridInfo
INNER JOIN DataCollectionGroup ON DataCollectionGroup.datacollectiongroupid = GridInfo.datacollectiongroupid
INNER JOIN DataCollection ON DataCollection.datacollectiongroupid = DataCollectionGroup.datacollectiongroupid
SET GridInfo.datacollectionid = DataCollection.datacollectionid
WHERE GridInfo.datacollectionid IS NULL;
```
> Gridinfo is now linked to dc and not dcg

- api/src/Page/Stats.php
Fix `Division by zero` and `Undefined index` exception bugs in the Stats > Beamline Stats view (`/statistics/bl`) when there are no data collections.
> Make Stats > Beamline Stats work when no DCs

- api/src/Page/Status.php
When accessing the Beamline Status view, if the GDA log file is empty, an `Undefined offset: 0` exception is thrown from the API.  Fix this so that an empty GDA log file is handled correctly.
> Make Beamline Status view handle empty GDA log

- client/src/js/modules/types/xpdf/shipment/views/containeradd.js
- client/src/js/templates/types/xpdf/shipment/containeradd.html
- client/src/js/templates/types/xpdf/shipment/containerview.html
the XPDF pages incorrectly set the barcode on the model and Container.barcode is a unique column, therefore precluding reusing a barcode. This fixes this by: 
- not setting the barcode on the model when a container is added
- removing the stage name field from the container add page (use the registry name instead)
- removing the barcode field from the container view page
> [I15_1-1203] fix xpdf reuse of containers

- client/src/js/app/store/modules/store.menus.js
- client/src/js/modules/dc/components/dc-wrapper.vue
- client/src/js/modules/types/b24/dc/datacollections.js
- client/src/js/modules/types/b24/menu.js
- client/src/js/modules/types/epsic/dc/datacollections.js
- client/src/js/modules/types/epsic/menu.js
- client/src/js/modules/types/i12/dc/datacollections.js
- client/src/js/modules/types/i12/menu.js
- client/src/js/modules/types/i13/dc/datacollections.js
- client/src/js/modules/types/i13/menu.js
Addition of (trivial xpdf extension) templates for i12, i13 and b24.
Moves the authorisation from the tomo_admin group to the appropriate staff group.
Template shows the scan_params json field and autoprocessing areas of the DC.
> Further beamline templates

- api/composer.json
- api/src/Shipment/Courier/DHL.php
**JIRA ticket:** [LIMS-232](https://jira.diamond.ac.uk/browse/LIMS-232)
**Changes:**
- Update `composer.json` to use a [fork](https://github.com/MattPrit/dhl-api) of the PHP library that makes DHL requests with the updated schema.
- Check if address lines are set before trying to set the elements of the DHL shipping request.
**To test:**
- Test that quote/shipping/pickup/tracking requests can be made successfully.
**Note:** Currently uses a fork on my GitHub account; the aim is to move over to https://github.com/mtcmedia/dhl-api once Synchweb has been updated to PHP7
> [LIMS-232]Improvement: Update DHL XML API

- api/src/Page/Shipment.php
- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/templates/shipment/dispatch.html
**JIRA ticket:** [LIMS-130](https://jira.diamond.ac.uk/browse/LIMS-130)
**Changes:**
- Make local contact and Dewar location optional fields of the Dewar dispatch form.
- Make the local contact field read-only
**To test:**
- Check that the form can be submitted both with and without the local contact and dewar location fields populated
- Check that the dispatch email(s) are sent correctly in all cases
> [LIMS-130]Fix: optional local contact for dispatch

- api/src/Page/Shipment.php
- client/src/js/models/shipment.js
- client/src/js/modules/shipment/controller.js
- client/src/js/modules/shipment/routes.js
- client/src/js/modules/shipment/views/shipment.js
- client/src/js/modules/shipment/views/shipmentadd.js
- client/src/js/templates/shipment/shipment.html
- client/src/js/templates/shipment/shipmentadd.html
**JIRA ticket:** [LIMS-80](https://jira.diamond.ac.uk/browse/LIMS-80)
**Changes:**
- Remove use of shipments_comments.json - remove questions from within the comments field, replacing them with separate fields
- Add extra fields to the create shipment form, for all dynamically-scheduled remote visits: Session length, Energy/wavelength, Microfocus beam, Scheduling restrictions, Last minute beam time, Dewar grouping
- Add an extra field for industrial dynamically-scheduled remote visits: Remote or mail in?
- Add extra fields for all shipments: Tools enclosed?, Hard drive enclosed?
- Add extra rows to the shipment page corresponding to the new fields
**To test:**
- Check that the correct fields appear depending on the circumstances (dynamic scheduling, industrial visit, etc.)
- Check that …
> [LIMS-80]Feature: Tidy responsive scheduling questions

- client/src/js/modules/shipment/views/dewars.js
**JIRA ticket:** [LIMS-138](https://jira.diamond.ac.uk/browse/LIMS-138)
**Changes:**
- Extend the first experiment dropdown on the shipment page so that it can show more than 5 visits
**To test:**
- Check that the first experiment dropdown can show more than 5 visits for proposals with a large number of visits
> [LIMS-138]Fix: Extend dropdown for first experiment in Shipment page

- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/templates/shipment/dispatch.html
**JIRA ticket:** [LIMS-93](https://jira.diamond.ac.uk/browse/LIMS-93)
**Changes:**
- Change logic of Dewar dispatch form such that: If the facility courier account is used, courier details fields are hidden. If the facility account is not used and courier details have been fully specified, then courier details fields are shown disabled by default, with the option for editing. If the facility account is not used but courier details are not fully specified, then the fields are enabled by default, with no option to disable.
**To test:**
- Check that, for each combination of provided courier account information, the correct fields are visible.
> [LIMS-93]Fix: Change logic of dewar dispatch courier fields

- api/src/Page/Shipment.php
- api/src/Shipment/Courier/DHL.php
**JIRA ticket:** [LIMS-228](https://jira.diamond.ac.uk/browse/LIMS-228)
**Changes:**
- Add the `deliveryAgent_agentCode` from the Shipping table to the DHL XML quote request as the `PaymentAccountNumber` element.
**To test:**
- Check that the quotes received are correct for a given account number
> [LIMS-228]Fix: Add account number to DHL quote request

- api/assets/pdf/shipment_label.php
**JIRA ticket:** [LIMS-230](https://jira.diamond.ac.uk/browse/LIMS-230)
**Changes:**
- Removed 'To:' from the outbound addresses in the shipping label template. This is to allow for more characters to fit on each address line, e.g. to let 'Harwell Science & Innovation Campus' fit without requiring multiple lines.
**To test:**
- Check that shipping labels are rendered correctly and that 'Harwell Science & Innovation Campus' can now fit on a single line.
> [LIMS-230]Improvement: Widen the address on shipping labels

- client/src/js/templates/shipment/shipment.html
**JIRA ticket:** [LIMS-229](https://jira.diamond.ac.uk/browse/LIMS-229)
**Changes:**
- Make the create air waybill button only be present on the shipping page if the shipment's courier is undefined or DHL.
- Change the text on the create air waybillbutton to read 'create DHL airway bill'
**To test:**
- Check that the button only appears under the right circumstances.
> [LIMS-229]Improvement: Hide 'create air waybill' if not applicable

- api/assets/pdf/shipment_label.php
- client/src/js/modules/shipment/views/createawb.js
**JIRA ticket:**
**Changes:**
- Swap positions of 'This way up' and shipment description.
- Update the description to read 'Cryogenic dry shipper. Not restricted, ADR A346, IATA A152.'
- Change validation on package description field on the create air waybill page to allow the new description.
**To test:**
- Check that shipment labels are formatted as expected.
- Check that airway bills can be created using the new description.
**Note:** To update the description on airway bills, `$package_description` will need to be updated in `config.php`.
> [LIMS-231]Improvement: Update and move description on shipping label

- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/templates/shipment/dispatch.html
JIRA ticket: [LIMS-254](https://jira.diamond.ac.uk/browse/LIMS-254)
Changes:
Add default countries of "United Kingdom" and "Other" on the dewar dispatch form
Only overwrite those with full list of countries if such a list exists
To test:
Check the dropdown still populates with full list of countries
Check the dropdown has UK/Other options if countries URL is blocked (firefox -> F11 -> Network tab -> right click on countries -> Block URL
Check the form can be submitted with United Kingdom, Other, Aruba
> [LIMS-254] Fix: Add default country options of UK/Other

- client/src/js/modules/types/mx/shipment/views/mx-container-view.vue
Ticket: [LIMS-329](https://jira.diamond.ac.uk/browse/LIMS-329)
Looks like an error in the merge of Victor's sample groups fixes. This function is not needed here as it is in container-mixin.js
> LIMS-329: Samples not displayed in container

- api/src/Page/Shipment.php
JIRA ticket: [LIMS-324](https://jira.diamond.ac.uk/browse/LIMS-324)
Changes:
- Patch fix for issue introduced in https://github.com/DiamondLightSource/SynchWeb/pull/416. Shipping argument `DYNAMIC` would always be set to `true` when provided. This change fixes this issue.
To test:
- Check that shipments created with `DYNAMIC` set to `true/false` have the correct value added to the database.
> LIMS-324: Fix DYNAMIC arg in backend

- client/src/js/modules/shipment/views/dispatch.js
JIRA ticket: [LIMS-335](https://jira.diamond.ac.uk/browse/LIMS-335)
Changes:
- Set courier as 'DHL' when requesting a Dewar dispatch on the facility's account in the case where the shipping terms haven't been accepted before the dispatch request. This makes it consistent with dispatches where the terms had been accepted earlier.
To test:
- Check that when a dispatch is requested the courier is always set to 'DHL'.
> LIMS-335: Set courier as 'DHL' for facility shipping

- client/src/js/modules/shipment/views/containerplate.js
Beforehand, screen components would not update when a new well is selected. This is fixed by this pull request, which restores the update functionality.
> Fixes screen components on well update

- client/src/js/modules/shipment/views/shipment.js
- client/src/js/modules/shipment/views/shipmentadd.js
JIRA ticket: [LIMS-259](https://jira.diamond.ac.uk/browse/LIMS-259)
Changes:
- Alter logic determining if a given visit is an industrial visit to use app.prop rather than app.proposal
To test:
- Check that shipment pages now load correctly from direct links
> [LIMS-259]Fix: Direct links to shipments fail

- client/src/js/modules/dc/views/reprocess2.js
- client/src/js/templates/dc/reprocess.html
Previously, the space group field was an input field where users needed to enter data manually.
Turning this field into a dropdown guides the users. This is done following the dropdown implementation in Containers Add page.
I am assuming modules/dc/views/reprocess.js doesn't need to updated for this as that one is only being used in `apstatussummary.js` (?)
> Feature: Turn the space group input field into a dropdown in DC

- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/utils/validation.js
**JIRA ticket: [LIMS-255](https://jira.diamond.ac.uk/browse/LIMS-255)**
**Changes:**
- Create new validation type for letters/numbers/spaces/underscores/dots/dashes
- Add help message for new validation type
- Use new validation type on visit local contact
**To test:**
- Check that the form can be submitted with a local contact with only letters and spaces
- Check that the form can be submitted with a local contact with a dot in (eg Dr. Anastasia Shilova, https://ispyb.diamond.ac.uk/dewars/dispatch/57805)
- Check the form cannot be submitted with invalid characters in the local contact field - may not be possible to test
> [LIMS-255] Fix: Allow dots in local contact

- client/src/js/modules/calendar/views/calendar-view.vue
**Jira Tickets: [LIMS-244](https://jira.diamond.ac.uk/browse/LIMS-244) [LIMS-275](https://jira.diamond.ac.uk/browse/LIMS-275)**
**Changes:**
- Fixed bug where beamline status page didn't know the current date
- Fixed bug where the next month button didn't span years (also fixed on general calendar page)
**To test:**
- Check beamline status page (eg https://ispyb.diamond.ac.uk/status/bl/i03) shows visits for current month
- Check beamline status page can navigate months and years
- Check general calendar page (https://ispyb.diamond.ac.uk/cal) shows visits for current month
- Check general calendar page can navigate months and years
> LIMS-244: Beamline status page calendar showed no visits

- client/src/js/modules/types/mx/samples/tabbed-columns-view.vue
**JIRA ticket: [LIMS-225](https://jira.diamond.ac.uk/browse/LIMS-225)**
**Changes:**
- Change regex validation on User Path field to allow hyphens before and after the forward slash
**To test:**
- Check the form can be submitted with hyphens in the User Path
- Check the sample can be edited to add hyphens to the User Path
- Check the Bulk Editor can put hyphens in the User Path
> LIMS-225: Allow hyphens in user path when creating pucks

- api/src/Page/DC.php
**JIRA ticket: [LIMS-158](https://jira.diamond.ac.uk/browse/LIMS-158)**
**Changes:**
- If filter type is 'full collections', append 'and numberOfImages>1' to the SQL query
**To test:**
- Check that single image data collections no longer appear if 'Full collections' is selected
- Check that single image data collections still appear if 'Data collections' or no filter is selected
> LIMS-158: When filtering by 'Full collections', dont show single image data collections

- client/src/js/modules/types/mx/shipment/views/mx-container-view.vue
JIRA ticket: [LIMS-260](https://jira.diamond.ac.uk/browse/LIMS-260)
Changes:
- Make it so that a container cannot be added to the UDC queue from the container view page if the information in the samples table does not meet the criteria for adding to the UDC queue on the container add page.
To test:
- Check that a container cannot be added to the UDC queue if fields are missing in the samples table.
> LIMS-260: Validate samples before adding container to UDC queue

- client/src/js/modules/assign/routes.js
Ticket: [LIMS-75](https://jira.diamond.ac.uk/browse/LIMS-75)
On the page https://ispyb.diamond.ac.uk/assign, we load the next 10 visits for the current proposal, but if a proposal has more than 10 current/future visits, there is no way to get to the 11th onward. This PR ups the pageSize to 9999.
> LIMS-75: Show more than 10 visits on the assign containers page

- client/src/js/modules/dc/views/dc.js
- client/src/js/templates/dc/reprocess.html
- client/src/js/templates/mc/datacollections.html
- client/src/js/templates/types/sm/dc/dc.html
- client/src/js/templates/vue/docs/data/index.html
Ticket: [LIMS-70](https://jira.diamond.ac.uk/browse/LIMS-70)
Remove references to DISTL from a few places:
- Most notably, in the title of the per-image analysis plots
- In the help text on reprocessing and multicrystal reprocessing
- From the links next to a SM data collection
> LIMS-70: Remove references to DISTL

- api/src/Page/Processing.php
- client/src/js/templates/dc/dc_autoproc.html
Ticket: [LIMS-377](https://jira.diamond.ac.uk/browse/LIMS-377)
Display resIOverSigI2 value in SynchWeb in dataset stats view, where it only shows when it is available in ISPYB.
> [LIMS-377] SynchWeb: Display resolution where I/SigI == 2 in frontend

- client/src/js/templates/dc/dc_autoproc.html
Ticket: [LIMS-377](https://jira.diamond.ac.uk/browse/LIMS-377)
Change: Patch where  I/SigI == 2  field logic has changed where value appears correctly in autoproc table. 
To test: check user journey is as expected.
> [LIMS-377] Patch: conditional logic changed for I/SigI == 2  

- client/src/js/modules/shipment/views/dispatch.js
JIRA ticket: [LIMS-321](https://jira.diamond.ac.uk/browse/LIMS-321)
Changes:
- Add the call to `countries.fetch` to the array awaited on rendering the dispatch view.
To test:
- Check that the country drop-down is now always populated with the complete list of countries, rather than just 'United Kingdom/other'
Note: It is not really possible to ensure that the list is *always* populated. When testing this change I added an artificial delay in the back end function `_get_countries`. Before this change the delay would result in the list of countries not being populated; after the change the list would be populated once the request returned.
> [LIMS-321]Fix: 

- api/src/Page/Proposal.php
- client/src/js/modules/visits/views/visit_list.vue
Ticket: [LIMS-212](https://jira.diamond.ac.uk/browse/LIMS-212)
Changes:
Endpoint created in proposal.php where users can add comments to the visits without needing manage visit permissions. 
To test:
Check postman returns expected json
Check ISPYB records change
Check user journey is as expected.
> [LIMS-212] Fix: Add endpoint to post comments without special permissions

- client/src/js/modules/dc/views/dc.js
- client/src/js/templates/dc/reprocess.html
- client/src/js/templates/mc/datacollections.html
- client/src/js/templates/types/sm/dc/dc.html
- client/src/js/templates/vue/docs/data/index.html
Ticket: [LIMS-70](https://jira.diamond.ac.uk/browse/LIMS-70)
Remove references to DISTL from a few places:
Most notably, in the title of the per-image analysis plots
In the help text on reprocessing and multicrystal reprocessing
From the links next to a SM data collection
> [LIMS-70]: Remove references to DISTL

- client/src/js/modules/shipment/views/dispatch.js
JIRA ticket: [LIMS-321](https://jira.diamond.ac.uk/browse/LIMS-321)
Changes:
Add the call to countries.fetch to the array awaited on rendering the dispatch view.
To test:
Check that the country drop-down is now always populated with the complete list of countries, rather than just 'United Kingdom/other'
Note: It is not really possible to ensure that the list is always populated. When testing this change I added an artificial delay in the back end function _get_countries. Before this change the delay would result in the list of countries not being populated; after the change the list would be populated once the request returned.
> [LIMS-321] Fix: Dispatch country list not populated

- api/src/Page/Shipment.php
Ticket: [LIMS-213](https://jira.diamond.ac.uk/browse/LIMS-213)
Trying to create a container of type "Block-4" would fail because of the regex not expecting a hyphen.
> LIMS-213: Update regex to enable creating Block-4 containers

- client/src/js/modules/shipment/components/container-view-wrapper.vue
Ticket: [LIMS-405](https://jira.diamond.ac.uk/browse/LIMS-405)
If an i23-style puck was created using the containerType 'block-4', it was displayed as a plate as it didn't match the list of non-plate container types. Adding 'block-4' to the list means the samples are displayed the same as a puck.
> LIMS-405: Cannot view samples in containers of type 'Block-4'

- client/src/js/templates/dc/dclist.html
Ticket: [LIMS-216](https://jira.diamond.ac.uk/browse/LIMS-216)
Clarify that data from 'archived' industrial visits is deleted, not archived.
> LIMS-216: Fix message for industrial archived visits

- api/src/Page/Shipment.php
Ticket: [LIMS-453](https://jira.diamond.ac.uk/browse/LIMS-453)
Currently when dewars are returned to the Randex we send an email to the lab contact to say the dewar is ready for return or internal transfer. Feedback from users is that the current notifications aren't going to the right people, and that the people creating the samples don't get told once their samples are done. This PR adds all container "owners" to the CC list of the email.
> LIMS-453: Email container owners when a dewar returns to the dewar store

- api/src/Page/Shipment.php
JIRA ticket: [LIMS-475](https://jira.diamond.ac.uk/browse/LIMS-475)
Changes:
- Assign `SCHEDULINGRESTRICTIONS` to the `$scheduling_restrictions` vaiable
To test:
- Check that, when a 'dynamic' shipment is created with scheduling restrictions specified, the scheduling restrictions are persisted to the database.
> [LIMS-475]Fix: Persist SCHEDULINGRESTRICTIONS to database

- api/src/Page/Vstat.php
- client/src/js/templates/stats/details.html
Ticket: [LIMS-412](https://jira.diamond.ac.uk/browse/LIMS-412)
Improve the display of the visit stats page to show explicitly how many data collections, screenings and grid scans have been done on how many samples.
Not sure if there is a better way to do the "newargs" line.
> LIMS-412: Improve visit stats page

- api/src/Page/Proposal.php
Ticket: [LIMS-270](https://jira.diamond.ac.uk/browse/LIMS-270)
If users go to the list of proposals, they get a list of all proposals they have a visit on. If staff go to the list of proposals, they get a list of all proposals for beamlines they are admin on. This fix gives staff an extra OR condition, for proposals on other beamlines.
> LIMS-270: Enable staff to see proposals from other villages

- client/src/js/modules/dc/views/mcaplot.js
Ticket: [LIMS-342](https://jira.diamond.ac.uk/browse/LIMS-342)
If the browser window is resized, the peak labels (eg "Se-K") on an MCA spectrum should move with the peaks themselves.
Also fix typo on "opacity".
> LIMS-342: Move MCA peak labels when window resizes

- api/src/Page/Shipment.php
- client/src/js/modules/shipment/views/shipment.js
- client/src/js/templates/shipment/shipment.html
JIRA ticket: [LIMS-413](https://jira.diamond.ac.uk/browse/LIMS-413)
Changes:
- Allow `DYNAMIC` to be changed via the shipment page - i.e. allow users to change 'responsive remote' after a shipment has been created.
- Change the type of `DYNAMIC` to be a string `'Yes'`/`'No'` rather than a boolean.
- Allow responsive remote options (`REMOTEORMAILIN`, `SESSIONLENGTH`, `ENERGY`, `MICROFOCUSBEAM`, `SCHEDULINGRESTRICTIONS`, `LASTMINUTEBEAMTIME`, `DEWARGROUPING`) to be shown/hidden when the value of `DYNAMIC` is changed on the shipment page.
To test:
- Check that `DYNAMIC` and the remote options can be edited via the shipment page.
> [LIMS-413]Improvement: Make dynamic editable

- client/src/js/modules/dc/views/imageviewer.js
JIRA ticket: [LIMS-129](https://jira.diamond.ac.uk/browse/LIMS-129)
Changes:
- Change the formula used in calculating resolution on moving the cursor in the image viewer when the `DETECTORMODEL` is `"Pilatus 12M"`. This formula should produce more accurate values of resolution for the curved detector.
To test:
- Check that the values of resolution produced are now more accurate for the Pilatus 12M detector, i.e. consistent with the formulae linked in the JIRA ticket.
> [LIMS-129]Fix: Fix Pilatus 12M resolution in image viewer

- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/templates/shipment/dispatch.html
Ticket: [LIMS-467](https://jira.diamond.ac.uk/browse/LIMS-467)
* When requesting dispatch of a dewar, those on the beamline should display a warning
* Fixes typo of 'i024' to 'i24'
* Add data-testid tag for Selenium test
> LIMS-467: Display warning when requesting a dispatch for a dewar on i24

- api/index.php
- api/src/Page/DC.php
- client/src/js/modules/dc/views/gridplot.js
Ticket: [LIMS-464](https://jira.diamond.ac.uk/browse/LIMS-464)
* Requires new variable in config.php, formatted as eg:
$scale_grid_end_date = 20221231;
* This should be added as/when GDA fix the grid scan scaling on affected beamlines (listed as $scale_grid)
* If $scale_grid_end_date is not present, image scaling will continue as before
> LIMS-464: Add config variable to allow ending of grid scan image scaling

- api/src/Page/Proposal.php
Ticket: [LIMS-550](https://jira.diamond.ac.uk/browse/LIMS-550)
- Bug introduced by https://github.com/DiamondLightSource/SynchWeb/pull/441/
- Count of number of visits (for staff) was greatly increased by new join
- Add 'distinct' keyword to correct
> LIMS-550: Fix number of visits count on proposals page

- api/src/Page/Download.php
Ticket: [LIMS-510](https://jira.diamond.ac.uk/browse/LIMS-510)
Add .lsa to the list of extensions to be served as plain text mime type (instead of octet-stream)
Means anode.lsa files (from ANODE) are presented as preformatted logs
> LIMS-510: Display .lsa files from ANODE as preformatted logs

- client/src/js/modules/dc/views/gridplot.js
Ticket: [LIMS-217](https://jira.diamond.ac.uk/browse/LIMS-217)
- Per-image analysis (PIA) for VMXi grid scans is stored as data collection file attachments
- So by default they are listed in attachment id order, which leaves the most useful one (pia_total_intensity) last
- By reversing the ordering, get the most useful one first, which makes it the default one displayed
> LIMS-217: Use pia_total_intensity as default PIA for VMXi grid scans

- api/src/Page/Shipment.php
Changes:
- Use `$facility_email` rather than `$dispatch_email` as `shipper_contact_email` when making shipping service requests. this is because the shipping service expects only a single email address, whereas `$dispatch_email` can be a list of email addresses. Also, the facility email address is a more sensible email to be used as the shipper contact email from DHL's point of view.
To test:
- Check that a dispatch request can be successfully sent to the shipping service when `$dispatch_email` is a list of emails.
> Use facility_email rather than dispatch_email as shipper_contact_email

- api/src/Page.php
Ticket: [LIMS-620](https://jira.diamond.ac.uk/browse/LIMS-620)
* Cannot do regex searches against anything other than strings
* Check input is a string before comparison
* Return false if not a string
> LIMS-620: Check a variable is a string before doing a regex match on it

- api/src/Page/Exp.php
- client/src/js/collections/detectors.js
Ticket: [LIMS-211](https://jira.diamond.ac.uk/browse/LIMS-211)
- Mainly, paginate on the server in pages of 5 to speed up the query
- Other minor changes:
- Use subqueries as this speeds up debugging
- Remove unused dps2 result
- Join DataCollection to BLSession to remove join to DataCollectionGroup
- Use CONCAT_WS to avoid "i03i03" type results
> LIMS-211: Paginate detectors to avoid slow query timeouts

- api/src/Controllers/AuthenticationController.php
- api/src/Page.php
- api/src/Utils.php
- api/tests/Controllers/AuthenticationControllerTest.php
Ticket: [LIMS-608](https://jira.diamond.ac.uk/browse/LIMS-608)
* A few specialist systems (eg dewar-logistics) authenticate via IP address, so user is null
* PHP7 is throwing errors when asking for permissions on null users
> LIMS-608: Check a user is not null before checking if an admin

- api/src/Page/DC.php
- client/src/js/modules/dc/views/gridplot.js
Ticket: [LIMS-572](https://jira.diamond.ac.uk/browse/LIMS-572)
- Need to gradually switch from using pixelsPerMicron to micronsPerPixel for grid scan snapshots
- This PR means we can use either, but will prefer pixelsPerMicron
- A later PR will remove the micronsPerPixel possibility once that column has been emptied
> LIMS-572: Use micronsPerPixel preferably over pixelsPerMicron for grid scan snapshots

- api/src/Model/Services/UserData.php
Ticket: [LIMS-596](https://jira.diamond.ac.uk/browse/LIMS-596)
* Calls to /api/users take ~15s due to doing 2 slow queries with `SELECT a FROM b WHERE c OR d` structure
* Much faster to use `SELECT a FROM b WHERE c UNION SELECT a FROM b WHERE d` structure
* The getUsers function has a lot of possible uses eg projects, sessions, but most common is just a list of persons on a proposal, so split those off into faster function
> LIMS-596: Speed up most common call to getUsers by using UNION instead of OR

- api/config_sample.php
- api/src/Page.php
- api/src/Page/Image.php
This change uses the new [dials-rest server](https://github.com/dials/dials-rest) to generate bitmaps rather than the legacy [flask-dataviewer](https://github.com/DiamondLightSource/flask-dataviewer).
Requires the variables `$dials_rest_url` and `$dials_rest_jwt` to be defined in `config.php`.
> Generate image bitmaps via dials-rest server

- client/src/js/modules/types/mx/samples/sample-table-mixin.js
- client/src/js/modules/types/mx/samples/sample-table-row.vue
Ticket: [LIMS-634](https://jira.diamond.ac.uk/browse/LIMS-634)
* Protein acronym and Sample name fields are not editable when a sample is in a container that is processing or if data has been collected on a sample
* The input validation is still looking at the hidden editable (but empty) fields, so the validation fails
* Set the validation rules to only apply to these fields if these fields are editable
* There may be a better way to do this (https://vee-validate.logaretm.com/v2/guide/conditional-and-looping-inputs.html) but I was unable to get it to work
> LIMS-634: Dont fail sample validation on fields that aren't editable

- api/src/Page/Shipment.php
Ticket: [LIMS-639](https://jira.diamond.ac.uk/browse/LIMS-639)
* Accidental use of setInCache rather than getFromCache
* Introduced in https://github.com/DiamondLightSource/SynchWeb/commit/ab9c8d5ce4cd3453070fa67174aa32c4108873ef#
> LIMS-639: Use getFromCache not setInCache

- client/src/js/models/sample.js
Ticket: [LIMS-677](https://jira.diamond.ac.uk/browse/LIMS-677)
* When a container is created by CSV upload, the DiffractionPlan.strategyOption field is often left blank/null
* Synchweb expects something in the Screening Method column to enable editing or queueing
* Show that column as 'None' when strategyOption is blank/null.
> LIMS-677: Show screening method as none when strategyOption is null

- client/src/js/models/shipment.js
Ticket: [LIMS-725](https://jira.diamond.ac.uk/browse/LIMS-725)
* Fix for bug stopping AWB's from being booked
* Happened if multi-axis question was not answered, usually from CSV upload
* Delete from this model, mirroring eg LASTMINUTEBEAMTIME
> LIMS-725: Fix bug stopping AWB's being booked

- api/assets/emails/html/dewar-dispatch.html
- api/src/Page/Shipment.php
JIRA ticket: [LIMS-733](https://jira.diamond.ac.uk/browse/lims-733)
Changes:
- Change logic in Dewar dispatch email template such that courier details are only hidden if facility terms have not been accepted. 
To test:
- Check that courier details are present in the dispatch email if facility terms have not been accepted
- Check that courier details are not present in the dispatch email if facility terms have been accepted.
> [LIMS-733]Fix: Include courier details in dispatch email

- api/assets/emails/html/dewar-dispatch.html
- api/src/Page/Shipment.php
- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/templates/shipment/dispatch.html
JIRA tickets: [LIMS-682](https://jira.diamond.ac.uk/browse/lims-682), [LIMS-688](https://jira.diamond.ac.uk/browse/lims-688)
Changes:
- Add extra args for `CITY` and `POSTCODE` in `Shipment.php`, use these for Dewar dispatch
- Add extra lines for city and postcode in Dewar dispatch email template (rather than append them to `ADDRESS`)
- Add extra fields in dispatch form for city and post code
- Add front-end validation for city and post code: city is always required, post code is required if country is 'United Kingdom'
- Strip whitespace from beginning and end of post code on blur event.
- Strip repeated new lines and trailing commas from address on blur event.
To test:
- Check that a Dewar dispatch can be requested using the new city and post code fields.
- Check that shipment creation …
> LIMS[682,688]Improvement: Seperate dispatch address fields, strip whitespace

- api/src/Page/Vstat.php
- client/src/js/modules/blstats/views/histogram.js
Ticket: [LIMS-649](https://jira.diamond.ac.uk/browse/LIMS-649)
* I23 use bigger beam sizes than other MX beamlines
* Use larger max value for x axis on beam size x/y histograms when beamline is i23, or comparing all beamlines
> LIMS-649: Increase max beam size for i23 in run stats page

- client/src/js/modules/types/mx/shipment/views/container-mixin.js
Ticket: [LIMS-98](https://jira.diamond.ac.uk/browse/LIMS-98)
- Use the getList function rather than the list object
- getList merges in commissioning if a staff member is logged in (see client/src/js/utils/experimentkinds.js)
> LIMS-98: Show Commissioning experiment type for staff

- client/src/js/modules/types/mx/samples/tabbed-columns-view.vue
Ticket: [LIMS-567](https://jira.diamond.ac.uk/browse/LIMS-567)
* Allow up to 6 decimal places on the unit cell fields for an MX puck
* Same for required resolution and minimal resolution fields
> LIMS-567: Allow up to 6 decimal places for unit cell and resolution fields

- api/config_sample.php
- api/src/Page/Shipment.php
Ticket: [LIMS-397](https://jira.diamond.ac.uk/browse/LIMS-397)
Currently users get emailed about their dewar if it moves:
* from i19 to the mx dewar store
* from one beamline to another beamline (or even to the same beamline)
Users should only be emailed about their dewar if it moves:
* from an mx beamline to the dewar store
* from any beamline to a '*-storage' location
> LIMS-397: Dont email if dewar moves from i19 to dewar store

- client/src/js/templates/dc/dc.html
- client/src/js/templates/dc/grid.html
- client/src/js/templates/types/gen/dc/dc.html
- client/src/js/templates/types/pow/dc/dc.html
- client/src/js/templates/types/saxs/dc/dc.html
- client/src/js/templates/types/sm/dc/dc.html
- client/src/js/templates/types/tomo/dc/dc.html
- client/src/js/templates/types/xpdf/dc/dc.html
Ticket: [LIMS-685](https://jira.diamond.ac.uk/browse/LIMS-685)
Remove the "title" tag from various locations of data collection comment. The onlo ones that seem to be editable are for Edge scans and MCA scans, so have left those unchanged.
> LIMS-685: Hover text wrongly suggests data collection comments are editable

- client/src/js/modules/dc/router.js
- client/src/js/modules/dc/routes.js
The path for DC page was made general so that it could accept arguments in any order but having done this it now takes the path from other routes. Move it doen the routing table so it matches last instead of first.
> Make general dc path less important

- api/src/Page/Sample.php
Ticket: [LIMS-858](https://jira.diamond.ac.uk/browse/LIMS-858)
* Sample changer view has become very slow for XChem proposals, as all dewars remain as 'processing' forever
* But the Container.sampleChangerLocation is set to blank when pucks are unloaded
* Exclude blank strings as well as null values
> LIMS-858: Ignore containers with blank samplechangerlocation

- api/src/Database/Type/MySQL.php
- api/src/Page/DC.php
- api/src/Page/Processing.php
Ticket: [LIMS-614](https://jira.diamond.ac.uk/browse/LIMS-614)
* Use XrayCentring.status instead of deprecated XrayCentringResult.status
* Remove unused endpoint
> LIMS-614: Use new XrayCentring/XrayCentringResults tables

- api/src/Page/Shipment.php
- client/src/js/modules/shipment/views/regdewar.js
Ticket: [LIMS-871](https://jira.diamond.ac.uk/browse/LIMS-871)
* Staff see wrong number of uses of each dewar on the Registered Dewars page, they see (actual number of uses) * (number of proposals the dewar belongs to)
* Staff also get redirected to the max(proposal) when clicking on a registered dewar, and then only see the shipments for that dewar on that proposal
Testing:
1.  Log in as a staff member, go to proposal mx29907.
2. Go to Registered Dewars page
3. Search for DLS-MX-0873, it should show "# Uses" as around 19 (not 57)
4. Click on DLS-MX-0873, proposal should stay as mx29907 (not switch to mx30951)
5. The shipments section should show all 19 uses of this dewar, even those that belong to other proposals
6. Repeat as a user from mx29907, the only difference should be in step 5, …
> LIMS-871: Fix wrong number of dewar uses for staff

- client/src/js/app/store/modules/store.menus.js
- client/src/js/modules/dc/components/dc-wrapper.vue
Ticket: [LIMS-787](https://jira.diamond.ac.uk/browse/LIMS-787)
P99 is used for lots of testing, it would be really useful to be able to see the autoprocessing results in synchweb and its just a 2 line change to the code.
> Let P beamlines show autoprocessing

- api/src/Downstream/Type/Dimple.php
Ticket: [LIMS-899](https://jira.diamond.ac.uk/browse/LIMS-899)
* The code tries to extract the mime type of an image blob from the file extension
* If filepath (or view1/2/3) is null in MXMRRunBlob, that fails with Undefined Variable
Testing:
* Go to a data collection with downstream processing eg https://ispyb.diamond.ac.uk/dc/visit/cm33903-3/id/11034210
* Click on downstream processing bar to expand
* See failed requests to eg https://ispyb.diamond.ac.uk/api/processing/downstream/images/96310113?prop=cm33903
> LIMS-899: Null path to blobs causes errors

- api/config_sample.php
- api/index.php
- api/src/Database/DatabaseConnectionFactory.php
- api/src/Database/DatabaseFactory.php
- api/src/Database/Type/PureMySQL.php
- api/src/Page/Summary.php
- api/src/TemplateParser.php
- client/package-lock.json
- client/src/css/main.scss
- client/src/css/partials/_summary.scss
- client/src/js/app/components/combo-box.vue
- client/src/js/app/components/expandable-sidebar.vue
- client/src/js/app/components/navbar.vue
- client/src/js/app/layouts/main.vue
- client/src/js/app/router/router.js
- client/src/js/app/store/store.js
- client/src/js/modules/summary/collections/summaryresults.js
- client/src/js/modules/summary/models/summaryresult.js
- client/src/js/modules/summary/routes.js
- client/src/js/modules/summary/utils/utils.js
- client/src/js/modules/summary/views/summary.vue
- client/src/js/modules/types/gen/menu.js
* updating .gitignore
* adding frontend files and building backend
* adding front end files and router files
* create sidebar, filter options added, routes added
* add routing to page,search bar and column selector
* adding pagination continutation
* adding csv, all columns, rest of filters
* added descending and ascending
* sidebar dropdown&changed data structure&hide row
* cleaning up fixing jump bug
* refactored backend mapped data
* added expanding row
* refactored favourites
* refactored orderby filter
* cleaned up code, added comments
* added all params to watcher
* added summary db connection
* add routes to summary
* add backend changes summarypage
* changes to expandable sidebar, cleaning up fronte
* clean up, add functions to get data
* front end changes, group concat backend
* …
> LIMS-116: Summary page revamp (#606)

- client/src/js/modules/types/mx/samples/tabbed-columns-view.vue
Ticket: [LIMS-892](https://jira.diamond.ac.uk/browse/LIMS-892)
https://github.com/DiamondLightSource/SynchWeb/pull/558 (LIMS-677) introduced a bug where users could leave screening method and required resolution both blank and then queue for UDC. Required resolution should be a required field if queueing for UDC, and even if screening method is blank. (The extra comma in the rules line matches when screening method is blank).
> LIMS-892: Dont allow UDC samples with no screening method and no reqd resolution

- api/config_sample.php
- api/src/Database/DatabaseFactory.php
- api/src/Page/Shipment.php
- api/src/Shipment/ShippingService.php
- api/tests/Database/DatabaseFactoryTest.php
- client/src/js/modules/shipment/views/createawb.js
- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/templates/contact/contactview.html
- client/src/js/templates/shipment/createawb.html
Requires #618 
JIRA ticket: [LIMS-832](https://jira.diamond.ac.uk/browse/lims-832)
Changes:
- Add config parameter `$use_shipping_service_incoming_shipments` to toggle using the shipping service for incoming shipments
- Make requests to the shipping service for booking incoming shipments
- Fix problem logging `$shipment_data` on shipping service dispatch error
- Format address and post code when first loading the dispatch form
To test:
- Check that, with  `$use_shipping_service_incoming_shipments=true;`, shipments are created/updated in the shipping service when booking an incoming shipment
- Check that SynchWeb behaviour is unchanged when booking an incoming shipment
> [LIMS-832]Feature: Use shipping service for incoming shipments

- api/assets/emails/dewar-transfer.html
- api/assets/emails/html/dewar-transfer.html
- client/src/js/modules/shipment/models/transfer.js
- client/src/js/modules/shipment/views/transfer.js
- client/src/js/templates/shipment/transfer.html
**JIRA ticket**: [LIMS-903](https://jira.diamond.ac.uk/browse/LIMS-903)
**Summary**:
Update the email sent to LCs when an internal dewar transfer is requested.
**Changes**:
- Remove instructions to physically move dewar, this is not required
- Remove instructions to EHCs as they are not involved in the process any more
- Move row with new LC details
- Remove references to Diamond-specifically
**To test**:
- Test email still sent with all dewar details
> LIMS-903: Update email on dewar transfer

- api/src/Page/Proposal.php
- client/src/js/modules/shipment/views/dispatch.js
Ticket: [LIMS-705](https://jira.diamond.ac.uk/browse/LIMS-705)
* New sessions with visit_number = NULL causes confusion and potential errors in dispatch request form
* So hide sessions with visit_number = NULL
> LIMS-705: Ignore null visits

- api/src/Page/Sample.php
- client/src/js/modules/imaging/views/queuecontainer.js
- client/src/js/templates/imaging/queuecontainer.html
Ticket: [LIMS-219](https://jira.diamond.ac.uk/browse/LIMS-219)
- Add "Add All To Queue" button to GUI
- Copy queueAllSamples function to queuePageSamples, make queueAllSamples use post request
- Send in chunks of 500 as >1000 gives a PHP error
- Allow post requests
Testing instructions:
- Go to a container that is a plate, eg /containers/cid/263100
- Click 'Prepare For Data Collection'
- Click 'Add All To Queue'
> LIMS-219: Add All Samples To Queue

- client/src/js/app/store/store.js
- client/src/js/modules/types/mx/shipment/views/container-mixin.js
Ticket: [LIMS-210](https://jira.diamond.ac.uk/browse/LIMS-210)
Changes:
* We now know that double-clicking on the tick button when editing samples can create 2 samples in the same location. By closing the editor before saving, we prevent that.
Tests:
* Editing a sample and single clicking creates one sample
* Editing a sample and double clicking only creates one sample
* Editing a sample, leaving invalid parameters, clicking should leave the editor open and not create a sample
> LIMS-210: Prevent double clicking to create multiple samples

- api/src/Page/DC.php
- client/src/js/templates/dc/dc_title.html
**JIRA ticket**: [LIMS-499](https://jira.diamond.ac.uk/browse/LIMS-499)
**Summary**:
The reciprocal space viewer is a useful tool, hidden away in the (unlabelled) attachments for each data collection. We should make it more obvious.
**Changes**:
- Pull from the database whether any of the attachments are of type reciprocal space viewer (I would expect only one type of attachment per DC)
- If any are RSV's, then change the icon and title to something more suitable.
**To test**:
- Test a data collection group has the new icon and title for the icon, and the correct number still (eg /dc/visit/cm33866-3/ty/fc)
- Test a single data collection has the new icon etc (eg /dc/visit/cm33866-3/id/11467902)
- Test a data collection with a non-RSV attachment has the old file icon (eg …
> LIMS-499: Make reciprocal space viewer more obvious

- client/src/js/modules/dc/views/gridplot.js
- client/src/js/templates/dc/gridplot.html
Ticket: [LIMS-154](https://jira.diamond.ac.uk/browse/LIMS-154)
* Add a dropdown for the various snapshots taken for a grid scan (see eg /dc/visit/sw34709-4/dcg/9689655)
* Add button to see the full image, not just the zoomed in area of the grid scan
* Add gallery controls to the full image view to allow moving through all of them
* Disable the per-image analysis overlay if the selected image is a different width to the first image, as the coordinates will not match (this is just VMXi, see eg /dc/visit/nt30330-129/id/10981728)
> LIMS-154: Enable display of all grid scan snapshots in full

- api/src/Page/DC.php
- api/src/Page/Processing.php
- client/src/js/modules/dc/views/grid.js
**JIRA ticket**: [LIMS-952](https://jira.diamond.ac.uk/browse/LIMS-952)
**Summary**:
Beamlines have complained that an Xray Centring results bar appears under any grid scan, so only show the bar if '3d' xray centring has been used. A normal grid scan is classified as '2d'. Also fix the results displayed.
**Changes**:
- Don't display the results bar if not using '3d' xray centring
- Restore the /grid/xrc/:id endpoint, and return all crystal results from xray centring, with x/y/z values
- Display all crystal x/y/z results in results bar
**To test**:
- Check no results bar displayed for 'normal' grid scan (eg /dc/visit/cm33866-3/id/11284158)
- Check results bar displayed with multiple crystal positions if found (eg /dc/visit/nr27313-243/dcg/10077627)
- Check results bar shows failure if no …
> LIMS-952: Display xray centring results if running 3d xray centring

- client/src/js/modules/fault/routes.js
**JIRA ticket**: [LIMS-150](https://jira.diamond.ac.uk/browse/LIMS-150)
**Summary**:
Fix bug where https://ispyb.diamond.ac.uk/faults/edit is broken.
**Changes**:
- Add MarionetteView component in the same way as faults/add and faults/{faultid}
**To test**:
- Test user with fault_admin privilege can see the "Fault Database Editor" at faults/edit
- Test unprivileged user sees an error
- Test can add new Systems, Components and Subcomponents
> LIMS-150: Cannot edit fault components

- api/config_sample.php
- api/src/Page/Shipment.php
- api/src/Shipment/ShippingService.php
**JIRA ticket**: [LIMS-933](https://jira.diamond.ac.uk/browse/lims933)
**Summary**:
This change attaches an auth header to shipping service requests. This is either the user access token as a bearer token or basic auth using stored synchweb credentials.
**Changes**:
- Added new separate configuration parameters for shipping service API and frontend URLS.
- Added configuration parameters for shipping service basic auth credentials.
- If the user session token cookie is present, it is added as a bearer token in shipping service requests. If not present, stored basic auth credentials are used.
- AWB PDF email link has been changed to point to the frontend AWB page rather than a direct link to the PDF from the backend.
**To test**:
- Check that, when a user books a shipping service shipment …
> LIMS-933: Attach auth header to shipping service requests

- api/config_sample.php
- api/src/Page.php
**JIRA ticket**:  [TICKET-1027](https://jira.diamond.ac.uk/browse/LIMS-1027)
**Summary**:
If in config.php ldap server is set to null then no name lookup is done when emails are sent. This allows us to test sending email in dev 
**Changes**:
- Don't use LDAP server
**To test**:
- Send an email in dev with ldap server set to null. Emails should appear in emails.txt if using the latest podman image.
> LIMS-1027: Allow emails to be sent whwn LDAP server is not configured

- api/src/Page/Contact.php
**JIRA ticket**: [LIMS-1029](https://jira.diamond.ac.uk/browse/LIMS-1029)
**Summary**:
Fix bug getting laboratoryId when creating a Lab Contact using the Login field, introduced in https://github.com/DiamondLightSource/SynchWeb/pull/622
**Changes**:
- Fix getting laboratoryId, as db queries always return a list
**To test**:
- Test creating a Lab Contact using the Login field, when logged in someone with an associated Laboratory eg ndg63276
- Test creating a Lab Contact using the Login field, when logged in as someone with no associated Laboratory
- Test creating a Lab Contact leaving the Login field blank
> LIMS-1029: Fix bug creating lab contact with login

- api/src/Page/Shipment.php
- client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue
**JIRA ticket**: [I15_1-1318](https://jira.diamond.ac.uk/browse/I15_1-1318)
**Summary**:
Simple sample creation uses a 'default' dewar inside a 'default' shipment. Previously these were associated with and named after visit 0, as a beamline visit may not exist. But we no longer use visit 0, so it was failing. So just use a default dewar/shipment named after the proposal.
**Changes**:
- Allow requests to api/shipment/dewars/default without a visit parameter, as long as the prop parameter is still there
- Use variables for shipment name, dewar name and barcode to allow use with either visit or prop
- Dont add anything to ShippingHasSession if not specifying visit
- Don't use visit in container name if visit is undefined
**To test**:
- Create a new simple sample in a proposal, check it …
> I15_1-1318: Cannot create default shipment for visit 0

- api/src/Page/Imaging.php
- client/src/css/partials/_utility.scss
- client/src/js/modules/imaging/views/imageviewer.js
- client/src/js/modules/shipment/views/containerplate.js
- client/src/js/modules/shipment/views/plate.js
- client/src/js/templates/shipment/containerplateimage.html
Ticket: [LIMS-95](https://jira.diamond.ac.uk/browse/LIMS-95)
* Once a plate is imaged, the previous drop scoring is hidden, so a user may have to click through each drop again and score them
* Add a checkbox to show the 'max' score for each drop, which will allow them to quickly see which drops have been highly scored in the past
Testing (on dev db):
* go to proposal 30330, go to a container
* click on some drops, set a score, change inspections and repeat
* tick 'Max scores' radio button to show the highest score colour for each drop
* Also try "Current scores", "Data Status" and "Auto Scores" with various drop downs (Schema CHIMP should not be visible)
> LIMS-95: Show max score for each drop in a plate

- client/src/js/modules/dc/views/gridplot.js
**JIRA ticket**: [LIMS-140](https://jira.diamond.ac.uk/browse/LIMS-140)
**Summary**:
For a VMXi grid scan, if you select pia_estimated_d_min as the dropdown, the heat map disappears.
**Changes**:
- Fix the _getVal function to get data from the visible dropdown so that clicking on a box shows the value
- Invert the values sent to the heatmap for pia_estimated_d_min, as they are resolutions, so 1 is better than 2.
- Dont pad the maximum by 50x if values are inverted
**To test**:
- Test heat map of i03 grid scan (eg /dc/visit/cm33866-4/dcg/10292076), check heat map looks normal for all PIA selections
- Test heat map of VMXi grid scan (eg /dc/visit/nt30330-145/id/11688261), check heat map looks normal for all PIA selections, including for (inverted) values of pia_estimated_d_min
> LIMS-140: Fix pia_estimated_d_min display on VMXi grid scans

- client/src/js/modules/types/mx/samples/sample-table-row.vue
**JIRA ticket**: [LIMS-309](https://jira.diamond.ac.uk/browse/LIMS-309)
**Summary**:
MX users shouldn't be able to create new proteins within ISPyB, they should create them in UAS to be assessed, then they are copied over. The 'Create New' button that appears now doesn't do anything, so should be removed (for MX proteins, not in general)
**Changes**:
- Set property canCreateNewItem to false when creating the combo box
**To test**:
- Create a new puck, try to create a new protein, verify the 'Create New' button doesn't appear.
- Check can use existing proteins
> LIMS-309: Remove the Create New button in the protein acronym field for MX

- api/scripts/mtz2map.sh
- api/src/Downstream/BigEPPhasing.php
- api/src/Downstream/Type/FastEp.php
- api/src/Page/DC.php
- api/src/Page/Download.php
- api/src/Page/Processing.php
- client/src/js/modules/dc/views/autoprocattachments.js
- client/src/js/templates/dc/dc_autoproc.html
- client/src/js/templates/dc/downstreamerror.html
**JIRA ticket**: [LIMS-1074](https://jira.diamond.ac.uk/browse/LIMS-1074)
**Summary**:
To save on disk space, many files created by auto processing pipelines have been zipped (*.gz), which breaks the links to them in Synchweb, as well as a number of image files and map / model viewers. These should be fixed server-side.
**Changes**:
- Use gzopen and gzread to temporarily unzip the processing files before serving them to the front end
- Add already zipped files to archive.zip file served by "Archive" button (they download as unzipped files zipped together)
- Fix the map / model viewer shell script to unzip the relevant files first
- Fix 2 silly spelling mistakes
**To test**:
- View a pre-2022 data collection with autoprocessing, eg /dc/visit/mx23694-64/id/6669874
- For fast_dp
- Check the …
> LIMS-1074: Allow accessing zipped files

- api/src/Authentication/Type/OIDC.php
**JIRA ticket**: [LIMS-1068](https://jira.diamond.ac.uk/browse/LIMS-1068)
**Summary**:
- Reduce number of calls to OIDC provider by only performing discovery when necessary
- Get expiration time for token from provider, apply it to cookie
**Changes**:
- Cookie expiry is applied based on value returned from OIDC provider
- Endpoint discovery is only performed when a function is called and there are no known endpoints
**To test**:
- Check if user logout behaves as expected
- Check if user login behaves as expected
- Check if opening page in a new tab doesn't trigger login
- Check if moving between pages works
> LIMS-1068: Move discovery away from constructor, get cookie expiry dynamically

- client/src/js/templates/shipment/shipment.html
- client/src/js/templates/shipment/shipmentadd.html
**JIRA ticket**: [LIMS-1009](https://jira.diamond.ac.uk/browse/LIMS-1009)
**Summary**:
As visits can now be in person and not just remote, we no longer need to refer to 'responsive remote' sessions, we can just say 'responsive' sessions.
**Changes**:
- Remove the word remote in a couple of places
- Clarify that UDC dewars should select Automated
**To test**:
- Test creating a shipment, new labels should appear
- View an existing shipment, new label should appear
> LIMS-1009: Remove the word 'remote' from 'responsive remote'

- .github/workflows/ci.yml
- api/psalm.xml
- api/src/Authentication/Type/LDAP.php
- api/src/Page.php
**JIRA ticket**: None
**Summary**:
Set up Psalm so that if it runs and fails the build fails
**Changes**:
- make constants as ok
- update the build in github
**To test**:
- check that build passes
> Make psalm passing part of the build

- api/src/Database/DatabaseQueryBuilder.php
- api/src/Page/Contact.php
- api/tests/Database/DatabaseQueryBuilderTest.php
**JIRA ticket**: [LIMS-1025](https://jira.diamond.ac.uk/browse/LIMS-1025)
**Summary**:
Fix lab contact search
**Changes**:
- Create a where clause to match the passed in search term to any of the lab contact fields
- Start with a known false condition as each field adds an "or" clause
**To test**:
- Go to a list of lab contacts on a proposal and search for each field in turn
- View a single lab contact, test it displays correctly
> LIMS-1025: Fix lab contact search

- client/src/js/modules/shipment/views/shipmentadd.js
**Original issue**: https://github.com/DiamondLightSource/SynchWeb/issues/232
**JIRA ticket**: [LIMS-693](https://jira.diamond.ac.uk/browse/LIMS-693)
**Summary**:
Automatically focus on "Name" field on the Add New Shipment page.
**Changes**:
- Add a new onShow method (triggered after onRender) with the .focus() command
**To test**:
- Log in, pick a proposal, click Shipments, then Add New Shipment. Start typing, it should go into the Name field.
> LIMS-693: Give Name text field default focus in Add New Shipment view

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-978](https://jira.diamond.ac.uk/browse/LIMS-978)
**Summary**:
If you look at a registered dewar that has been created since 2020, you cannot edit the purchase date or facility code.
**Changes**:
- Use the DewarRegistry_has_Proposal table to link DewarRegistry to Proposal, rather than DewarRegistry.proposalId.
**To test**:
- Log in, go to a proposal, then go to a recently registered dewar (eg /dewars/registry/DLS-MX-1230). Try to edit the facility code or the purchase date. Check the HTTP response, before this change you get "No such dewar".
**NB**
There is no need to put in OR statements to allow either the old style or the new style, as there is a ticket in to replace all the old style rows with new style ones.
> LIMS-978: Use DewarRegistry_has_Proposal table

- api/config_sample.php
- api/src/Page/Vstat.php
- client/src/js/modules/stats/views/callout.js
- client/src/js/modules/stats/views/visit.js
- client/src/js/templates/stats/visit.html
Ticket: [LIMS-898](https://jira.diamond.ac.uk/browse/LIMS-898)
* Main bug was returning the object containing the callouts instead of an array of the callouts (foreach clause on $calls_tmp)
* Moved URLs to config.php
* Removed the blank columns from callouts
* Fixed callouts and elog entries divs being flipped
> LIMS-898: Fix callouts in visit stats

- api/config_sample.php
- api/index.php
- client/src/css/partials/_header.scss
- client/src/index.php
- client/src/js/app/components/footer.vue
- client/src/js/app/store/store.js
**JIRA ticket**: [LIMS_1053](https://jira.diamond.ac.uk/browse/LIMS-1053)
**Summary**:
The MotD is not the best place for the Synchweb version number, so let's put it in the footer. While we're at it, let's improve the look of the footer, using @jlmuir's code from https://github.com/DiamondLightSource/SynchWeb/pull/144
**Changes**:
- Move Synchweb link to left of footer, site link to the right
- Do the same for both vue and non-vue versions
- Expose $synchweb_version in the api/options endpoint
- Add the Synchweb version to the footer if it is specified
- Add the variable to the example config.php
**To test**:
- View the footer on any page, check it looks ok
- Check the $synchweb_version is displayed
- Check no errors occur if $synchweb_version is absent
> LIMS-1053: Put synchweb version in footer

- client/src/js/templates/shipment/shipment.html
Ticket: [LIMS-996](https://jira.diamond.ac.uk/browse/LIMS-996)
Changes:
* Trim courier name before comparing to 'dhl', otherwise couriers like ' dhl' and 'dhl ' will be rejected.
Tests:
* Go to a test shipment eg on mx23694, edit courier name to 'DHL', check 'Create Air Waybill' button remains after refresh
* Edit courier name to ' DHL', check button remains after refresh
* Edit courier name to 'Fedex', check button has gone after refresh
> LIMS-996: Trim empty space around courier name

- api/src/Page/Sample.php
**JIRA ticket**: [LIMS-768](https://jira.diamond.ac.uk/browse/LIMS-768), [LIMS-650](https://jira.diamond.ac.uk/browse/LIMS-650)
**Summary**:
I15-1 have asked for the BLSample.name and Crystal.name fields to be changed for Simple Sample uploads
**Changes**:
- Use {acronym}-sample as Crystal.name
- Use {acronym} as BLSample.name
**To test**:
- Go to a 'Phase' eg /phases/pid/580719
- Click 'New Simple Sample'
- Fill Acronym as something memorable eg 'foo', and Packing Fraction as 0
- Verify new sample is created with name 'foo-sample'
- Verify new instance of sample is created with name 'foo'
> LIMS-768: Modify the values saved in database for Simple Sample Uploads

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-1125](https://jira.diamond.ac.uk/browse/lims-1125)
**Summary**:
If the shipping service returns a 401 when a user attempts to book an incoming shipment (due to an expired token), prompt the user to log in again.
**Changes**:
- Return errors received from the shipping service to the frontend when trying to book an incoming shipment.
**To test**:
- Check that shipping service error statuses and content details are returned to the client from the backend. In particular, check that a 401 error code results in the user being prompted to log in again.
> LIMS-1125: Prompt user login on shipping service 401 status

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-1136](https://jira.diamond.ac.uk/browse/LIMS-1136)
**Summary**:
Currently, it is possible for post codes to contain spaces before and after the actual post code. Sending such post codes to the shipping service results in a 422 error.
**Changes**:
- Use `trim` rather than `rtrim`, for post code and email address.
**To test**:
- Book an incoming shipment
- Book an incoming shipment with a space at the start of the post code
- Book an incoming shipment with a space at the start of the email address
> LIMS-1136: Trim preceding spaces from postcode and email address

- client/src/js/app/layouts/main.vue
- client/src/js/app/layouts/maintenance.vue
**JIRA ticket**: [LIMS-1161](https://jira.diamond.ac.uk/browse/LIMS-1161)
**Summary**:
The Synchweb main view uses 10/12 (83.33%) of the width of the browser for large screen sizes (lg:tw-w-10/12). This wastes a lot of screen space, so have upped it to 11/12 (91.67%). (Full screen display looks weird)
**Changes**:
- Change main view from 10/12 width to 11/12 width
- Apply same change to 'maintenance mode' view
**To test**:
- Check main synchweb view looks ok in large browser
- Check full width is still used for small browsers / mobile.
> LIMS-1161: Widen main view from 10/12 to 11/12

- api/src/Database/Type/MySQL.php
**JIRA ticket**: [LIMS-1026](https://jira.diamond.ac.uk/browse/LIMS-1026)
**Summary**:
Floats from the database are rounded to 5 decimal places, then rounded again when displayed. See eg https://ispyb.diamond.ac.uk/dc/visit/mx33658-13/id/11629518 which has wavelength of 0.953745 rounded first to 0.95375 then again to 0.9538.
**Changes**:
- Delete the code that rounds unnecessarily
**To test**:
- Go to https://ispyb.diamond.ac.uk/dc/visit/mx33658-13/id/11629518, check wavelength is displayed correctly as 0.9537A.
- Check no other numbers are shown with extra precision
> LIMS-1026: Don't round everything to 5 decimal places

- client/src/js/templates/dc/dc_autoproc.html
**JIRA ticket**: [LIMS-851](https://jira.diamond.ac.uk/browse/LIMS-851)
**Summary**:
Beam centre(starting and refined) display (and warnings if different) were disabled for "sm" beamlines (I19 at DLS) in https://github.com/DiamondLightSource/SynchWeb/pull/81. We want to put them back in.
**Changes**:
- Remove "if  type != sm" clause
**To test**:
- Go to a data collection with beam centre (eg /dc/visit/cy29890-8/id/12536146), check it displays in the auto processing stats
- Go to an old data collection with start beam centre of 0,0 ( eg /dc/visit/cm26454-1/id/4563855), check a warning appears saying the beam centre has moved significantly
> LIMS-851: Display beam centre (and warnings) for i19

- api/src/Controllers/AuthenticationController.php
- api/src/Model/Services/AuthenticationData.php
**JIRA ticket**: [LIMS-1163](https://jira.diamond.ac.uk/browse/LIMS-1163)
**Summary**:
Users complain of not being allowed to print an air waybill after booking a shipment into Diamond.
**Changes**:
- Specify in the error message generated whether this is because the one time token is too old, or non-existent
- Add user agent and timestamp to the error message generated
- Allow increasing of 10 second age limit with an optional config variable
**To test**:
- Generate an AWB for a shipment, check can view it from the shipment page
- Set a $max_token_age = -1 config variable and check the error generated (delete it afterwards)
- View a visit pdf report and CSV download from /visits page, as these also use the sign function
> LIMS-1163: Improve error message when token is invalid

- api/src/Page/Sample.php
- client/src/js/modules/imaging/views/queuecontainer.js
**JIRA ticket**: [LIMS-980](https://jira.diamond.ac.uk/browse/LIMS-980)
**Summary**:
LIMS-219 (https://github.com/DiamondLightSource/SynchWeb/pull/591) added a button to add all subsamples to the queue, but it ignored the current filter, which can be auto/manual/point/region.
**Changes**:
- Get the id of the currently selected filter element and add it to the backend request
- Use the filter supplied to alter the where clause of the query
**To test**:
- Go to a VMXi proposal (eg nt37104), go to Containers, pick one. On the next page mark a point and a region using the "Mark Point" and "Mark Region" buttons. Click "Prepare for Data Collection"
- Filter the available samples using the Point/Region/Auto/Manual buttons, click the Add All to Queue button. Check the right number appear in the …
> LIMS-980: Add all samples to queue should obey filters

- api/src/Page/Sample.php
- client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue
**JIRA ticket**: [LIMS-1192](https://jira.diamond.ac.uk/browse/LIMS-1192)
**Summary**:
A recent change (https://github.com/DiamondLightSource/SynchWeb/pull/686) improved the names of samples, but also affected the names of automatically created capillaries. This then broke things further down the chain.
**Changes**:
- Put the crystal name back to how it was for capillaries
- Use the passed in crystal name for the sample name
- Change the crystal name passed in for non-capillary crystals
**To test**:
- Go to cm37261, then go to Phases, pick one. Click "+ New Simple Sample", fill in the form with a memorable acronym, and use one of the Borosilicate capillaries and submit. Then go to Samples, 2 should have been created. One named acronym-sample, and one ending in _CP for the capillary.
- …
> LIMS-1192: Fix capillary names

- api/config_sample.php
- api/src/Controllers/AssignController.php
- api/tests/Controllers/AssignControllerTest.php
**Github issue**: https://github.com/DiamondLightSource/SynchWeb/issues/53
**JIRA ticket**: [LIMS-697](https://jira.diamond.ac.uk/browse/LIMS-697)
**Summary**:
@jlmuir points out that not all facilities have a one-to-one mapping of beamlines to pv prefixes (DLS included). As the `$bl_pv_map` variable is only used in one place, we should replace it with a template for the specific PVs it is used for.
**Changes**:
- Remove `$bl_pv_map` variable
- Remove DLS-specific hardcoded PV names
- Add `$bl_puck_names` variable for a template for the puck names PV
**To test**:
- Go to the assign container page for a visit (eg /assign/visit/cm37235-1) and check the loaded pucks are displayed next to the puck number (eg CPS-0001 below)
> LIMS-697: Use more specific PVs for puck names

- api/src/Page/DC.php
- client/src/js/templates/dc/dc.html
**JIRA ticket**: [LIMS-1185](https://jira.diamond.ac.uk/browse/LIMS-1185) and [LIMS-1212](https://jira.diamond.ac.uk/browse/LIMS-1212)
**Summary**:
The total dose displayed on data collection groups is incorrect, and also shown to a huge number of decimal places.
**Changes**:
- Limit the totaldose field to 2 decimal places, as done for other fields
- Use the totaldose returned from the backend, which does a sum of the total absorbed dose, rather than getting one value and multiplying by the number of data collections.
- Also limit chi/phi/overlap to 1 decimal place
**To test**:
- View a data collection group, eg /dc/visit/cm33903-5/dcg/10774174, check the dose displayed for each data collection is shown to 2 decimal places. Add together the total dose for the group (11.40MGy)
- Find the …
> LIMS-1185: Fix incorrect total dose displayed

- api/assets/emails/html/dewar-transfer.html
- api/assets/emails/html/storage-rack.html
- client/src/js/templates/shipment/transfer.html
**JIRA ticket**: [LIMS-904](https://jira.diamond.ac.uk/browse/LIMS-904)
**Summary**:
Give users a bit more guidance if they require more data collection time.
**Changes**:
- Edited the post-visit email to say "Or fill out the dewar transfer form if you require more data collection time:" instead of "Or fill out the dewar transfer form if you would like it to be transferred to another beamline for another visit"
- Removed instruction to print this email
- Edited the transfer request form help text under 'Next Visit' to say 'Select "-" to return the dewar to the responsive scheduling queue'
- Removed the comments field from the transfer request form, as they are not recorded anywhere
**To test**:
- Fill out a dewar transfer request, check there is no comments field, check it correctly sends …
> LIMS-904: Improve help text for internal transfer requests

- api/docs/dist/spec.json
**JIRA ticket**: [LIMS-1138](https://jira.diamond.ac.uk/browse/LIMS-1138)
**Summary**:
The docs for the Synchweb API are outdated in a few places, this PR is to update them. As first reported in https://github.com/DiamondLightSource/SynchWeb/issues/217.
**Changes**:
- Remove required prop parameter from /proposal (get)
- Add required prop parameter to /proposals/visits/visit (get/patch) and /dc/{id} (get)
- Update endpoint for /dc/{id}, /dc/single/t/{type}/{id}, /processing/status, /processing/{id}
- Remove non-existent get on /dc/single/t/{type}/{id}
- Fix docs on post to /dc/comment
- Remove non-existent event types
**To test**:
- Go to https://editor.swagger.io/, load spec.json
> LIMS-1138: Update Swagger spec

- api/src/Page/DC.php
**JIRA ticket**: [LIMS-1219](https://jira.diamond.ac.uk/browse/LIMS-1219)
**Summary**:
The processing errors tab in the data collections page performed an outer join that effectively evaluated to outer joining on `true`, creating an unperformant query that took up lots of resources and often timed out.
Also, the query that returns the total number of pages performed `UNION`s instead of `UNION ALL`s, which could result in an unexpectedly smaller page count. Due to deduping.
**Changes**:
- Rewrote two portions of the query
**To test**:
- Go to a data collection (/dc/visit/cm33866-1/ty/dc), check if the page loads
- Go to a data collection processing errors tab (dc/visit/cm33866-1/ty/err), check if the page times out
- Switch to the new changes, observe that now the processing errors tab …
> LIMS-1219: Fix slow data collection queries

- client/src/js/modules/calendar/views/calendar-view.vue
**JIRA ticket**: [LIMS-303](https://jira.diamond.ac.uk/browse/LIMS-303)
**Summary**:
The Calendar view currently only shows visits from the same beamline 'type' as the active proposal. Users would like to be able to see their visits from all villages. Don't apply to staff as the visit list becomes unwieldy.
Also, the visit list is requested 3 times when the page is first loaded.
**Changes**:
- Only specify the beamline type if a staff member is logged in
- Dont fetch the new visit list when the current year/month is first set, there is an explicit fetch in the `mounted()` function
**To test**:
- Log in as a staff member, check the calendar page displays as before, but there is only one request to `/api/proposal/visits`
- Log in as a user who has visits in different villages (eg ygr68196), …
> LIMS-303: Show visits from other villages on user calendar

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-1011](https://jira.diamond.ac.uk/browse/LIMS-1011)
**Summary**:
New proposals need dewars registering to them before they can ship samples, and staff have to do this. But often new proposals dont have any lab contacts yet, so we cant add the proposal to the dewar.
**Changes**:
- Make lab contact an optional field in the function
**To test**:
- Add a dewar to a proposal without any lab contacts, eg nt33918, check the server responds with a DEWARREGISTRYHASPROPOSALID
- Add a dewar to a proposal with lab contacts, same check
> LIMS-1011: Allow linking of registered dewars to proposals without a lab contact

- client/src/js/templates/types/sm/dc/dc.html
**JIRA ticket**: [LIMS-1232](https://jira.diamond.ac.uk/browse/LIMS-1232)
**Summary**:
I19 is now doing small molecule serial, where every other collection is run with backwards oscillation. Unfortunately, recording this accurately in ISPyB doesn't show the autoprocessing sections in Synchweb.
This changes the check to be truthy (nonzero) instead of purely positive.
Also fixes an adjacent issue where a null value for overlap was passing the intended non-zero check (null != 0). This is made truthy also.
**Changes**:
- Altered data checks to check truthiness instead of comparisons to zero
**To test**:
- Viewing https://ispyb.diamond.ac.uk/dc/visit/cy35300-1/dcg/11242587 should show "Auto Processing" for both collections, instead of the current situation:
> Handle -ve rotations, null overlap in sm/DC

- api/src/Page/Sample.php
**JIRA ticket**: [LIMS-1202](https://jira.diamond.ac.uk/browse/LIMS-1202)
**Summary**:
On an xpdf proposal, on the Phases page, there is a tickbox to "Show Only UAS Samples". This has the effect of grouping phases by their external id, so only one entry appears for each UAS sample, but as they are ordered by most recent, the recent non-UAS phases are shown instead of older UAS phases.
Sorting on the same table only worked for a couple of columns as well.
**Changes**:
- When the "Show only UAS Samples" tickbox is ticked, only show Phases (Proteins) with the "proteinType" of "ORIGIN:UAS"
- Add more possible columns to sort by in the database query
- Get the number of samples and number of data collections in the original query so they can be used for sorting as well
- Remove redundant …
> LIMS-1202: Fix UAS filter and table sorting on Phases/Proteins page

- api/composer.json
**JIRA ticket**: [LIMS-1214](https://jira.diamond.ac.uk/browse/LIMS-1214)
**Summary**:
Update composer.json to use Symfony 5.4 components
Composer.json includes two Symfony components, symfony/http-foundation and symfony/filesystem. Both references updated from 2.8 to 5.4, the last Symfony 5.n release. (Now the server runs PHP 7.3.33, composer.json may reference Symfony 5.4 components which require PHP 7.2.5 or later.)
SynchWeb’s Download class uses Filesystem, BinaryFileResponse, and StreamedResponse.
**Changes**:
- Update references to symfony/http-foundation and symfony/filesystem in composer.json.
**To test**:
- Download auto processing output via the “Logs & Files” list.
- Download .zip archive via “Archive” button.
> LIMS-1214: Update composer.json to use Symfony 5.4 components

- api/src/Page/Vstat.php
- client/src/js/modules/stats/views/breakdown.js
**JIRA ticket**: [LIMS-1255](https://jira.diamond.ac.uk/browse/LIMS-1255)
**Summary**:
It was noticed the visit stats page doesn't load for some visits eg https://ispyb.diamond.ac.uk/stats/visit/mx30106-12. This is caused by the CTF query doing unnecessary joins to Proposal and v_run, which are only referenced in $where if a visit is not supplied.
On further inspection, the whole CTF query is not necessary, this is only for EM which is now using PaTo. So I have removed the query and the JS that references the output.
**Changes**:
- Remove unnecessary joins to Proposal and v_run from some queries
- Remove entire CTF query and data manipulation
- Remove references to the 'scatters' data
**To test**:
- Load visit stats page for an mx visit, check everything appears correctly
> LIMS-1255: Fix problematic query on visit stats page

- client/src/js/modules/types/em/dc/redirect.vue
**JIRA ticket**: [LIMS-1288](https://jira.diamond.ac.uk/browse/LIMS-1288)
**Summary**:
When visiting an EM DC page for a null session, currently, the proposal or visit are not properly included in the URL. This fixes this by only including the session in URL if the session is valid, and in case both the proposal/session are not available through a prop or the URL, the redirect points to PATo's home page.
**Changes**:
- Add conditional checks to build the redirection URL dynamically, taking into consideration the session/proposal validity.
**To test**:
- Visit an EM DC page pointing to a null session (/dc/visit/ic37826-null) and check that only the proposal is included in the redirect
- Visit a regular EM DC page (/dc/visit/bi23047-119) and check that both the session number and proposal …
> [LIMS-1288] SynchWeb link to PATo with undefined session

- client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue
**JIRA ticket**: [LIMS-1201](https://jira.diamond.ac.uk/browse/LIMS-1201)
**Summary**:
When an i15-1 user creates a new sample using a standard capillary, a Crystal is made to represent the capillary, currently using the UAS acronym, the standard capillary name and the string "_CP".
They would like this changed to use the user-entered acronym rather than the UAS acronym.
**Changes**:
- Replace name (from UAS) with acronym (from user) for both simple sample form and CSV upload
**To test**:
- On the dev db:
- Go to proposal cm37261, select Phases from the main menu
- Click on a phase eg H2O.1, then click "New simple sample"
- Choose "File upload for multiple samples"
- Select this file [simple_sample_csv_template.csv](https://github.com/DiamondLightSource/SynchWeb/files/14538814/simple_sampl …
> LIMS-1201: Amend name of XPDF capillary crystal to use user acronym

- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/utils/validation.js
**JIRA ticket**: [LIMS-1256](https://jira.diamond.ac.uk/browse/LIMS-1256)
**Summary**:
A user couldn't fill in the dispatch request form because the local contact had an "ö" in their name and the form rejected the "ö". As the user cannot edit this field any more, we should remove the validation.
**Changes**:
- Remove validation from local contact field
- Remove wwsddash pattern as it is not used anywhere else
**To test**:
- Do a dispatch request, check the form still submits ok
> LIMS-1256: Remove validation from Local Contact field

- client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
**JIRA ticket**: [LIMS-667](https://jira.diamond.ac.uk/browse/LIMS-667)
**Summary**:
If the user creates a plate without a requested imager, then the plate does not get assigned an imaging schedule when it is read by our Formulatrix system and is not imaged.
**Changes**:
- Set a validation provider for the requested imager field, but only if the container type is plate (requested imager field is only shown if container type is plate)
**To test**:
- Go to Add Container page, create a puck with at least one sample, check it is allowed without a Requested Imager
- Try to create a plate (eg container type CrystalQuickX) with at least one sample, without selecting an imager, check it is not allowed and the user is directed to the error
- Choose an imager and check the plate is created …
> LIMS-667: Make the Requested Imager a required field if a plate is being created

- api/src/Page/Download.php
**JIRA ticket**: [LIMS-1261](https://jira.diamond.ac.uk/browse/LIMS-1261)
**Summary**:
On the container view, grid scan heatmaps have been broken by linking to GridInfo by dataCollectionId rather than dataCollectionGroupId.
**Changes**:
- Add another join to GridInfo using dataCollectionId, then use those values if the original ones are null
**To test**:
- Find a 2024 container with grid scans from VMXi (eg /containers/cid/290064/iid/125013/ well 19), the grid area should be shown on the crystal image, with a heatmap of diffraction over it.
- Check the same for a 2023 container (eg /containers/cid/280354/iid/117934 well 56)
> LIMS-1261: Fix the grid scan heat maps on the VMXi container view

- api/src/Page/Sample.php
**JIRA ticket**: [LIMS-1289](https://jira.diamond.ac.uk/browse/LIMS-1289)
**Summary**:
The values for the numbers of samples and PDBs on the Proteins page are incorrect.
**Changes**:
- Use distinct to only count unique samples, PDBs and data collections
- Fix typo in function name
**To test**:
- Go to a proposal (eg cm37235) then go to the Proteins page, check no protein is listed as having thousands of samples or PDBs
- Click through to each protein and check the number of PDBs and samples match those shown on the proteins page
- Check each protein page displays correctly
- Add a new container to a shipment, check the list of (distinct) proteins populates correctly
> LIMS-1289: Fix sample and pdb count on proteins page

- client/src/js/templates/dc/action.html
- client/src/js/templates/dc/load.html
**JIRA ticket**: [LIMS-1304](https://jira.diamond.ac.uk/browse/LIMS-1304)
**Summary**:
The before and after snapshots in robot load, annealing and washing are the correct order in the page but captioned incorrectly. This swaps the captions around for both
**Changes**:
- Swaps captions for before/after crystals
**To test**:
- Confirm that in a robot load action the location of the before/after snapshot images have not moved but the captions now correctly label the left image as `Before`
> LIMS-1304: Correct the order of before and after snapshots

- client/src/js/app/components/header.vue
- client/src/js/modules/contact/views/contacts.js
- client/src/js/modules/types/mx/menu.js
- client/src/js/templates/header.html
**JIRA ticket**: [LIMS-1207](https://jira.diamond.ac.uk/browse/LIMS-1207)
**Summary**:
The main menu has too many items for MX and is in a weird order.
**Changes**:
- Make the calendar link in the top left be for all, not just staff, and remove the Calendar link in the menu
- Add a link to the migrate page from the lab contacts page, and remove the Migrate link from the menu
- Remove the Assign Container link from the menu, that is linked from each visit
- Re-order the remaining items to flow more naturally (particularly for new users)
**To test**:
- Check Calendar link appears and works for staff and non-staff
- Check "Migrate Lab Contacts" button appears on the Lab Contacts page and works
- Check all items in the main menu work
> LIMS-1207 - Improve main menu for mx

- api/src/Page/DC.php
- api/src/Page/Sample.php
- client/src/js/modules/projects/views/view.js
- client/src/js/templates/projects/projectview.html
**JIRA ticket**: [LIMS-1235](https://jira.diamond.ac.uk/browse/LIMS-1235)
**Summary**:
The list of samples and data collections for a project times out, as it is trying to list both explicitly linked samples and also implicitly linked (via protein) samples. 
**Changes**:
- Remove the option to show implicitly-linked samples and data collections, show only those explicitly linked to the project
**To test**:
- Create a new project, and add some proteins, samples and data collections to it
- Check they each appear on the project page promptly
- Check the implicit/explicit button has been removed
> LIMS-1235: Queries for implicit samples and DCs in project time out

- client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue
**JIRA ticket**: [LIMS-1200](https://jira.diamond.ac.uk/browse/LIMS-1200)
**Summary**:
One way to create multiple simple samples (for XPDF) is to upload a CSV file. A header row is compulsory and provided in the template, and is stripped by the CSV file library. However, the Synchweb code also strips the first subsequent row, meaning the first user sample is ignored.
**Changes**:
- No longer ignore the first row of the CSV file
**To test**:
- On the dev db:
- Go to proposal cm37261
- Select Phases from the main menu
- Click on a phase eg H2O.1
- Click "Add new simple sample"
- Choose "File upload for multiple samples"
- Select this file [simple_sample_csv_template.csv](https://github.com/DiamondLightSource/SynchWeb/files/14538814/simple_sample_csv_template.csv)
- Choose a plain capillary …
> LIMS-1200: CSV file upload ignores first sample

- api/src/Page/Proposal.php
- client/src/js/modules/visits/views/visit_list.vue
**JIRA ticket**: [LIMS-1174](https://jira.diamond.ac.uk/browse/LIMS-1174)
**Github issue**: https://github.com/DiamondLightSource/SynchWeb/issues/133
**Summary**:
If you end up on the visits page without a current proposal, you get a server error. This should be handled more gracefully.
**Changes**:
- Handle the error in PHP
- Redirect to the proposals page in JS
**To test**:
- Log in to Synchweb, but dont choose a proposal. Go to /visits/. It should redirect you to the proposals page.
> LIMS-1174: Handle blank proposal on visits page

- api/src/Page/DC.php
**JIRA ticket**: [LIMS-44](https://jira.diamond.ac.uk/browse/LIMS-44)
**Summary**:
The lookup of sessionid from proposal-visit is written sub-optimally, so it has to perform a full table scan on BLSession. This changes speeds up the block of code from 40ms to 1ms.
**Changes**:
- Use regex to split the visit string into proposal code, proposal number and visit number
- Query the db with those separately
**To test**:
- Go to any visit page (eg /dc/visit/mx23694-112) and check it loads correctly, showing data collections from that visit and only from that visit
- Go to the View All Data page (/dc) and check it loads correctly
> LIMS-44: Speed up visit query

- client/src/js/app/store/modules/store.menus.js
- client/src/js/modules/types/em/menu.js
**JIRA ticket**: [LIMS-1315](https://jira.diamond.ac.uk/browse/LIMS-1315)
**Summary**:
This pull request restores the dropdown menu in EM proposals, which was erroneously deleted beforehand.
**Changes**:
- EM menu files restored
**To test**:
- Select proposal `bi37694`, open the dropdown, verify that all EM-related options (shipments, etc.) are displayed
NOTE: this is merged directly to master as a hotfix for release `2024-R2.2`, and will be merged into future prerelease branches.
> LIMS-1315 - Restore EM menu in dropdown

- api/src/Page/Download.php
- api/src/Page/Sample.php
- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
- client/src/js/modules/types/xpdf/samples/views/vue-simplesample.vue
- client/src/js/utils/validation.js
**Summary**:
Merge 2.2 into master
**Changes**:
**To test**:
> Pre release/2024 r2.2

- api/index.php
- api/src/Page/Shipment.php
- api/src/Shipment/ShippingService.php
- client/src/js/modules/shipment/views/createawb.js
- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/templates/shipment/createawb.html
- client/src/js/templates/shipment/dispatch.html
**JIRA ticket**: [LIMS-1342](https://jira.diamond.ac.uk/browse/LIMS-1342)
**Summary**:
[ULIMS-50](https://jira.diamond.ac.uk/browse/ULIMS-50) introduced changes to the create AWB form. These changes should have no effect if 
`$use_shipping_service_redirect_incoming_shipments = False;`
in config.php.
**Changes**:
- Add a condition on `shipping_service_app_url_incoming`, which depends on `$use_shipping_service_redirect_incoming_shipments`
**To test**:
- Set `$use_shipping_service_redirect_incoming_shipments = false;`, then
- create a shipment from the UK, click Create DHL Air Waybill, check a full form appears, with Get Quote at the bottom
- click Use Facility Account, check the form stays, but Get Quote changes to Create Air Waybill
- create a shipment from Aruba, click Create DHL Air …
> LIMS-1342: Show regular create AWB form if shipping redirect not enabled

- api/src/Page/Imaging.php
- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-67](https://jira.diamond.ac.uk/browse/LIMS-67)
**Summary**:
The imaging admin dashboard (/admin/imaging, needs privileges) is very slow to load the containers and inspections tables. This PR is to fix these slow queries, trying not to break anything else.
**Changes**:
- Change default sorting on container table from bltimestamp to containerid. Some sorts are still slow, but at least the default is fast now.
- Remove the join to the massive BLSampleImage table from the Inspections query, instead do that as separate smaller queries afterwards and push them into the result.
- This breaks sorting by the Scored column, but I have added the ability to sort by several other columns as compensation.
**To test**:
- Go to /admin/imaging, check the page loads rapidly.
- Click …
> LIMS-67: Fix 2 slow queries on imaging admin dashboard

- client/src/js/app/store/modules/store.menus.js
- client/src/js/modules/samples/components/sample-group-create-and-edit.vue
- client/src/js/modules/shipment/components/plate-view.vue
- client/src/js/modules/types/em/menu.js
- client/src/js/modules/types/mx/samples/valid-container-graphic.vue
**JIRA ticket**: [LIMS-1334](https://jira.diamond.ac.uk/browse/LIMS-1334)
**Summary**:
Allow a plate sample that is already in a group to be selected for adding to a new group
**Changes**:
- Maintain a list of manually selected samples, pass that down to the plate view
- Use this list to decide whether a click is a select or deselect
- Use uniqBy instead of concatenating a difference list to return valid samples (this list includes those already in groups)
**To test**:
- Open proposal nt37104, go to Sample Groups, then Create Sample Group
- Select a shipment and a plate (with no coloured samples)
- Select a few samples and create a group with a name, check the view on the Sample Groups page that this has worked correctly
- Go back to Create Sample Group, use the same shipment and plate, …
> LIMS-1334: Allow selection of plate samples already in a group

- api/src/Page.php
- api/src/Page/Proposal.php
- client/src/js/app/components/header.vue
- client/src/js/modules/types/em/menu.js
- client/src/js/modules/types/gen/menu.js
- client/src/js/modules/types/mx/menu.js
- client/src/js/modules/types/pow/menu.js
- client/src/js/modules/types/saxs/menu.js
- client/src/js/modules/types/sp/menu.js
**JIRA ticket**: [LIMS-1246](https://jira.diamond.ac.uk/browse/LIMS-1246)
**Summary**:
Members of goods handling have the "all_dewars" permission in ISPyB. We should allow them to see all shipments, and print the shipping labels. They should also see the "Logistics" page (/dewars/overview) with the truck icon in the top right.
Unfortunately this PR also allows them to see:
- A list of all proposals (could be removed but seems useful so they can navigate to a specific shipment)
- A list of all samples for a proposal
- A list of all proteins for a proposal
- A list of all lab contacts for a proposal
- Registered dewars and containers for a proposal
Does not allow them to see:
- Any visits or data collections
- Any containers
- Any details on samples, proteins, lab contacts
**Changes**:
- …
> LIMS-1246: Allow users with all_dewars permission to view all shipments

- client/src/js/templates/dc/dc.html
**JIRA ticket**: [LIMS-1319](https://jira.diamond.ac.uk/browse/LIMS-1319)
**Summary**:
Dose (or total dose) is only shown for some data collection types. We should show it for all, when a value is in the database.
**Changes**:
- Remove check for DC type
**To test**:
- View a characterisation eg /dc/visit/au34221-5/id/13769997, check Dose is displayed (1.00 MGy)
- View an OSC experiment eg /dc/visit/au34221-5/id/13770015, check Dose is displayed
- View a visit with data collection groups, eg /dc/visit/mx34263-56, check Total Dose is displayed
- View a DC without a dose eg /dc/visit/mx23694-117, check no dose is displayed
> LIMS-1319: Show dose for all data collection types

- api/src/Page/Shipment.php
- client/src/js/modules/shipment/models/dewarregistry.js
- client/src/js/modules/shipment/views/dewarregistry.js
- client/src/js/modules/shipment/views/regdewar.js
- client/src/js/templates/shipment/dewarregistryadd.html
- client/src/js/templates/shipment/regdewar.html
**JIRA ticket**: [LIMS-954](https://jira.diamond.ac.uk/browse/LIMS-954)
**Summary**:
Now that the DewarRegistry table has a manufacturerSerialNumber column, we should make it editable in Synchweb.
**Changes**:
- Get serial number from database
- Update the INSERT statement for new dewars to allow serial number
- Update the loop that does the UPDATE statement for editing existing dewars
- Add optional text fields to both the new dewar and existing dewar pages
- Clear the field once a new dewar has been created
**To test**:
- Add a new Registered Dewar with and without a sserial number
- Edit an existing dewar to add a serial number (see PR https://github.com/DiamondLightSource/SynchWeb/pull/651 if you find a bug)
> LIMS-954: Add ability to edit manufacturer serial no on dewars

- api/assets/pdf/shipment_label.php
- api/assets/pdf/styles.css
- api/src/Page/PDF.php
**JIRA ticket**: [LIMS-1276](https://jira.diamond.ac.uk/browse/LIMS-1276)
**Summary**:
Add a bit more information to the dewar shipment label
**Changes**:
- Add instruction to remove old paperwork
- Remove "No of Parcels" from dewar label
- Add "Printed on" date to each page
- Limit number of puck names printed to 8, to prevent going onto another page
- Decrease indent on instruction list
**To test**:
- Go to a shipment, check the label looks sensible, compare with [shipping-label.pdf](https://github.com/DiamondLightSource/SynchWeb/files/14958921/shipping-label.pdf)
- Go to a shipment with more than 8 pucks (eg /shipments/sid/54450), check only the first 8 are printed, and "plus 3 more" (or however many)
> LIMS-1276: Add printed date to shipping labels

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-902](https://jira.diamond.ac.uk/browse/LIMS-902)
**Summary**:
When a user requests a dewar transfer, they either specify a future visit, or they can leave it blank if the visit has not yet been created. But if the samples have been collected through UDC, the containers will have an associated visit, and so the dewar won't appear on the list of those that need visits. So if they are requesting a transfer to a not-yet-created visit, then we should clear the sessionid's from the containers.
**Changes**:
- Get list of containers within the dewar
- Don't overwrite `$dew` so they can be accessed
- If the session id is null, set each container's session id to be null
**To test**:
- Test a dewar transfer request on a dewar with UDC pucks to a null session, puck session ids …
> LIMS-902: Clear sessionId from containers when requesting a dewar transfer

- client/src/js/modules/dc/views/samplechanger.js
**JIRA ticket**: [LIMS-277](https://jira.diamond.ac.uk/browse/LIMS-277)
**Summary**:
The sample changer view (/dc/sc/visit/<visit>) scales weirdly, depending on the number of pucks available on the beamline.
**Changes**:
- Force one of two possible aspect ratios, either 1.5 (10 pucks or less) or 0.4 (more than 10 pucks)
**To test**:
- Set up 3 beamlines in config.json with 10, 14 and 37 pucks, eg:
```
"pucks": {
"i03": 37,
"i19-1": 14,
"i19-2": 10
},
```
- Go to a visit on each beamline, and click on the Sample Changer view, eg /dc/sc/visit/cm37235-3
- Check the view looks reasonable with each number of pucks. If 10 pucks or less, the sample changer view is smaller, if more than 10 pucks, the view should be full width.
- Go back to the visit, if there is a roll out sample changer view …
> LIMS-277: Fix sample changer view scaling

- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/templates/shipment/dispatch.html
**JIRA ticket**: [LIMS-1382](https://jira.diamond.ac.uk/browse/LIMS-1382)
**Summary**:
Add a short message advising users to fill in the shipping service form in full.
**Changes**:
- Message added
**To test**:
- Set `$use_shipping_service_redirect = True;`
- Go to a shipment that has not accepted the DLS terms, eg from mx23694, click request dispatch, should see full form for dispatch within Synchweb
- Click Use Facility Account, check the form disappears, "Proceed" button appears, and a highlighted message appears
- Change the country to non-UK, check the form re-appears and the message disappears
> LIMS-1382: Add message to users about using the shipping service

- api/src/Page/Shipment.php
- api/src/Shipment/ShippingService.php
**JIRA ticket**: [LIMS-1370](https://jira.diamond.ac.uk/browse/LIMS-1370)
**Summary**:
With `$use_shipping_service = True;` but `$use_shipping_service_redirect = False;`, if the shipping service returns an error, we should display the message detail in Synchweb.
**Changes**:
- Dont try and get the AWB number if there was an error from the shipping service
- Pass the error message back to the GUI as a JSON encoded string, so it appears in the GUI
**To test**:
- NB this is a user dewar so only test on backup db, without sending emails
- Set `$use_shipping_service = True;` but `$use_shipping_service_redirect = False;`
- Go to a shipment that has already been dispatched by the shipping service, eg /shipments/sid/60942
- Click on the little house icon to request the dewar be returned, click …
> LIMS-1370: Handle errors from the shipping service

- api/src/Page/Sample.php
- api/src/Page/Stats.php
**JIRA ticket**: [LIMS-1240](https://jira.diamond.ac.uk/browse/LIMS-1240)
**Summary**:
We no longer populate the Screening.shortComments with 'EDNA Strategy 1', instead we just use 'Strategy 1'. Using the program version is more generic for getting any EDNA strategy, or use 'Strategy%' when comparing EDNA strategies.
**Changes**:
- Use programVersion instead of shortComments to search for EDNA results
- Fix accessing pipeline stats
- Search for 'Strategy%' instead of 'EDNA%' in pipeline stats, which has been used since 2018.
**To test**:
- Go to a container with samples that have been screened, eg /containers/cid/301095, inspect the GET to /api/sample, check that some of the samples have non-null values for SCRESOLUTION and SCCOMPLETENESS
- Go to Stats, then Pipeline Stats (this should …
> LIMS-1240: Dont use shortComments LIKE 'EDNA%'

- client/src/js/templates/fault/view.html
**JIRA ticket**: [LIMS-1369](https://jira.diamond.ac.uk/browse/LIMS-1369)
**Summary**:
Fault report titles should be editable
**Changes**:
- Match the class of the title span to the editable created in modules/fault/views/view.js
**To test**:
- Go to a fault report, edit the title.
- Check it won't let you leave a blank title
- Check you can add a new fault report
> LIMS-1369: Make fault report titles editable

- api/config_sample.php
- api/src/Authentication/Type/OIDC.php
- api/src/Utils.php
- client/src/js/app/views/login.vue
**JIRA ticket**: [LIMS-1355](https://jira.diamond.ac.uk/browse/LIMS-1355)
**Summary**:
Currently, support for OAuth2 code flow in the OIDC authentication type is tailored to CAS. In order to enable Keycloak compatibility, it must be configurable, down to the claim used for identifying users, as well as ensuring the whole process is not specific to one or other CAS quirk.
*NOTE:* This requires configuration changes to SynchWeb when being deployed. Do not merge this in before altering the configuration to provide a full path (including protocol) for `$sso_url` and adding `$sso_user_key` to the configuration file with the value `id`.
**Changes**:
- Added new configuration key, `$sso_user_key`, allowing deployer to set which one of the claims returned from the upstream auth service will be …
> LIMS-1355: Make OAuth2 support more generic

- client/src/js/modules/dc/views/reprocess.js
- client/src/js/modules/dc/views/reprocess2.js
- client/src/js/modules/mc/views/datacollections.js
- client/src/js/templates/dc/reprocess.html
- client/src/js/templates/dc/reprocess_dc.html
- client/src/js/templates/mc/datacollections.html
**JIRA ticket**: [LIMS-1383](https://jira.diamond.ac.uk/browse/LIMS-1383)
**JIRA ticket**: [LIMS-160](https://jira.diamond.ac.uk/browse/LIMS-160)
**JIRA ticket**: [LIMS-269](https://jira.diamond.ac.uk/browse/LIMS-269)
**Summary**:
Fix 3 tickets all related to reprocessing, fixing a bug and adding extra features. While we look at it, improve the GUI a bit.
**Changes**:
- Rename method elements to pipeline
- Add dropdown options for indexing method (uses xia2 keyword `method` hence renaming above)
- Rename Options button as Xia2 Options, grey out the options if a non-xia2 pipeline is chosen
- Add options for Xia2 keywords `cc_half`, `isigma`, `misigma`, `sigma_strong` and `method`
- Add a blank option for space group, otherwise P1 is the default
- Close Reprocessing dialog if the …
> LIMS-1383, LIMS-160, LIMS-269: Improve reprocessing

- api/src/Page/Download.php
**JIRA ticket**: [LIMS-1379](https://jira.diamond.ac.uk/browse/LIMS-1379)
**Summary**:
You can view heatmaps for grid scans on plates via the container view, eg https://ispyb.diamond.ac.uk/containers/cid/295986 well 3. But the snaked parameter is being ignored, so alternate rows of the grid scan are flipped from what they should be. This creates a stripy and mirrored effect.
**Changes**:
- Convert the SNAKED parameter to a number, as the javascript checks for `=== 1` (see [here](https://github.com/DiamondLightSource/SynchWeb/blob/master/client/src/js/modules/imaging/views/imageviewer.js#L1176))
- Could also have changed the javascript but this way is consistent with other fields.
**To test**:
- Go to /containers/cid/295986 well 3, check the stripy and mirrored effect is gone
> LIMS-1379: Grid scan heatmaps are not snaked correctly

- client/src/js/modules/types/mx/samples/mx-puck-samples-table.vue
- client/src/js/modules/types/mx/samples/sample-table-mixin.js
- client/src/js/modules/types/mx/shipment/views/mx-container-view.vue
**JIRA ticket**: [LIMS-700](https://jira.diamond.ac.uk/browse/LIMS-700)
**JIRA ticket**: [LIMS-691](https://jira.diamond.ac.uk/browse/LIMS-691)
**Github issue**: https://github.com/DiamondLightSource/SynchWeb/issues/552
**Summary**:
Improve the behaviour of the bulk editor.
**Changes**:
- Disable the bulk editor dropdown, textbox and submit button until the previous request has finished
- Shorten the debounce time on updating the samples to make the form respond quicker
- Add (green only) protein acronym to the fields that can be bulk edited
- Sort the fields alphabetically by name rather than "field name"
- Correct the message displayed when samples are updated successfully
- Add an error notification if samples are not updated
**To test**:
- Make a new puck with some samples in, save …
> LIMS-700: Allow bulk editing of protein

- api/src/Page/Sample.php
- client/src/js/modules/samples/components/sample-groups.vue
**JIRA ticket**: [LIMS-1371](https://jira.diamond.ac.uk/browse/LIMS-1371)
**JIRA ticket**: [LIMS-1372](https://jira.diamond.ac.uk/browse/LIMS-1372)
**Summary**:
The sample groups page needs 2 new features:
1. The ability to search sample groups by name
2. The ability to only show sample groups created by the current user
**Changes**:
- Record the current user in the new BLSampleGroup.ownerId field (when deployed)
- Add a new query parameters for filtering by current user, and adjust the WHERE part of the query to match
- Add a new query parameter for the search text, and adjust the WHERE part of the query to match
- Add a checkbox at the top left for filtering by the current user
- Add a search box to the top right for searching by name
- Put a watch (and debounce) on the search box to …
> LIMS-1371, LIMS-1372: Add search and 'My Groups' to Sample Groups page

- api/src/Downstream/Type/Shelxt.php
- client/src/js/modules/dc/views/downstream.js
- client/src/js/modules/dc/views/mapmodelview.js
- client/src/js/modules/dc/views/shelxt.js
- client/src/js/modules/types/sm/dc/views/apstatusitem.js
- client/src/js/templates/dc/dc_shelxt.html
**JIRA ticket**: [LIMS-1432](https://jira.diamond.ac.uk/browse/LIMS-1432)
**Summary**:
Add support for shelxt downstream results. 
**Changes**:
- add a Shelxt extension of `DownStreamPlugin`
- add the mapping to this plugin
- add a `dc_shelxt.html`
- add the accompanying javascript
(loosely based on dimple but with several differences)
**To test**:
- head to https://ispyb.diamond.ac.uk/dc/visit/cm37266-1/id/13371207
- confirm a list of solutions appears
- confirm a 2d molecular view appears
- confirm that map/model viewer leads to a 3d render of a molecule
I will add a screenshot once the restore database synch is run later today.
> LIMS-1432: Add shelxt downstream view

- api/assets/emails/html/dewar-dispatch-lite.html
- api/src/Controllers/AuthenticationController.php
- api/src/Page/Shipment.php
- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/templates/shipment/dispatch.html
**JIRA ticket**: [LIMS-1396](https://jira.diamond.ac.uk/browse/LIMS-1396)
**Summary**:
Currently, when a user is redirected to the shipping service, Synchweb sends the email and marks the dewar as 'dispatch-requested' instantly, as it doesn't know if/when they have completed the form.
The shipping service now accepts a callback URL, so we can send that in and it will POST to the address with some data about the completed shipment.
**Changes**:
- Create new non-authenticated endpoint at /api/shipment/dewars/confirmdispatch/did/{dewarid}/token/{token}
- Create pseudo-random token and store in Dewar.extra column as JSON
- Pass callback URL including token to shipping service
- Don't update dewar status and history when first redirecting to shipping service
- Add function at new endpoint to …
> LIMS-1396: Use shipping service callback URL to only send emails once shipment is booked

- api/config_sample.php
- api/scripts/mtz2map.sh
- api/src/Downstream/DownstreamProcessing.php
**JIRA ticket**: [LIMS-1435](https://jira.diamond.ac.uk/browse/LIMS-1435)
**Summary**:
CCP4 has been updated, so the old path no longer works, meaning dimple maps show no electron density. The path shouldn't be hard-coded though.
**Changes**:
- Add `$ccp4_location` config variable
- Pass that variable into the `mtz2map.sh` script
**To test**:
- Add the config variable with `$ccp4_location = '/dls_sw/apps/ccp4/latest/ccp4-9';`
- Open a data collection with a dimple result, eg /dc/visit/nt37104-106/id/14642946
- Click on the Downstream Processing bar to show the dimple results, then click "Map / Model Viewer"
- Check the electron density is shown in blue in the centre of the image
- Check you can move/rotate the image
> LIMS-1435: Put CCP4 location into config variable

- api/src/Page/Download.php
- client/src/js/templates/dc/dc_autoproc.html
**JIRA ticket**: [LIMS-14](https://jira.diamond.ac.uk/browse/LIMS-14)
**Summary**:
Currently it takes 2 clicks to see the processing log, via the "Logs & Files" button. We should add a direct link. We can use the importanceRank field to find the most important file of type 'log'.
**Changes**:
- Add a new button to successful autoprocessing jobs saying "Processing Log".
- Download the first attachment of type 'log' and importanceRank '1'.
- Sort other attachments by importanceRank first, then alphabetically, instead of random.
**To test**:
- Go to a visit, look for a successful fast_dp run, click the "Processing Log" button, check it displays the fast_dp-report.html file
- Repeat the check for other processing pipelines
- Check no button appears for unsuccessful processing jobs
- Check no …
> LIMS-14: Show a direct link to the autoprocessing log

- client/src/js/modules/dc/views/distl.js
- client/src/js/modules/dc/views/reprocess2.js
**JIRA ticket**: [LIMS-1422](https://jira.diamond.ac.uk/browse/LIMS-1422)
**Summary**:
The reprocessing dialog tries to help by autofilling the end value, but sometimes that concats a 1 to the start, sometimes adds a 1 to the number resulting in impossible parameters.
As discussed on Slack at https://diamondlightsource.slack.com/archives/CKS8PRR0Q/p1722949258543509
**Changes**:
- Use Math.round instead of Math.floor or Math.ceil to ensure the image numbers are not affected randomly
- Only autocorrect the start/end image numbers if something has been filled in, rather than putting something in before the user has a chance
- Make the "submitted successfully" message be in green not red.
**To test**:
First, check the current behaviour.
- Open …
> LIMS-1422: Reprocessing dialog edits the end value unpredictably

- client/src/js/templates/shipment/containerli.html
**JIRA ticket**: [LIMS-1424](https://jira.diamond.ac.uk/browse/LIMS-1424)
**Summary**:
We should display the visit associated with each container (if one exists).
**Changes**:
- Add visit to each container in the list
- Replace tabs with spaces
**To test**:
- Go to a UDC shipment, eg /shipments/sid/65097, check each container shows the visit after the number of samples eg `CPS5392 (16 samples) (mx34566-21)`
- Go to a non-UDC shipment, eg /shipments/sid/61956, check each container shows only the number of samples eg `CPS5433 (16 samples)`
- Go to a VMXi shipment, eg /shipments/sid/64374, check each container shows the number of samples, the requested and actual imager used, and the visit, eg `7013_magic (192 samples) [Req: VMXi 20c] [Img: VMXi 20c] (nt37104-99)`
> LIMS-1424: Show visit for each container if set

- client/src/js/modules/shipment/views/plate.js
**JIRA ticket**: [LIMS-1425](https://jira.diamond.ac.uk/browse/LIMS-1425)
**Summary**:
When ranking samples on a plate by autoprocessing (AP) resolution or completeness, any samples with failed autoprocessing are currently displayed as yellow. This is confusing, they should just be grey, as for samples without any data.
**Changes**:
- Dont show any samples as 'yellow', just use `#dfdfdf` (grey) for all.
**To test**:
- Go to a plate eg /containers/cid/309483, change the "Display" radio button to "Data Status"
- Take a note of which wells are shown in blue, this means the autoprocessing failed, and which are green, this means the autoprocessing succeeded
- Tick the "Rank By" checkbox, and check the blue wells turn grey, not yellow
- Check the green wells turn red/orange/green as before
> LIMS-1425: Show samples with no processing as grey

- client/src/js/modules/imaging/views/queuecontainer.js
- client/src/js/templates/imaging/queuecontainer.html
**JIRA ticket**: [LIMS-1430](https://jira.diamond.ac.uk/browse/LIMS-1430)
**Summary**:
The (VMXi) "Prepare for data collection" page needs a number of bugfixes and improvements.
**Changes**:
- Allow queueing the container even if all data collections are currently hidden due to filters
- Show/hide relevant controls so that no refresh is needed after queueing or unqueueing the container. This exposed a number of bugs:
- Fix bug where couldn't remove sample that wasn't currently displayed in the Available Samples section
- Fix bug where unqueueing container removed all data collections until refresh
- Fix bug where filtering on the available samples affected the filtering of data collections
- Fix bug where invalid data collections could be queued if they were filtered
- Show number of …
> LIMS-1430: Fix bugs on prepare for data collection page

- api/src/Page/DC.php
**JIRA ticket**: [LIMS-1390](https://jira.diamond.ac.uk/browse/LIMS-1390)
**Summary**:
Viewing a data collection group (or a group linked by a processing job) and then using the search box gives a server error.
**Changes**:
- Remove unnecessary `lower()` and `concat()` calls as MariaDB is case-insensitive and you can pass many arguments to a single `concat()`
- Add to `$where2`, `$where3` and `$where4` rather than replacing them, as the `$args` array has already been populated expecting them to have several extra values
**To test**:
- Go to a data collection group, eg /dc/visit/mx34566-20/dcg/12631761 and search for just one of the data collections, eg `16_1`, and check only one data collection is shown
- Go to a data processing group eg /dc/pjid/24527370, and search for just one of the …
>  LIMS-1390: Fix searching of data collection groups

- api/src/Page/Proposal.php
- client/src/js/modules/calendar/views/components/calendar-day-events.vue
- client/src/js/modules/visits/views/visit_list.vue
**JIRA ticket**: [LIMS-1286](https://jira.diamond.ac.uk/browse/LIMS-1286)
**Summary**:
Users (and staff) often don't realise their ERA has not been validated as the visit approaches, so we should display it more prominently.
**Changes**:
- Get risk rating for each session from ISPyB (it should be synced to UAS)
- Display a green/yellow/red circle for low/medium/high risk sessions, and a black circle if the ERA has not been approved yet, on both the calendar page and also the visits list page
- Display a tooltip to explain the circle if a user hovers over it
**To test**:
- Go to an MX proposal (eg /dc/visit/mx37045-1) and then click the calendar link at the top left. As staff you should see lots of visits for the mx village, check a coloured circle appears next to each, and a tooltip …
> LIMS-1286: Show ERA status on calendar and visits list

- api/composer.json
- api/src/Page.php
- api/src/Page/Process.php
- api/src/Queue.php
**JIRA ticket**: [LIMS-1354](https://jira.diamond.ac.uk/browse/LIMS-1354)
**Summary**:
SynchWeb sends messages to ActiveMQ to trigger MX reprocessing and AlphaFold model prediction jobs. A single ActiveMQ server proved unreliable so a RabbitMQ cluster was established in early 2021. An ActiveMQ to RabbitMQ bridge service was implemented as a temporary solution while applications migrated to RabbitMQ. The failure of the bridge service in mid-2024 highlighted the need to update SynchWeb to send messages direct to RabbitMQ.
SynchWeb uses the Stomp (Simple Text Oriented Message Protocol) PHP client to send messages to ActiveMQ. This ticket updates SynchWeb to use an AMQP (Advanced Message Queuing Protocol) client to send messages to RabbitMQ. The php-amqplib client is the de facto standard and …
> LIMS-1354: Migrate from ActiveMQ to RabbitMQ

- api/src/Page/Processing.php
**JIRA ticket**: [LIMS-1454](https://jira.diamond.ac.uk/browse/LIMS-1454)
**Summary**:
Manually re-run Dimple jobs do not show up as ticks or crosses, although the results are there if you expand.
**Changes**:
- Remove the requirement to only show 'automatic' downstream jobs
**To test**:
- Set the config variable:
```
$downstream_filter = array('big_ep', 'ep_predict', 'mr_predict');
```
- Go to a data collection where dimple has been re-run manually, eg /dc/visit/nt32304-39/id/15055911
- Check the number of ticks and crosses in the Downstream Processing bar matches the number of results that appear when you expand the bar. For the example above, there should be 
- Dimple: 6 x tick, 4 x cross
- MrBUMP: 7 x tick, 1 x cross
> LIMS-1454: Show non-automatic downstream processing

- api/src/Page/DC.php
**JIRA ticket**: [LIMS-1462](https://jira.diamond.ac.uk/browse/LIMS-1462)
**Summary**:
Currently the screening tab only shows data collections with a non-zero overlap or the experiment type of 'Screening'. We should include the experiment type 'Characterisation'.
**Changes**:
- If the "Screenings" tab is selected, show data collections of type "Characterization" as well
- If the "Full Collections" tab is selected,, hide data collections of type "Characterization" as well
- If the "Auto Integrated" tab is selected, data collections of type "Screening" and "Characterization" as well (have checked with I19)
- If the "Phasing" tab is selected, data collections of type "Screening" and "Characterization" as well
**To test**:
- Go to an MX data collection of type "Characterization" (eg …
> LIMS-1462: Show characterizations on Screenings tab

- api/src/Page/Contact.php
- client/src/js/models/labcontact.js
- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/modules/shipment/views/dispatch.js
**JIRA ticket**: [LIMS-1467](https://jira.diamond.ac.uk/browse/LIMS-1467)
**Summary**:
Some people have spaces in their names, both given and family. This should be allowed in Synchweb.
**Changes**:
- Update regex for familyname and givenname args in PHP
- Update model for creating/editing lab contacts and dewar dispatch form
- Ensure visitRequired matches dispatchDetailsRequired
**To test**:
- Set `$use_shipping_service_redirect = True;` in config.php, use sample-shipping-test as the shipping service.
- Create a lab contact with spaces in given and family name, check the GUI gives no errors, and the form submits ok
- Edit the lab contact given and family name (still with spaces), check the form submits ok and edits persist
- Add a shipment with your new lab contact as the outgoing and …
> LIMS-1467: Allow lab contacts to have spaces in their names

- client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
- client/src/js/modules/types/mx/shipment/views/mx-container-view.vue
**JIRA ticket**: [LIMS-1489](https://jira.diamond.ac.uk/browse/LIMS-1489)
**JIRA ticket**: [LIMS-1506](https://jira.diamond.ac.uk/browse/LIMS-1506)
**Summary**:
If a shipment has been uploaded as a CSV (or created by GDA), it doesn't have a safety level. https://github.com/DiamondLightSource/SynchWeb/pull/827 disabled the ability to queue containers in such shipments, but the message is not helpful, as it says "Cannot queue containers in shipments". We should make the message clearer.
Also, as already editing this file, I added some text to remind users to add PDB and/or sequence information to their proteins.
**Changes**:
- If adding/editing a container in a shipment with a null safety level, display a message advising users to set the shipment safety level
- When a new container is …
> LIMS-1489: Update message when trying to queue containers in uploaded shipments

- api/src/Page/Download.php
**JIRA ticket**: [LIMS-1498](https://jira.diamond.ac.uk/browse/LIMS-1498)
**Summary**:
A user emailed pointing out that the Archive download of an autoprocessing run gives a pretty abstract filename of `<datacollectionid>_<pipeline>.zip`, eg `106290598_xia2dials.zip`
**Changes**:
- Added the image prefix and data collection number, so we now have `<datacollectionid>_<imageprefix>_<datacolletionnumber>_<pipeline>.zip`, eg `106290598_sethau_8_42_xia2dials.zip`
**To test**:
- Go to a data collection with successful autoprocessing eg /dc/visit/cm37235-4/id/15531187
- Go to a processing pipeline and click on the "Archive" button, check the download has the image prefix and data collection number in it.
> LIMS-1498: Change name of processed data archive

- api/src/Page/Download.php
- client/src/js/modules/dc/views/summary.js
- client/src/js/modules/summary/views/summary.vue
**JIRA ticket**: [LIMS-1469](https://jira.diamond.ac.uk/browse/LIMS-1469)
**Summary**:
On the (old) summary page, there is a button marked "Download MTZ file", but it just gives a 404 error. It appears the API endpoint was removed in 2b7850223e26c646dcd999a920ae2cd0a2a662f6 (see changes to Download.php).
**Changes**:
- Change link from /download/id/<%-DCID%>/aid/<%-AID%> to /download/ap/archive/<%-AID%> to match the new endpoint
- Remove old "delete me" comment 
**To test**:
- Go to a summary page for a visit eg /dc/summary/visit/cm37235-4
- Check the tooltip for the download button now says "Download autoprocessing archive"
- Check clicking the button downloads a zip of autoprocessing files
> LIMS-1469: Fix download button on old summary page

- api/src/Page/DC.php
**JIRA ticket**: [LIMS-1463](https://jira.diamond.ac.uk/browse/LIMS-1463)
**Summary**:
When Hyperion adds a Mesh3D experiment to ISPyB, Synchweb initially displays it as a rotational data collection, only updating to a grid scan style after a refresh. We should detect that it is a grid scan immediately.
**Changes**:
- Treat the experiment type Mesh3d (ie hyperion grid scans) the same as Mesh (ie GDA grid scans)
- Force both to display as grid scans, irrespective of the axis range and number of images
**To test**:
- View a stopped Hyperion grid scan (eg /dc/visit/cm37235-4/dcg/13099843) check it displays in the style of a grid scan, ie space for a diffraction image and space for a crystal snapshot, no space for a graph of spot counts
- View a completed Hyperion grid scan (eg …
> LIMS-1463: Always display Mesh3D data collections as grid scans

- api/src/Page/DC.php
- client/src/js/templates/dc/dc.html
- client/src/js/templates/dc/edge.html
- client/src/js/templates/dc/grid.html
- client/src/js/templates/dc/mca.html
**JIRA ticket**: [LIMS-1515](https://jira.diamond.ac.uk/browse/LIMS-1515)
**Summary**:
Currently only wavelength is displayed in Synchweb for most data collection types, we should show energy in eV as well.
**Changes**:
- Define the eV/A conversion factor (value from https://en.wikipedia.org/wiki/Electronvolt#Wavelength)
- Add return values to the `_data_collections` function for the `energy` in eV, and also the `wavelength` in A for MCA spectra and peak (`wpk`) and inflection (`win`) wavelengths for edge scans
- Add labels to a few more columns, these are redundant as the union will use the labels from the first select statement, but help to identify where values are coming from
- Return energies to 0 decimal places and wavelengths to 4 decimal places, except for edge scan results which …
> LIMS-1515: Add energy value to data collections

- api/src/Page/Sample.php
- client/src/js/modules/samples/views/pdbs.js
**JIRA ticket**: [LIMS-261](https://jira.diamond.ac.uk/browse/LIMS-261)
**Summary**:
We store uploaded PDB files (and alphafold generated PDB files) in ISPyB, we should allow users to download them again. (We also store 4-letter PDB codes)
**Changes**:
- Generate buttons on each PDB after rendering, so that the code etc is known
- Add a button with link to EBI if the type is 'code'
- Otherwise, add download button
- Add new endpoint to download contents field
**To test**:
- Go to a protein with PDB's associated with it, eg /proteins/pid/422017
- Check the link button next to a 'code' type PDB goes to the correct entry on ebi.ac.uk
- Check the download button on a 'file' type PDB downloads a file with the correct name and contents (should be plain text)
- Check the delete button removes …
> LIMS-261: Allow download of PDB files

- api/scripts/mtz2map.sh
**JIRA ticket**: [LIMS-1529](https://jira.diamond.ac.uk/browse/LIMS-1529)
**Summary**:
https://github.com/DiamondLightSource/SynchWeb/pull/821 introduced a bug where the CCP4 path was set correctly for Dimple and MrBump, but not for Fast EP jobs, so the mtz2map conversion would fail and the map would not load.
**Changes**:
- Move the setting of `$CCP4_MASTER` etc out of the if clause
**To test**:
- EDIT: Make sure to set `$ccp4_location = '/dls_sw/apps/ccp4/latest/ccp4-9';` in your config.php file
- Go to a data collection with Dimple, MrBump and Fast EP results eg /dc/visit/cm37235-4/id/15531187
- Go to each downstream pipeline in turn and click "Map/Model Viewer", check that some electron density appears and no errors occur.
> LIMS-1529: Fix fast ep model viewer

- api/src/Page/Proposal.php
- client/src/js/modules/visits/views/visit_list.vue
**JIRA ticket**: [LIMS-1514](https://jira.diamond.ac.uk/browse/LIMS-1514)
**Summary**:
The list of visits for a proposal is not sortable.
**Changes**:
- Combine the data collection count into the main db query so that it can be sorted on
- Remove the need for an enter press on searching for a visit number, but add a debounce
- Make column headers actually be buttons so that the cursor becomes a pointer
- Re-fetch the data with a sort parameter if a header is clicked (apart from "Dewars")
- Re-fetch the data in the opposite direction if the same header is clicked again
- Don't add a search parameter if the search box is empty
- Allow searching by beamline name
**To test**:
- Open a proposal with a bunch of visits eg mx34263, and go to the /visits page
- Check you can sort by each header, …
> LIMS-1514: Allow sorting of visit list

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-753](https://jira.diamond.ac.uk/browse/LIMS-753)
**Summary**:
We record every time a dewar is topped up with LN2, but in the `Dewar.comments` field. In order to let the users know what has happened to their dewar, we should record it in the `DewarTransportHistory` table.
Once this code is live, I can edit the [Dewar Logistics](https://github.com/DiamondLightSource/flask-ispyb-logistics/) code to use this endpoint instead.
**Changes**:
- Allow usage of the `shipments/dewars/history` endpoint with a `STATUS` instead of a `LOCATION`.
- Update only `DewarTransportHistory` (and not `Dewar`) if only `STATUS` given
- Only send emails if the location has changed (and other criteria met)
**To test**:
- Edit the `$bcr` variable in config.php to include the IP of a machine you …
> LIMS-753: Allow LN2 topups as part of dewar history

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-1500](https://jira.diamond.ac.uk/browse/LIMS-1500)
**Summary**:
Local contacts no longer get dispatch request emails, but I19 staff would like to receive emails for i19 dewars. So we can implement a set of regex patterns to decide who gets an email based on the dewar barcode.
**Changes**:
- Introduce a new config variable called `$dispatch_email_regex`, of an array of email addresses and regex patterns.
- Add each email address to the list of recipients if the pattern matches the dewar barcode.
**To test**:
- Check your Synchweb server can log emails that should be sent (see https://confluence.diamond.ac.uk/display/~ndg63276/Synchweb+Dev#SynchwebDev-Sendingemails)
- Set these config variables (dummy email addresses):
```
$dispatch_email = …
```
> LIMS-1500: Set the dispatch request email recipients based on the dewar barcode

- api/src/Controllers/UserController.php
- api/src/Model/Services/UserData.php
- api/tests/Controllers/UserControllerTest.php
**JIRA ticket**: [LIMS-1002](https://jira.diamond.ac.uk/browse/LIMS-1002)
**Summary**:
When updating a user to have a laboratory when previously they didn't have one, although the laboratory is created, an error is logged.
**Changes**:
- Make the updateLaboratory function return the laboratoryId instead of nothing
- Use that laboratoryId to get the rest of the info to output to the user
- Remove unused code getting the laboratory earlier
**To test**:
- Find a personId that has no laboratoryId, eg personId 13000, login gnj59924
- Login to a synchweb dev instance as this person, and get the authentication headers
- Open a python terminal and do:
```
>>> import requests
>>> headers = {"Authorization": "Bearer eyJ..."} # using headers from Synchweb
>>> r = …
```
> LIMS-1002: Fix error when creating new laboratory

- api/src/Page/Proposal.php
- api/src/UAS.php
**JIRA ticket**: [LIMS-1302](https://jira.diamond.ac.uk/browse/LIMS-1302)
**Summary**:
UAS often fails to find sessions it has created in the last few minutes, so when loading the second UDC puck from a shipment, Synchweb doesnt assign the session id to the container, even though it knows the session id and so it must exist.
**Changes**:
- Treat a 404 error the same as a success
- Only log errors from UAS, not only successes (UAS.php line 76)
- Fix indentation to use spaces not tabs
**To test**:
- Hard to test without UAS. Currently UAS has a workaround in so it doesn't return a 404, but that will probably be removed soon.
- I suggest (if approved and if UAS take out their workaround) we roll out to staging, then point the beamline to staging temporarily. We can load multiple pucks from …
> LIMS-1302 - add visit to container even if UAS fails

- api/config_sample.php
- api/src/Page.php
**JIRA ticket**: [LIMS-1487](https://jira.diamond.ac.uk/browse/LIMS-1487)
**Summary**:
Automatic triggering of alphafold when a sequence is added was broken by the switch to rabbitmq (https://github.com/DiamondLightSource/SynchWeb/pull/826)
**Changes**:
- Use rabbitmq parameters instead of activemq ones to submit jobs
- Put the updated global variable names in the sample config
**To test**:
- Put the rabbitmq variables into the config (get from prod or from Mark)
- Find a protein in a cm proposal with no current sequence (eg /proteins/pid/604455)
- Add a suitable sequence (eg copy from /proteins/pid/597094)
- Check in [graylog](https://graylog.diamond.ac.uk/streams/6579e104ca674e7c2a7c6bad/search?q=alphafold&rangetype=relative&streams=6579e104ca674e7c2a7c6bad&from=86400) if alphafold has …
> LIMS-1487: Fix alphafold triggering

- api/src/Page/Imaging.php
- api/src/Page/Sample.php
- client/src/css/partials/_imaging.scss
- client/src/js/modules/imaging/views/queuecontainer.js
- client/src/js/modules/shipment/components/container-queue-wrapper.vue
- client/src/js/modules/shipment/router.js
- client/src/js/modules/shipment/routes.js
- client/src/js/modules/shipment/views/plate.js
- client/src/js/templates/imaging/queuecontainer.html
- client/src/js/views/search.js
**JIRA ticket**: [LIMS-128](https://jira.diamond.ac.uk/browse/LIMS-128)
**Summary**:
When queuing subsamples in a plate for data collection, it would be useful to show a view of the plate, rather than just a list of (possibly 1000s of) subsamples.
**Changes**:
- Move filtering by point/region/manual/auto to the server
- Display a plate view on the "Prepare For Data Collection" page (/containers/queue/<containerid>)
- Add a search bar to the same page
- Synchronize the search bar with clicking on the plate wells
- Load the inspection image when you click on the wells
- Fix site-wide bug where clearing the search box using the x (Chrome-only?) doesn't clear the search parameters
**To test**:
- Go to a VMXi proposal, eg nt37104, navigate to the /containers page, click a plate that is 'in …
> LIMS-128: Add plate view to queue page

- api/src/Page/Shipment.php
- client/src/js/modules/shipment/views/dispatch.js
**JIRA ticket**: [LIMS-1066](https://jira.diamond.ac.uk/browse/LIMS-1066)
**Summary**:
When you request a dewar dispatch, the visit is automatically selected if it is associated with the dewar. But for UDC visits, the visit is associated with the container, so the visit is not automatically selected. This PR is to fix that.
**Changes**:
- Outer join Container to BLSession, and get a UDC visit if one exists
- Auto-select that visit in the dropdown if a non-UDC visit is not found
**To test**:
- Turn off the shipping service, or just use examples who haven't selected 'Use facility account'
- Go to a UDC shipment, eg /shipments/sid/67174, click "Dispatch", check that the visit is selected in the dispatch form
- Go to a non-UDC shipment, eg /shipments/sid/66694, click "Dispatch", check that …
> LIMS-1066: Autofill UDC visit on dispatch form

- api/src/Page/Imaging.php
- api/src/Page/Sample.php
- client/src/css/partials/_imaging.scss
- client/src/js/modules/imaging/views/queuecontainer.js
- client/src/js/modules/shipment/components/container-queue-wrapper.vue
- client/src/js/modules/shipment/router.js
- client/src/js/modules/shipment/routes.js
- client/src/js/modules/shipment/views/plate.js
- client/src/js/templates/imaging/queuecontainer.html
- client/src/js/views/search.js
Reverts DiamondLightSource/SynchWeb#839
> Revert "LIMS-128: Add plate view to queue page"

- client/src/js/modules/shipment/views/dewarregistry.js
**Summary**:
Small extension of LIMS-1366, where registration messages are green instead of red, to reduce confusion.
**Changes**:
- Make registration success messages green instead of red
**To test**:
- Log in as a staff member, go to proposal mx34263.
- Go to /dewars/registry 
- Add a new dewar (eg.: DLS-MX-0123)
- Check if the success message is green
- Add the newly created dewar to a proposal
- Check if that message is also green
> [LIMS-1366] Make dewar registration success messages green

- api/src/Page/Contact.php
- client/src/js/modules/contact/views/viewcontact.js
- client/src/js/templates/contact/contactview.html
**JIRA ticket**: [LIMS-1590](https://jira.diamond.ac.uk/browse/LIMS-1590)
**Summary**:
The synchronisation scripts from UAS to ISPyB will overwrite any changes to Lab Contact names where the `login` or `externalId` fields are set, so we should disable changing them.
**Changes**:
- Get and display the current value for `login`, or use "External" if the `externalId` is set.
- Don't set the name fields to be editables if the `login` or `externalId` is not null
- Fix some whitespace and indentation
**To test**:
- Go to proposal mx23694, then go to /contacts/cid/11278, check the login is displayed, and the given name and family name fields are not editable
- Go to /contacts/cid/5988, check the login field is blank, and the given name and family name fields are editable
- Run this command …
> LIMS-1590: Dont allow name editing for lab contacts when login is set

- client/src/js/modules/samples/views/view.js
- client/src/js/templates/samples/sample.html
**JIRA ticket**: [LIMS-1558](https://jira.diamond.ac.uk/browse/LIMS-1558)
**Summary**:
https://github.com/DiamondLightSource/SynchWeb/pull/793 allowed SMILES codes to be added to samples in plates. This PR is to add that functionality to any sample.
**Changes**:
- Add SMILES entry box to sample view page
**To test**:
- Go to a visit, click on the sample associated with a data collection to go to eg /samples/sid/5461086
- Check the SMILES code box appears.
- Edit the SMILES code, using weird symbols eg .:%=#$@+-[]()/\, check it remains after a refresh
- Try symbols that are not allowed, eg £, check it is refused by the GUI
> LIMS-1558: Add functionality for SMILES code for any sample

- api/src/Controllers/AuthenticationController.php
- api/src/Page/Shipment.php
- client/src/js/templates/shipment/shipment.html
**JIRA ticket**: [LIMS-1490](https://jira.diamond.ac.uk/browse/LIMS-1490)
**Summary**:
If we are to fully use the shipping service for incoming dewars, we need to use the callback URL function to allow setting of the dewar status and tracking number, once the shipping service booking is complete.
**Changes**:
- Add a new (non-authenticated) endpoint (`/api/shipment/dewars/confirmpickup/sid/<shippingid>/token/<token>`) for the shipping service to hit when an incoming dewar has been booked
- Update the shipping status & dewar status to `awb created` or `pickup booked` as necessary
- Update the dewar tracking number
- Add lines to the DewarTransportHistory table
- Use an md5 token to authenticate the new endpoint
- Hide irrelevant fields on the Shipment page if the shipping service has been …
> LIMS-1490: Use callback URL for incoming dewars via shipping service

- client/src/js/modules/dc/views/reprocess2.js
- client/src/js/modules/mc/views/datacollections.js
- client/src/js/templates/dc/reprocess.html
- client/src/js/templates/dc/reprocess_dc.html
- client/src/js/templates/mc/datacollections.html
**JIRA ticket**: [LIMS-1537](https://jira.diamond.ac.uk/browse/LIMS-1537)
**Summary**:
Add the d_max option and the absorption level option (for xia2 only) for reprocessing jobs. Also fix a bug in space groups when 'process individually' is ticked.
**Changes**:
- Add a low res input next to the current high res input
- Add a dropdown for absorption level with high/medium/low options, default is left blank
- Add the above changes to standard single crystal reprocessing and mutli crystal reprocessing
- Fix the identifier for the space group box to an input (rather than select) for when 'process individually' is ticked, so that the space group can be populated from the 'Use AP Cell' button, and the requested space group is passed on to the reprocessing job
**To test**:
- Change your config …
> LIMS-1537: Add more options to reprocessing

- client/src/js/modules/shipment/models/dispatch.js
- client/src/js/modules/shipment/views/dispatch.js
**JIRA ticket**: [LIMS-1466](https://jira.diamond.ac.uk/browse/LIMS-1466)
**Summary**:
The dispatch request form has quite strict validation, but little of it is used (or even displayed) if the shipping service will be used. This has led to problems where a hidden field fails validation and the user doesn't know how to fix the problem. We should disable validation if the shipping service is going to be used.
**Changes**:
- Move validation patterns out of model file and into functions within view file
- Tidy some whitespace
**To test**:
- Enable `$use_shipping_service` and `$use_shipping_service_redirect` in config
- Go to a test shipment (eg /shipments/sid/63609) and click "Dispatch"
- Change the country to eg Aruba to show the full form
- Add illegal characters to each field, check that …
> LIMS-1466: Disable dispatch form validation when using the shipping service

- api/src/Page/Image.php
**JIRA ticket**: [LIMS-1621](https://jira.diamond.ac.uk/browse/LIMS-1621)
**Summary**:
If the webcams require a username and password to view, this can be added to the address in the config file, but that will be ignored without telling curl to use it.
**Changes**:
- Allow curl to use any suitable auth method
**To test**:
- Get the i19 webcam username and password from Mark or Sarah Barnett
- Update the `$webcams` array in the config, to set (with real credentials)
```
'i03' => array('172.23.103.177', '172.23.103.176'),
'i19-1' => array('user:pass@i19-webcam10.diamond.ac.uk', 'user:pass@i19-webcam11.diamond.ac.uk'),
'i19-2' => array('user:pass@i19-webcam8.diamond.ac.uk', 'user:pass@i19-webcam9.diamond.ac.uk'),
```
- Log in to proposal cm40638, then go to /status/bl/i19-1, check the …
> LIMS-1621: Support webcam auth

- api/src/Page/Shipment.php
- client/src/js/models/shipment.js
- client/src/js/modules/shipment/views/shipment.js
- client/src/js/modules/shipment/views/shipmentadd.js
- client/src/js/templates/shipment/shipment.html
- client/src/js/templates/shipment/shipmentadd.html
**JIRA ticket**: [LIMS-1287](https://jira.diamond.ac.uk/browse/LIMS-1287)
**Summary**:
Users often fill out the scheduling question incorrectly when making a shipment, or not at all. This PR is to try and make it clearer for them and us.
**Changes**:
- Change the Scheduling question to a compulsory radio button, storing the value in the db (rather than just Yes/No)
- Only show the session dropdown if they say they have a scheduled session and a session exists
- Split UDC and Imager into separate answers
- If they ask for a session, ask if they require a long wavelength beamline (ie I23), and in that case dont ask further scheduling questions
- Add a 'Something else' answer with the comments field then compulsory
- Display the full scheduling and long wavelength answers on the View …
> LIMS-1287: Improve workflow for responsive scheduling

- client/src/js/modules/shipment/views/containerplate.js
- client/src/js/templates/shipment/containerplateimage.html
**JIRA ticket**: [LIMS-1064](https://jira.diamond.ac.uk/browse/LIMS-1064)
**Summary**:
In https://github.com/DiamondLightSource/SynchWeb/pull/621 we hard-coded the UI to say only CHIMP auto-scores were available. There are 275 plates in the database with MARCO scores, and of course other schemas may be used in future, So we should show a dropdown if mulitple schema results return, but just a span if only one schema results return.
**Changes**:
- Re-enable the schema dropdown, as well as an empty span
- Show or hide them according to the number of schemas returned
**To test**:
- Go to a container inspection with both MARCO and CHIMP scores, eg /containers/cid/177952, inspection on 9th Dec 2020, check a dropdown appears to choose between MARCO and CHIMP scores
- Switch to an older …
> LIMS-1064: Display dropdown or span depending on number of schema options

- client/package-lock.json
- client/package.json
**JIRA ticket**: [LIMS-1652](https://jira.diamond.ac.uk/browse/LIMS-1652)
**Summary**:
Non-MX pucks are not displayed correctly after updating underscore. This reverts to the previous underscore version.
**Changes**:
- Revert underscore version
**To test**:
- Go to /containers/cid/322576, ensure puck is displayed
> LIMS-1652: Revert underscore to 1.8.3

- client/src/js/modules/shipment/views/dispatch.js
**JIRA ticket**: [LIMS-1646](https://jira.diamond.ac.uk/browse/LIMS-1646)
**Summary**:
European users should be allowed to request dewar dispatch via Synchweb, an request to use our account. This won't go via the shipping service so it will be reviewed anyway. At the moment, the "Use Facility Account" button is only shown to UK users, we should enable it for European users as well.
**Changes**:
- Show button if EU as well as if UK
**To test**:
- Set this in config.php:
```
$facility_courier_countries_nde = array('Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic, The', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland, Republic Of', 'Italy', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands, The', …
```
> LIMS-1646: Show 'Use Facility Account' button for EU dewar dispatch

- client/src/js/modules/dc/views/gridplot.js
**JIRA ticket**: [LIMS-1496](https://jira.diamond.ac.uk/browse/LIMS-1496)
**Summary**:
When viewing vertical grid scans in Safari, the image is offset and so the heatmap doesn't align with the drawn grid. This seems to be because Safari doesn't like negative numbers being passed to drawImage. To test this, go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_canvas_drawimage and replace the drawImage line with
```
ctx.drawImage(img, -250, 0, 500, 300, 0, 0, 250, 300);
```
On Firefox or Chrome, you see a squashed image in the right half of the frame. On Safari, you see the normal image.
It turns out Safari doesn't like negative values for the second parameter (sx), so it ignores them and uses 0 instead. It also doesn't like if sx + swidth is larger than the source image width, …
> LIMS-1496: Fix offset grid scan heatmaps in Safari

- api/config_sample.php
- api/index.php
- api/src/Page/Processing.php
- client/src/css/partials/_utility.scss
- client/src/js/modules/dc/views/attachments.js
- client/src/js/modules/dc/views/autointegration.js
- client/src/js/modules/dc/views/autoprocattachments.js
- client/src/js/templates/dc/cloudupload.html
- client/src/js/views/cloudupload.js
**JIRA ticket**: [LIMS-1389](https://jira.diamond.ac.uk/browse/LIMS-1389)
**Summary**:
We should allow users to directly send processed files (eg mtz, hkl) to CCP4 cloud, without them needing to download/upload. We can add an 'Upload to CCP4 Cloud' button to the 'attached files' dialog.
**Changes**:
- Add a 'CCP4 Cloud' button to the attached files dialog, for both data processing jobs and also data collections themselves (for future work with mmcif files)
- Add a config variable to alter upload path, also allows the button to be removed
- Add a link to help pages on CCP4 cloud (page does not yet exist but Eugene says something will soon)
- Add ability to store ccp4 username/cloudrun id in a cookie
- Return to attached files dialog after successful upload
**To test**:
- Set config …
> LIMS-1389 - Add upload to ccp4 cloud button

- api/src/Page/Sample.php
- client/src/css/partials/_imaging.scss
- client/src/js/modules/imaging/views/queuecontainer.js
- client/src/js/modules/shipment/views/plate.js
- client/src/js/templates/imaging/queuecontainer.html
**JIRA ticket**: [LIMS-128](https://jira.diamond.ac.uk/browse/LIMS-128)
**Summary**:
When queuing samples in a plate for data collection, it would be useful to show a view of the plate, rather than just a list of (possibly 1000s of) samples.
First attempt at this was https://github.com/DiamondLightSource/SynchWeb/pull/839 but had to be reverted.
**Changes**:
- Display a plate view on the "Prepare For Data Collection" page (/containers/queue/)
- Filter the list when you click on a well
- Load the inspection image when you click on a well
- Ensure 'Add all to queue' only adds from the current well (otherwise you get an error as the server queues samples the client isn't showing)
**To test**:
- Go to a proposal with plates (eg nt37104) and then go to a plate (eg /containers/cid/317254)
- …
> LIMS-128: Add plate view to queue container page

- client/src/js/app/components/page-title-header.vue
- client/src/js/app/components/prev-next-btngroup.vue
- client/src/js/modules/types/mx/shipment/views/mx-container-view.vue
**JIRA ticket**: [LIMS-1632](https://jira.diamond.ac.uk/browse/LIMS-1632)
**Summary**:
Provides a new component with prev/next button links to access the next & Previous containers in the Dewar when viewing a container. 
**Changes**:
- Added new page-title-header & prev-next-btgroup vue components which can display the prev/next puck in the header if target data supplied. Dumb components for the most part due to page reloads being default behaviour.
- mx-container-view.vue collates sibling containers using existing containersCollection (if exists) or by fetching the collection as required.
**To test**:
- Visit a shipment page containing a Dewar with multiple containers eg `/shipments/sid/69283`. note the order of the containers within the Dewar.
- Click through to a container of the Dewar …
> LIMS-1632: Buttons to go to next & previous puck in dewar

- client/src/js/templates/shipment/dispatch.html
**JIRA ticket**: [LIMS-1406](https://jira.diamond.ac.uk/browse/LIMS-1406)
**Summary**:
When a user requests a dewar dispatch, the current dewar location is shown, but editable. It should not be editable.
**Changes**:
- Disable the location input field
**To test**:
- Go to proposal mx23694, go to a shipment that is on site eg /shipments/sid/58389
- Click "Dispatch" and load the dispatch form
- Check the dewar location is displayed and not editable
- If only the short version of the form is shown, change the country to Aruba to see the full version
> LIMS-1406: Don't allow the location to be changed during a dispatch request

- api/src/Page/Vstat.php
- client/src/js/modules/shipment/views/dewarstats.js
- client/src/js/templates/shipment/dewarstats.html
**JIRA ticket**: [LIMS-995](https://jira.diamond.ac.uk/browse/LIMS-995)
**Summary**:
The shipment stats at https://ispyb.diamond.ac.uk/shipments/stats timeout after 1 minute. The slow joins are to BLSample and DataCollection, which are only needed if the 'With Data' tickbox is turned on.
**Changes**:
- Remove 'With Data' checkbox and associated code
- Remove joins to BLSample and DataCollection
- Remove non-functional search boxes
**To test**:
- Go to /shipments/stats, check the page loads, with a graph and 2 tables
- Check there is no 'With Data' checkbox, and no search boxes on any tables
- Check the 'With Dewar History' checkbox still works
> LIMS-995: Fix Shipment Stats page

- client/src/js/modules/dc/routes.js
**JIRA ticket**: [LIMS-1615](https://jira.diamond.ac.uk/browse/LIMS-1615)
**Summary**:
Links to eg https://ispyb.diamond.ac.uk/dc/summary/visit/cm40608-1 don't work, as the proposal is not set.
**Changes**:
- Set the proposal 'cookie' when navigating to the page. This is reverting commit https://github.com/DiamondLightSource/SynchWeb/commit/80ef089a61b8fc9ac25a7acc09eb6da6bb8dd6c2.
**To test**:
- In a new browser tab for each, go to /dc/summary/visit/cm40608-1, /dc/apstatussummary/visit/cm40608-1, /dc/sc/visit/cm40608-1 and /dc/visit/cm40608-1 and check each one loads correctly, with the proposal set.
- Try again, but log in as someone without permission to view that visit, check each page doesn't load
> LIMS-1615: Allow direct links to visit summary page

- api/src/Page/Sample.php
- client/src/js/app/store/store.js
- client/src/js/modules/samples/components/sample-group-create-and-edit.vue
- client/src/js/modules/types/mx/samples/sample-table-mixin.js
**JIRA ticket**: [LIMS-1665](https://jira.diamond.ac.uk/browse/LIMS-1665)
**Summary**:
Users need to create sample groups when setting up samples for UDC. The 'create container' screen does not indicate when this has succeeded and allows for multiple groups of the same name to be created. These groups are distinct, but indistinguishable for the user. This is causing confusion.
Sample groups should be uniquely named within a proposal and users should receive confirmation when a group is created successfully from the create container page.
**Changes**:
- Add a check that the sample group name is unique within the proposal
- Tidy the `_get_sample_groups_by_sample` function
- Fix bug where error messages were not passed through correctly
- Add success notifications for sample group creation, …
> LIMS-1665: Don't allow multiple groups with the same name

- client/src/js/modules/mc/routes.js
- client/src/js/templates/mc/datacollections.html
**JIRA ticket**: [LIMS-1663](https://jira.diamond.ac.uk/browse/LIMS-1663)
**Summary**:
If you go to eg https://ispyb.diamond.ac.uk/mc/visit/mx23694-130, there are many pages of data collections at the bottom. But the Per Page dropdown doesn't work, it always shows 15 per page.
**Changes**:
- Remove the fixed number of data collections shown per page, allowing the dropdown to work as expected
- Move the search bar down to just above the data collections as this is what it searches
**To test**:
- Go to /mc/visit/mx23694-130
- Check you can adjust the number of data collections shown in the lower half of the page by changing the dropdown
- Check the search bar now appears in the bar with "Pipeline", "Spacegroup" etc, and that the search works on data collections in the lower half of the page
> LIMS-1663: Per-page dropdown on multicrystal processing page doesnt work

- api/src/Page/DC.php
- client/src/js/modules/dc/views/grid.js
- client/src/js/templates/dc/grid.html
**JIRA ticket**: [LIMS-1637](https://jira.diamond.ac.uk/browse/LIMS-1637)
**Summary**:
If displaying a group of grid scans (eg Mesh3d experiment type), we should show some more info.
**Changes**:
- Show the data collection group comment if one exists, otherwise show the comment from the first grid scan, not the first comment alphabetically
- Show the `totalCount` of each xray centring result as 'Strength', as well as x/y/z positions
- Show the grid size for all grid scans, including the 3rd dimension for 3d grid scans
**To test**:
- Go to a visit with grid scans, eg /dc/visit/mx23694-130/ty/gr
- Check the first grid scan (from 2025-02-26 17:13:55) shows the data collection group comment ("This is a data collection group comment")
- Check the 3rd grid scan (from 2025-02-25 15:10:31) has a …
> LIMS-1637: Show more info for grid scan groups

- client/src/js/modules/dc/components/auto-processing-job-details.vue
- client/src/js/modules/dc/views/downstreamwrapper.js
- client/src/js/templates/dc/dc_autoproc.html
- client/src/js/templates/dc/downstreamerror.html
**JIRA ticket**: [LIMS-1702](https://jira.diamond.ac.uk/browse/LIMS-1702)
**Summary**:
The "Archive" button on each data processing job should be changed to say "Download Zip", as it might be confused with the iCat archive. We should also change the icon to match, and swap positions with the "Logs and Files" button, so the default behaviour is to download individual files.
The "Archive" button is in the code in 5 places, but one is commented out (which would be on the Sample Groups page). The other 4 are:
* Auto processing success
* Auto processing failure
* Downstream processing success
* Downstream processing failure
**Changes**:
- Change 'Archive' to 'Download Zip' in all places, and icon to cloud-download
- Swap places with 'Logs & Files' button
- Fix download link for auto processing …
> LIMS-1702: Rename Archive button to Download Zip

- client/src/js/modules/imaging/views/imageviewer.js
- client/src/js/modules/imaging/views/queuecontainer.js
- client/src/js/templates/imaging/queuecontainer.html
**JIRA ticket**: [LIMS-1758](https://jira.diamond.ac.uk/browse/LIMS-1758)
**Summary**:
If a plate has a lot of subsamples, then "Add All to Queue", "Unqueue All", and "Apply to All" buttons become very slow.
**Changes**:
- Fix bug where browser complains about slider being set before it exists
- Show/hide the "Unqueue All" and "Unqueue Selected" buttons depending on whether the plate is queued or not
- When queuing or unqueuing subsamples, silently update the model (so as to not trigger any GUI changes), then trigger the GUI changes once all queuing/unqueuing is done
- Modify the "Apply to all" button to show something is happening, return it to normal once the process is done
- Do "Apply to all" as chunks of 500, to avoid failing on very large numbers of subsamples
**To test**:
- Go to …
> LIMS-1758: Fix slowness with plates with lots of subsamples

- api/src/Page/Shipment.php
**JIRA ticket**: [LIMS-1714](https://jira.diamond.ac.uk/browse/LIMS-1714)
**Summary**:
When we make a shipment, we should populate the Dewar.dewarRegistryId as well as facilityCode. Then on the shipment page, we currently show the dewar facility code based on the `Dewar.facilityCode` field, we should also allow joining to `DewarRegistry` by `dewarRegistryId` and then getting the `facilityCode` from there.
**Changes**:
- Add function to get `dewarRegistryId` from facility code
- Use it to populate the `dewarRegistryId` in dewars in new shipments, edited dewars, and new dewars in existing shipments
- Display facility code based on `dewarRegistryId`, falling back to `Dewar.facilityCode` if needed
**To test**:
- Go to any proposal and create a shipment, choosing a dewar facility code from the …
> LIMS-1714: Populate Dewar.dewarRegistryId

- api/src/Page/DC.php
- client/src/js/modules/dc/collections/gridxrc.js
- client/src/js/modules/dc/models/gridxrc.js
- client/src/js/modules/dc/views/grid.js
- client/src/js/modules/dc/views/gridxrc.js
- client/src/js/templates/dc/grid.html
**JIRA ticket**: [LIMS-1701](https://jira.diamond.ac.uk/browse/LIMS-1701)
**Summary**:
As the xray centring results become more in-depth, they should be displayed as an expandable table, rather than one long string of words.
**Changes**:
- Mimic the Auto Processing view to make the Xray Centring results into a similar expandable section
- Use a table view to display each result, alongside the sample identified (if any)
- Sort results by strength by default, but that can be changed by clicking column headers
**To test**:
- Find some `XrayCentringResult` rows with non-null blsampleids, or if none found, update some, eg
```
update XrayCentringResult set blsampleid=6488514 where xrayCentringResultId=1592487;
update XrayCentringResult set blsampleid=6488511 where xrayCentringResultId=1592490; …
```
> LIMS-1701: Make Xray Centring results an openable table

- client/src/js/modules/dc/views/autoprocattachments.js
- client/src/js/modules/types/sm/dc/dc.js
**JIRA ticket**: [LIMS-1777](https://jira.diamond.ac.uk/browse/LIMS-1777)
**Summary**:
Similar to https://github.com/DiamondLightSource/SynchWeb/pull/944, the attachments view of autoprocessing on 'sm' beamlines is broken as it thinks every visit has been purged.
**Changes**:
- Pass the purged status down to DCAutoIntegrationView
- Also, assume not purged if the purged status is undefined
**To test**:
- Go to an I19 visit eg /dc/visit/cm40638-2, find a data collection with auto processing, click Logs & Files, check there are Download and View buttons, not just an iCat button.
> LIMS-1777: Fix download of autoprocessing attachments on sm beamlines

- api/src/Page/DC.php
- client/src/js/modules/mc/controller.js
- client/src/js/modules/mc/routes.js
**JIRA ticket**: [LIMS-1716](https://jira.diamond.ac.uk/browse/LIMS-1716)
**Summary**:
If you go to the multicrystal data processing page (eg /mc/visit/mx23694-136), it only shows the first data collection for any that are in a group. It should show all data collections.
**Changes**:
- Add a new `expandgroups` parameter
- Use that parameter to change the grouping on the select (and also on the counting)
**To test**:
- Go to a visit with data collection groups eg /dc/visit/mx23694-136, check groups still appear as one entry on the main page, with a link to the group ("Group: 2 Data Collections")
- Click the cog icon on any data collection, then click the "Multi Crystal" button to take you to eg /mc/visit/mx23694-136
- Check all data collections from groups are now shown separately (in the …
> LIMS-1716: Multicrystal processing only shows one DC per group

- api/src/Page/Processing.php
**JIRA ticket**: [LIMS-1718](https://jira.diamond.ac.uk/browse/LIMS-1718)
**Summary**:
We are now running extra multiplex jobs using clusters of data, and recording the cluster number in the AutoProcProgram.processingEnvironment column. We should display this info in the name of the job displayed.
(The cluster number cannot be stored in ProcessingJobParameters as all clusters are from the same processingJobId)
**Changes**:
- if the processingEnvironment starts with `cluster=`, display it as part of the job name
**To test**:
- Go to /dc/visit/nt37104-145/id/16755310, check some of the multiplex autoprocessing jobs have "cluster=0" or "cluster=1" as part of the job name
> LIMS-1718: Display cluster info on multiplex jobs

- api/src/Downstream/Type/FastEp.php
- client/src/js/modules/dc/views/fastep.js
**JIRA ticket**: [LIMS-1688](https://jira.diamond.ac.uk/browse/LIMS-1688)
**Summary**:
If the filesystem with FastEP results on is not mounted, (or we cannot get the files for some reason), the whole downstream processing bar won't display.
**Changes**:
- Prepopulate the results data with error messages, that will be overwritten when results are found
- Check there is plotting data returned before attempting to plot a graph
**To test**:
- Start a synchweb instance on a machine without /dls/ mounted
- Go to a data collection with FastEP results, eg /dc/visit/cm40607-3/id/18552850
- Click on Downstream Processing, check it expands to show results
- Click on FastEP, check it displays that the files are not found, and no graph is displayed
- Mount /dls and refresh the page
- Check there are …
> LIMS-1688: Downstream processing wont display if filesystem not mounted

- api/config_sample.php
- api/index.php
- api/src/Page/Shipment.php
- client/src/js/modules/shipment/views/dewars.js
- client/src/js/modules/shipment/views/dispatch.js
- client/src/js/modules/shipment/views/shipment.js
- client/src/js/modules/shipment/views/shipmentadd.js
- client/src/js/templates/shipment/shipment.html
- client/src/js/utils/editable.js
**JIRA ticket**: [LIMS-1739](https://jira.diamond.ac.uk/browse/LIMS-1739)
**Summary**:
If a user has selected "I would like a session to be scheduled" when creating a shipment, it is hard to know when they have created all the dewars and pucks within the shipment. We should have a button to say "My shipment is ready for scheduling". When the user has pressed this button, we should disable creating new dewars and pucks.
**Changes**:
- Scheduling status is stored as JSON in the Shipping.extra column, under the 'DYNAMIC' key
- Get scheduling status when getting dewars, so can hide the 'Add Container' button
- Add new button for users to click when a shipment has all the dewars and pucks created
- Only show the new button if the scheduling status is 'I would like a session to be scheduled'
- …
> LIMS-1739: Add button to say shipment is ready for scheduling

- client/src/css/partials/_content.scss
- client/src/js/modules/dc/views/apstatusitem.js
- client/src/js/modules/dc/views/dc.js
- client/src/js/modules/dc/views/grid.js
- client/src/js/templates/dc/dc.html
- client/src/js/templates/dc/dc_strategy.html
- client/src/js/templates/dc/dc_xoalign.html
- client/src/js/templates/dc/grid.html
**JIRA ticket**: [LIMS-1780](https://jira.diamond.ac.uk/browse/LIMS-1780)
**JIRA ticket**: [LIMS-1787](https://jira.diamond.ac.uk/browse/LIMS-1787)
**Summary**:
The dials.align_crystal strategy pipeline is run on data collections of type 'characterization', we should display the results.
Some grid scans also have xia2.ssx run on them, we should display the results.
**Changes**:
- Move the logic of which result bars to display out of the HTML template and into the JS
- Show both strategies and processing if data collection type is 'characterization', otherwise unchanged
- Give strategy results a h2 header as h1 seems to be ignored (downstream results use h2 also)
- Show auto processing bar on grid scans if results are available
**To test**:
- Go to a characterization data collection (eg …
> LIMS-1780 / LIMS-1787: Show strategies on characterizations, auto processing on grid scans

- api/src/Page/Download.php
- client/src/js/modules/dc/views/attachments.js
- client/src/js/modules/dc/views/autoprocattachments.js
**JIRA ticket**: [LIMS-1796](https://jira.diamond.ac.uk/browse/LIMS-1796)
**Summary**:
Where autoprocessing jobs have run is a bit of a mystery within Synchweb. But one thing we can do simply is to display the filepath to any attachments.
**Changes**:
- Add a file path column to the data collection Attachments view, auto processing attachments view and the downstream processing attachments view
- Truncate the path to prevent it being too wide, but display the full path in a tooltip, and add a button to copy to the clipboard
**To test**:
- Deploy to a https server, otherwise clipboard integration doesn't work. At the time of writing this branch is on ispyb-dev-1
- Go to a data collection with attachments, auto processing attachments and downstream processing attachments (eg …
> LIMS-1796: Display filepath for attachments

- client/src/js/modules/dc/views/dc.js
- client/src/js/modules/types/gen/dc/dc.js
- client/src/js/modules/types/pow/dc/dc.js
- client/src/js/modules/types/saxs/dc/dc.js
- client/src/js/modules/types/sm/dc/dc.js
- client/src/js/modules/types/tomo/dc/dc.js
- client/src/js/modules/types/xpdf/dc/dc.js
**JIRA ticket**: [LIMS-1833](https://jira.diamond.ac.uk/browse/LIMS-1833)
**Summary**:
PR https://github.com/DiamondLightSource/SynchWeb/pull/956 broke the data collection view for some non-MX villages (eg XPDF), by trying to hide a non-existing strategies or auto processing bar.
**Changes**:
- Move setup of showStrategies and showProcessing into it's own function, then override it for each non-MX village.
**To test**:
- Repeat tests from https://github.com/DiamondLightSource/SynchWeb/pull/956
- Go to an XPDF visit (eg /dc/visit/cm40633-3), check data collections are visible, as well as Data Files and Auto Processing bars
- Repeat for an Generic visit (eg /dc/visit/cm40629-2)
- Repeat for a SAXS visit (eg /dc/visit/cm40642-3)
- Repeat for a Small Molecule visit (eg /dc/visit/cm40638-3), …
> LIMS-1833: Fix XPDF DC view

- api/src/Page/Download.php
**JIRA ticket**: [LIMS-1845](https://jira.diamond.ac.uk/browse/LIMS-1845)
**Summary**:
PR https://github.com/DiamondLightSource/SynchWeb/pull/959 broke the dropdown for VMXi grid scans, where it shows the name of each attachment on a dropdown. This is to fix that.
**Changes**:
- Re-add the 'NAME' field to the returned info
**To test**:
- Go to a VMXi grid scan, eg /dc/visit/nt37104-125/id/19041028
- Check there are 2 dropdowns on the image, one for choosing between image 1-4 (unchanged) and one for choosing between 'pia_total_intensity', 'pia_n_spots_total', 'pia_estimated_d_min', 'pia_n_spots_no_ice' and 'None'
- Check each one shows the data slightly differently
> LIMS-1845: Fix broken VMXi attachment names

- api/src/Page/Proposal.php
**JIRA ticket**: [LIMS-1848](https://jira.diamond.ac.uk/browse/LIMS-1848)
**Summary**:
When creating a new container, for some proposals eg mx34438, no container types are displayed to the user. This was caused by https://github.com/DiamondLightSource/SynchWeb/pull/960
**Changes**:
- Uniquify beamline types before inserting into the $tys array, rather than after
**To test**:
- Go to proposal mx34338, create a container, check container types for mx and saxs are shown
- Repeat for mx23694, check only mx types are shown
- Repeat for nt40910, check mx and sm types are shown
> LIMS-1848: Fix bug where no container types are available

- api/src/Page/Proposal.php
**Summary**:
Sometimes, the proposal type is set to "null" during the process in which we determine the proposal type, and therefore, defaults to "gen". This checks that the determined proposal type is not null before assigning it to the final proposal object.
**Changes**:
- Fix proposal type assignment
**To test**:
- Go to any older proposal that may get a `null` proposal type from `_get_type_from_beamline` (such as sw30864)
- Check that the menu displays all MX options, instead of the generic, shortened menu
- Go to any "recent" proposal such as cm40607, check that MX options are displayed
- Go to any recent VMXi proposal, such as cm40605, check that VMXi options are displayed
- Repeat for other experiment types if so desired
> Fix proposal type assignment

- api/src/Page/Shipment.php
- client/src/js/modules/shipment/components/plate-view.vue
- client/src/js/modules/types/mx/samples/valid-container-graphic.vue
- client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
**JIRA ticket**: [LIMS-1856](https://jira.diamond.ac.uk/browse/LIMS-1856)
**Summary**:
The reservoir for a MRC 2 Drop plate is on the left side, but Synchweb shows it on the right. The database has dropOffsetX=0.5, but this is not used anywhere.
**Changes**:
- Pull the drop offset values from the database and pass them to the client
- Use the offsets to move the drops around in the well. Drop offset values should be between 0 and 1.
**To test**:
- Go to any proposal, then add a container to a shipment
- Choose container type MRC 2 Drop, check the drops are on the right and the reservoir on the left
- Create the container, check there are no errors.
- View the created container, check the layout is still the same (this is rendered in a different way and is unchanged)
> LIMS-1856: Fix offset for plates

- api/src/Page/DC.php
**JIRA ticket**: [LIMS-1839](https://jira.diamond.ac.uk/browse/LIMS-1839)
**Summary**:
Fast dp radiation damage plots stopped working when some fast_dp files were moved to a different folder.
**Changes**:
- Search specifically for the xdsstat.log file, not just any fast_dp file
**To test**:
- Go to a recent data collection with successful fast_dp (eg /dc/visit/cm40607-3/id/19021858)
- Click on Auto Processing, choose the fast_dp tab, then click Radiation Damage. Check a plot appears.
- Repeat for an older data collection before the files were moved (eg /dc/visit/cm40607-1/id/17183638)
> LIMS-1839: Fix fast_dp radiation damage plots

- api/src/Page/Shipment.php
- client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
**JIRA ticket**: [LIMS-1804](https://jira.diamond.ac.uk/browse/LIMS-1804)
**Summary**:
Barcode should be a required field for plates
**Changes**:
- Add a validation of required to the barcode field
- Combine the error message with the message about uniqueness
- If a user does try and add a barcode that is already used, catch the database error and return a sensible message
**To test**:
- Go to any shipment in any proposal, eg /shipments/sid/65577, and click Add Container
- Create a puck, checking that barcode is not a required field
- Create a plate (eg container type of CrystalQuickX), try to leave the barcode field blank, check you get an error
- Try a barcode that already exists (eg "a"), check you get a sensible error message
- Try a unique barcode, check you can create the plate (no …
> LIMS-1804: Make barcode be required for new plates

- client/src/js/modules/shipment/views/shipments.js
**JIRA ticket**: [LIMS-1786](https://jira.diamond.ac.uk/browse/LIMS-1786)
**Summary**:
Much like the /visits page has a column for dewars, we should do the same for the /shipments page.
**Changes**:
- Add a dewars column
- Merge the Outgoing and Return Contacts columns into one column, displaying both if they are different
- Edit the column numbers that should be hidden on mobile
**To test**:
- Go to a proposal, then go to /shipments
- Check there is a Dewar(s) column, with the dewar name(s) in it
- Check there is a single Lab Contact field
- Edit a shipment so it has different outgoing and return lab contacts, check both are displayed on the shipments page
> LIMS-1786: Add Dewars column to Shipments page

- client/src/js/modules/shipment/models/platetype.js
- client/src/js/modules/shipment/views/containerplate.js
- client/src/js/modules/shipment/views/plate.js
**JIRA ticket**: [LIMS-1902](https://jira.diamond.ac.uk/browse/LIMS-1902)
**Summary**:
The MRC 2 Drop plate type is the only one with a drop_offset_x value, and it has not been used much. https://github.com/DiamondLightSource/SynchWeb/pull/973 fixed the display on creating such a plate and on first viewing it, but there is another view once the plate has inspections to view. This is to fix that view.
**Changes**:
- Use a new property to store the drop offset in pixels, so the offset isn't repeatedly converted
- Use the new offset pixels property to display the drop, the drop number, and to calculate the position for clicking/hovering
- Make the container type check be case-insensitive
**To test**:
- View a plate with inspections eg (/containers/cid/349468)
- Edit the plate in the database …
> LIMS-1902: Fix plate inspection view for MRC 2 Drop plates

- api/src/Downstream/Type/Dimple.php
- client/src/css/partials/_content.scss
- client/src/js/modules/dc/views/dimple.js
- client/src/js/templates/dc/dc_dimple.html
- client/src/js/utils/xhrimage.js
**JIRA ticket**: [LIMS-124](https://jira.diamond.ac.uk/browse/LIMS-124)
**Summary**:
Anode has been running at the end of Dimple for a few years, we should display the results in Synchweb, not just in obscure log files.
NB This PR does not include a map viewer for Anode results, but that is intended to follow at some point, ticket LIMS-598.
**Screenshot**:
**Changes**:
- Add method to the backend to return Anode results with the Dimple results
- Add a table of Anode results to the Dimple view, under the table of Dimple results
- Add a plot of peak height vs site number, under the Dimple plot
- Fix a bug in xhrimage if onerror is not defined
**To test**:
- Go to a data collection with a Dimple success eg /dc/visit/cm40607-3/id/19541770
- Expand the Downstream Processing bar, and click the …
> LIMS-124: Display Anode results
